/* verilator lint_off PINMISSING */
/* verilator lint_off CASEINCOMPLETE */
/* verilator lint_off COMBDLY */
/* verilator lint_off CASEX */
/* verilator lint_off CASEOVERLAP */
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="YZ_YZ,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvc1902-vsva2197-2MP-e-S,HLS_INPUT_CLOCK=2.500000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=1.337000,HLS_SYN_LAT=645,HLS_SYN_TPT=646,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=293,HLS_SYN_LUT=819,HLS_VERSION=2022_2}" *)

module YZ (
        y_stream_TDATA,
        y_s_stream_TDATA,
        z_stream_TDATA,
        z_s_stream_TDATA,
        o_stream_TDATA,
        ap_clk,
        ap_rst_n,
        y_stream_TVALID,
        y_stream_TREADY,
        y_s_stream_TVALID,
        y_s_stream_TREADY,
        z_stream_TVALID,
        z_stream_TREADY,
        z_s_stream_TVALID,
        z_s_stream_TREADY,
        o_stream_TVALID,
        o_stream_TREADY,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [63:0] y_stream_TDATA;
input  [7:0] y_s_stream_TDATA;
input  [63:0] z_stream_TDATA;
input  [7:0] z_s_stream_TDATA;
output  [255:0] o_stream_TDATA;
input   ap_clk;
input   ap_rst_n;
input   y_stream_TVALID;
output   y_stream_TREADY;
input   y_s_stream_TVALID;
output   y_s_stream_TREADY;
input   z_stream_TVALID;
output   z_stream_TREADY;
input   z_s_stream_TVALID;
output   z_s_stream_TREADY;
output   o_stream_TVALID;
input   o_stream_TREADY;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire   [255:0] do_yz_U0_o_stream_TDATA;
 reg    ap_rst_n_inv;
wire    do_yz_U0_y_stream_TREADY;
wire    do_yz_U0_y_s_stream_TREADY;
wire    do_yz_U0_z_stream_TREADY;
wire    do_yz_U0_z_s_stream_TREADY;
wire    do_yz_U0_o_stream_TVALID;
wire    do_yz_U0_ap_start;
wire    do_yz_U0_ap_done;
wire    do_yz_U0_ap_ready;
wire    do_yz_U0_ap_idle;
wire    do_yz_U0_ap_continue;

YZ_do_yz do_yz_U0(
    .y_stream_TDATA(y_stream_TDATA),
    .y_s_stream_TDATA(y_s_stream_TDATA),
    .z_stream_TDATA(z_stream_TDATA),
    .z_s_stream_TDATA(z_s_stream_TDATA),
    .o_stream_TDATA(do_yz_U0_o_stream_TDATA),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .y_stream_TVALID(y_stream_TVALID),
    .y_stream_TREADY(do_yz_U0_y_stream_TREADY),
    .y_s_stream_TVALID(y_s_stream_TVALID),
    .y_s_stream_TREADY(do_yz_U0_y_s_stream_TREADY),
    .z_stream_TVALID(z_stream_TVALID),
    .z_stream_TREADY(do_yz_U0_z_stream_TREADY),
    .z_s_stream_TVALID(z_s_stream_TVALID),
    .z_s_stream_TREADY(do_yz_U0_z_s_stream_TREADY),
    .o_stream_TVALID(do_yz_U0_o_stream_TVALID),
    .o_stream_TREADY(o_stream_TREADY),
    .ap_start(do_yz_U0_ap_start),
    .ap_done(do_yz_U0_ap_done),
    .ap_ready(do_yz_U0_ap_ready),
    .ap_idle(do_yz_U0_ap_idle),
    .ap_continue(do_yz_U0_ap_continue)
);

assign ap_done = do_yz_U0_ap_done;

assign ap_idle = do_yz_U0_ap_idle;

assign ap_ready = do_yz_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign do_yz_U0_ap_continue = ap_continue;

assign do_yz_U0_ap_start = ap_start;

assign o_stream_TDATA = do_yz_U0_o_stream_TDATA;

assign o_stream_TVALID = do_yz_U0_o_stream_TVALID;

assign y_s_stream_TREADY = do_yz_U0_y_s_stream_TREADY;

assign y_stream_TREADY = do_yz_U0_y_stream_TREADY;

assign z_s_stream_TREADY = do_yz_U0_z_s_stream_TREADY;

assign z_stream_TREADY = do_yz_U0_z_stream_TREADY;

endmodule //YZ
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module YZ_do_yz (
        y_stream_TDATA,
        y_s_stream_TDATA,
        z_stream_TDATA,
        z_s_stream_TDATA,
        o_stream_TDATA,
        ap_clk,
        ap_rst,
        y_stream_TVALID,
        y_stream_TREADY,
        y_s_stream_TVALID,
        y_s_stream_TREADY,
        z_stream_TVALID,
        z_stream_TREADY,
        z_s_stream_TVALID,
        z_s_stream_TREADY,
        o_stream_TVALID,
        o_stream_TREADY,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [63:0] y_stream_TDATA;
input  [7:0] y_s_stream_TDATA;
input  [63:0] z_stream_TDATA;
input  [7:0] z_s_stream_TDATA;
output  [255:0] o_stream_TDATA;
input   ap_clk;
input   ap_rst;
input   y_stream_TVALID;
output   y_stream_TREADY;
input   y_s_stream_TVALID;
output   y_s_stream_TREADY;
input   z_stream_TVALID;
output   z_stream_TREADY;
input   z_s_stream_TVALID;
output   z_s_stream_TREADY;
output   o_stream_TVALID;
input   o_stream_TREADY;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_start;
wire    do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_done;
wire    do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_continue;
wire    do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_idle;
wire    do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_ready;
wire    do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_y_stream_TREADY;
wire    do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_y_s_stream_TREADY;
wire    do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_z_stream_TREADY;
wire    do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_z_s_stream_TREADY;
wire   [255:0] do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_o_stream_TDATA;
wire    do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_o_stream_TVALID;

YZ_do_yz_Loop_VITIS_LOOP_30_1_proc1 do_yz_Loop_VITIS_LOOP_30_1_proc1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_start),
    .ap_done(do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_done),
    .ap_continue(do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_continue),
    .ap_idle(do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_idle),
    .ap_ready(do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_ready),
    .y_stream_TVALID(y_stream_TVALID),
    .y_s_stream_TVALID(y_s_stream_TVALID),
    .z_stream_TVALID(z_stream_TVALID),
    .z_s_stream_TVALID(z_s_stream_TVALID),
    .o_stream_TREADY(o_stream_TREADY),
    .y_stream_TDATA(y_stream_TDATA),
    .y_stream_TREADY(do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_y_stream_TREADY),
    .y_s_stream_TDATA(y_s_stream_TDATA),
    .y_s_stream_TREADY(do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_y_s_stream_TREADY),
    .z_stream_TDATA(z_stream_TDATA),
    .z_stream_TREADY(do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_z_stream_TREADY),
    .z_s_stream_TDATA(z_s_stream_TDATA),
    .z_s_stream_TREADY(do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_z_s_stream_TREADY),
    .o_stream_TDATA(do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_o_stream_TDATA),
    .o_stream_TVALID(do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_o_stream_TVALID)
);

assign ap_done = do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_done;

assign ap_idle = do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_idle;

assign ap_ready = do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_ready;

assign do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_continue = ap_continue;

assign do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_ap_start = ap_start;

assign o_stream_TDATA = do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_o_stream_TDATA;

assign o_stream_TVALID = do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_o_stream_TVALID;

assign y_s_stream_TREADY = do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_y_s_stream_TREADY;

assign y_stream_TREADY = do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_y_stream_TREADY;

assign z_s_stream_TREADY = do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_z_s_stream_TREADY;

assign z_stream_TREADY = do_yz_Loop_VITIS_LOOP_30_1_proc1_U0_z_stream_TREADY;

endmodule //YZ_do_yz
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module YZ_do_yz_Loop_VITIS_LOOP_30_1_proc1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        y_stream_TVALID,
        y_s_stream_TVALID,
        z_stream_TVALID,
        z_s_stream_TVALID,
        o_stream_TREADY,
        y_stream_TDATA,
        y_stream_TREADY,
        y_s_stream_TDATA,
        y_s_stream_TREADY,
        z_stream_TDATA,
        z_stream_TREADY,
        z_s_stream_TDATA,
        z_s_stream_TREADY,
        o_stream_TDATA,
        o_stream_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   y_stream_TVALID;
input   y_s_stream_TVALID;
input   z_stream_TVALID;
input   z_s_stream_TVALID;
input   o_stream_TREADY;
input  [63:0] y_stream_TDATA;
output   y_stream_TREADY;
input  [7:0] y_s_stream_TDATA;
output   y_s_stream_TREADY;
input  [63:0] z_stream_TDATA;
output   z_stream_TREADY;
input  [7:0] z_s_stream_TDATA;
output   z_s_stream_TREADY;
output  [255:0] o_stream_TDATA;
output   o_stream_TVALID;

reg ap_idle;
reg o_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln30_fu_167_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    regslice_both_o_stream_U_apdone_blk;
reg    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter3_reg;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
wire    y_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
wire    y_s_stream_TDATA_blk_n;
wire    z_stream_TDATA_blk_n;
wire    z_s_stream_TDATA_blk_n;
wire    o_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] trunc_ln32_fu_173_p1;
reg  signed [7:0] trunc_ln32_reg_713;
reg  signed [7:0] trunc_ln32_6_reg_718;
reg  signed [7:0] trunc_ln32_7_reg_723;
reg  signed [7:0] tmp_i_reg_728;
reg  signed [7:0] tmp_1_i_reg_733;
reg  signed [7:0] tmp_2_i_reg_738;
reg  signed [7:0] tmp_3_i_reg_743;
reg  signed [7:0] tmp_4_i_reg_748;
wire   [7:0] trunc_ln34_fu_255_p1;
reg  signed [7:0] trunc_ln34_reg_753;
reg  signed [7:0] trunc_ln34_6_reg_758;
reg  signed [7:0] trunc_ln34_7_reg_763;
reg  signed [7:0] tmp_8_i_reg_768;
reg  signed [7:0] tmp_9_i_reg_773;
reg  signed [7:0] tmp_i_20_reg_778;
reg  signed [7:0] tmp_10_i_reg_783;
reg  signed [7:0] tmp_11_i_reg_788;
wire   [4:0] ret_V_fu_337_p2;
reg   [4:0] ret_V_reg_793;
reg   [4:0] ret_V_reg_793_pp0_iter1_reg;
reg   [4:0] ret_V_reg_793_pp0_iter2_reg;
wire  signed [15:0] grp_fu_375_p2;
reg  signed [15:0] ret_V_1_reg_878;
wire  signed [15:0] grp_fu_384_p2;
reg  signed [15:0] ret_V_2_reg_883;
wire  signed [15:0] grp_fu_393_p2;
reg  signed [15:0] ret_V_3_reg_888;
wire  signed [15:0] grp_fu_402_p2;
reg  signed [15:0] ret_V_4_reg_893;
wire  signed [15:0] grp_fu_411_p2;
reg  signed [15:0] ret_V_5_reg_898;
wire  signed [15:0] grp_fu_420_p2;
reg  signed [15:0] ret_V_6_reg_903;
wire  signed [15:0] grp_fu_429_p2;
reg  signed [15:0] ret_V_7_reg_908;
wire  signed [15:0] grp_fu_438_p2;
reg  signed [15:0] ret_V_8_reg_913;
reg   [9:0] ct_fu_118;
wire   [9:0] ct_2_fu_161_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_ct_1;
wire    ap_block_pp0_stage0_01001;
wire   [3:0] lhs_V_fu_247_p1;
wire   [3:0] rhs_V_fu_329_p1;
wire   [4:0] zext_ln186_1_fu_333_p1;
wire   [4:0] zext_ln186_fu_251_p1;
wire  signed [33:0] sext_ln42_8_fu_465_p1;
wire   [33:0] sh_prom_i_i_i_fu_468_p1;
wire  signed [33:0] sext_ln42_7_fu_462_p1;
wire  signed [33:0] sext_ln42_6_fu_459_p1;
wire  signed [33:0] sext_ln42_5_fu_456_p1;
wire  signed [33:0] sext_ln42_4_fu_453_p1;
wire  signed [33:0] sext_ln42_3_fu_450_p1;
wire  signed [33:0] sext_ln42_2_fu_447_p1;
wire  signed [33:0] sext_ln42_fu_444_p1;
wire   [33:0] r_V_fu_513_p2;
wire   [23:0] trunc_ln2_fu_519_p4;
wire   [33:0] r_V_6_fu_477_p2;
wire   [23:0] trunc_ln1669_6_fu_533_p4;
wire   [33:0] r_V_7_fu_471_p2;
wire   [33:0] r_V_1_fu_507_p2;
wire   [33:0] r_V_2_fu_501_p2;
wire   [33:0] r_V_3_fu_495_p2;
wire   [33:0] r_V_4_fu_489_p2;
wire   [33:0] r_V_5_fu_483_p2;
wire   [22:0] tmp_s_fu_597_p4;
wire   [22:0] tmp_5_fu_611_p4;
wire   [22:0] tmp_6_fu_625_p4;
wire   [22:0] tmp_7_fu_639_p4;
wire   [22:0] tmp_8_fu_653_p4;
wire   [23:0] trunc_ln1669_7_fu_547_p4;
wire  signed [31:0] sext_ln42_9_fu_543_p1;
wire  signed [30:0] sext_ln44_4_fu_663_p1;
wire   [0:0] tmp_4_fu_589_p3;
wire  signed [30:0] sext_ln44_3_fu_649_p1;
wire   [0:0] tmp_3_fu_581_p3;
wire  signed [30:0] sext_ln44_2_fu_635_p1;
wire   [0:0] tmp_2_fu_573_p3;
wire  signed [30:0] sext_ln44_1_fu_621_p1;
wire   [0:0] tmp_1_fu_565_p3;
wire  signed [30:0] sext_ln44_fu_607_p1;
wire   [0:0] tmp_fu_557_p3;
wire  signed [31:0] sext_ln42_1_fu_529_p1;
wire   [247:0] tmp_9_fu_667_p14;
wire    ap_continue_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_done_int_frp;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [4:0] frp_pipeline_valid_U_valid_out;
wire   [3:0] frp_pipeline_valid_U_num_valid_datasets;
wire   [255:0] pf_o_stream_U_data_out;
wire    pf_o_stream_U_data_out_vld;
wire    pf_o_stream_U_pf_ready;
wire    pf_o_stream_U_pf_done;
reg    ap_condition_frp_pvb_no_fwd_prs;
reg    ap_condition_frp_pvb_no_bkwd_prs;
reg    ap_condition_frp_pvb_pf_start;
reg    ap_frp_vld_in;
reg    frp_pipeline_valid_U_exitcond;
reg    pf_o_stream_U_data_in_vld;
wire   [255:0] pf_o_stream_U_frpsig_data_in;
reg    pf_all_done;
wire    regslice_both_y_stream_U_apdone_blk;
wire   [63:0] y_stream_TDATA_int_regslice;
wire    y_stream_TVALID_int_regslice;
reg    y_stream_TREADY_int_regslice;
wire    regslice_both_y_stream_U_ack_in;
wire    regslice_both_y_s_stream_U_apdone_blk;
wire   [7:0] y_s_stream_TDATA_int_regslice;
wire    y_s_stream_TVALID_int_regslice;
reg    y_s_stream_TREADY_int_regslice;
wire    regslice_both_y_s_stream_U_ack_in;
wire    regslice_both_z_stream_U_apdone_blk;
wire   [63:0] z_stream_TDATA_int_regslice;
wire    z_stream_TVALID_int_regslice;
reg    z_stream_TREADY_int_regslice;
wire    regslice_both_z_stream_U_ack_in;
wire    regslice_both_z_s_stream_U_apdone_blk;
wire   [7:0] z_s_stream_TDATA_int_regslice;
wire    z_s_stream_TVALID_int_regslice;
reg    z_s_stream_TREADY_int_regslice;
wire    regslice_both_z_s_stream_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_CS_fsm = 1'd1;
//#0 ap_done_reg = 1'b0;
//#0 pf_all_done = 1'b0;
end

YZ_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln34_reg_753),
    .din1(trunc_ln32_reg_713),
    .ce(1'b1),
    .dout(grp_fu_375_p2)
);

YZ_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_8_i_reg_768),
    .din1(tmp_i_reg_728),
    .ce(1'b1),
    .dout(grp_fu_384_p2)
);

YZ_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_9_i_reg_773),
    .din1(tmp_1_i_reg_733),
    .ce(1'b1),
    .dout(grp_fu_393_p2)
);

YZ_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_i_20_reg_778),
    .din1(tmp_2_i_reg_738),
    .ce(1'b1),
    .dout(grp_fu_402_p2)
);

YZ_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_10_i_reg_783),
    .din1(tmp_3_i_reg_743),
    .ce(1'b1),
    .dout(grp_fu_411_p2)
);

YZ_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_11_i_reg_788),
    .din1(tmp_4_i_reg_748),
    .ce(1'b1),
    .dout(grp_fu_420_p2)
);

YZ_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln34_6_reg_758),
    .din1(trunc_ln32_6_reg_718),
    .ce(1'b1),
    .dout(grp_fu_429_p2)
);

YZ_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln34_7_reg_763),
    .din1(trunc_ln32_7_reg_723),
    .ce(1'b1),
    .dout(grp_fu_438_p2)
);

YZ_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(pf_all_done),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(pf_all_done),
    .ap_continue(ap_continue)
);

YZ_frp_pipeline_valid #(
    .PipelineLatency( 5 ),
    .PipelineII( 1 ),
    .CeilLog2Stages( 3 ),
    .ExitLatency( 0 ))
frp_pipeline_valid_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .valid_in(ap_frp_vld_in),
    .exitcond(frp_pipeline_valid_U_exitcond),
    .valid_out(frp_pipeline_valid_U_valid_out),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

YZ_frp_fifoout #(
    .BlockingType( 1 ),
    .PipeLatency( 5 ),
    .PipelineII( 1 ),
    .DataWidth( 256 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 3 ),
    .CeilLog2FDepth( 3 ),
    .PfAllDoneEnable( 2 ))
pf_o_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_o_stream_U_frpsig_data_in),
    .data_out(pf_o_stream_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(pf_o_stream_U_data_in_vld),
    .data_out_vld(pf_o_stream_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(ap_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_o_stream_U_pf_ready),
    .pf_done(pf_o_stream_U_pf_done),
    .data_out_read(o_stream_TREADY),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

YZ_regslice_both #(
    .DataWidth( 64 ))
regslice_both_y_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(y_stream_TDATA),
    .vld_in(y_stream_TVALID),
    .ack_in(regslice_both_y_stream_U_ack_in),
    .data_out(y_stream_TDATA_int_regslice),
    .vld_out(y_stream_TVALID_int_regslice),
    .ack_out(y_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_y_stream_U_apdone_blk)
);

YZ_regslice_both #(
    .DataWidth( 8 ))
regslice_both_y_s_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(y_s_stream_TDATA),
    .vld_in(y_s_stream_TVALID),
    .ack_in(regslice_both_y_s_stream_U_ack_in),
    .data_out(y_s_stream_TDATA_int_regslice),
    .vld_out(y_s_stream_TVALID_int_regslice),
    .ack_out(y_s_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_y_s_stream_U_apdone_blk)
);

YZ_regslice_both #(
    .DataWidth( 64 ))
regslice_both_z_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(z_stream_TDATA),
    .vld_in(z_stream_TVALID),
    .ack_in(regslice_both_z_stream_U_ack_in),
    .data_out(z_stream_TDATA_int_regslice),
    .vld_out(z_stream_TVALID_int_regslice),
    .ack_out(z_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_z_stream_U_apdone_blk)
);

YZ_regslice_both #(
    .DataWidth( 8 ))
regslice_both_z_s_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(z_s_stream_TDATA),
    .vld_in(z_s_stream_TVALID),
    .ack_in(regslice_both_z_s_stream_U_ack_in),
    .data_out(z_s_stream_TDATA_int_regslice),
    .vld_out(z_s_stream_TVALID_int_regslice),
    .ack_out(z_s_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_z_s_stream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        pf_all_done <= 1'b0;
    end else begin
        pf_all_done <= pf_o_stream_U_pf_done;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[3'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln30_fu_167_p2 == 1'd0)))) begin
        ct_fu_118 <= ct_2_fu_161_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ct_fu_118 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ret_V_reg_793_pp0_iter1_reg <= ret_V_reg_793;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ret_V_1_reg_878 <= grp_fu_375_p2;
        ret_V_2_reg_883 <= grp_fu_384_p2;
        ret_V_3_reg_888 <= grp_fu_393_p2;
        ret_V_4_reg_893 <= grp_fu_402_p2;
        ret_V_5_reg_898 <= grp_fu_411_p2;
        ret_V_6_reg_903 <= grp_fu_420_p2;
        ret_V_7_reg_908 <= grp_fu_429_p2;
        ret_V_8_reg_913 <= grp_fu_438_p2;
        ret_V_reg_793_pp0_iter2_reg <= ret_V_reg_793_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln30_fu_167_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_V_reg_793 <= ret_V_fu_337_p2;
        tmp_10_i_reg_783 <= {{z_stream_TDATA_int_regslice[39:32]}};
        tmp_11_i_reg_788 <= {{z_stream_TDATA_int_regslice[47:40]}};
        tmp_1_i_reg_733 <= {{y_stream_TDATA_int_regslice[23:16]}};
        tmp_2_i_reg_738 <= {{y_stream_TDATA_int_regslice[31:24]}};
        tmp_3_i_reg_743 <= {{y_stream_TDATA_int_regslice[39:32]}};
        tmp_4_i_reg_748 <= {{y_stream_TDATA_int_regslice[47:40]}};
        tmp_8_i_reg_768 <= {{z_stream_TDATA_int_regslice[15:8]}};
        tmp_9_i_reg_773 <= {{z_stream_TDATA_int_regslice[23:16]}};
        tmp_i_20_reg_778 <= {{z_stream_TDATA_int_regslice[31:24]}};
        tmp_i_reg_728 <= {{y_stream_TDATA_int_regslice[15:8]}};
        trunc_ln32_6_reg_718 <= {{y_stream_TDATA_int_regslice[55:48]}};
        trunc_ln32_7_reg_723 <= {{y_stream_TDATA_int_regslice[63:56]}};
        trunc_ln32_reg_713 <= trunc_ln32_fu_173_p1;
        trunc_ln34_6_reg_758 <= {{z_stream_TDATA_int_regslice[55:48]}};
        trunc_ln34_7_reg_763 <= {{z_stream_TDATA_int_regslice[63:56]}};
        trunc_ln34_reg_753 <= trunc_ln34_fu_255_p1;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[3'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln30_fu_167_p2 == 1'd1)))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int_frp = 1'b1;
    end else begin
        ap_done_int_frp = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[3'd1] == 1'b1)) begin
        ap_enable_reg_pp0_iter1 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter1 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[3'd2] == 1'b1)) begin
        ap_enable_reg_pp0_iter2 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter2 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[3'd3] == 1'b1)) begin
        ap_enable_reg_pp0_iter3 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter3 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[3'd4] == 1'b1)) begin
        ap_enable_reg_pp0_iter4 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_condition_frp_pvb_pf_start) & (1'b1 == ap_condition_frp_pvb_no_bkwd_prs) & (1'b1 == ap_condition_frp_pvb_no_fwd_prs))) begin
        ap_frp_vld_in = 1'b1;
    end else begin
        ap_frp_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (frp_pipeline_valid_U_valid_out[3'd0] == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ct_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_ct_1 = ct_fu_118;
    end
end

always @ (*) begin
    if (((icmp_ln30_fu_167_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        frp_pipeline_valid_U_exitcond = 1'b1;
    end else begin
        frp_pipeline_valid_U_exitcond = 1'b0;
    end
end

always @ (*) begin
    if ((pf_o_stream_U_data_out_vld == 1'b1)) begin
        o_stream_TVALID = 1'b1;
    end else begin
        o_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        pf_o_stream_U_data_in_vld = 1'b1;
    end else begin
        pf_o_stream_U_data_in_vld = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[3'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln30_fu_167_p2 == 1'd0)))) begin
        y_s_stream_TREADY_int_regslice = 1'b1;
    end else begin
        y_s_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[3'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln30_fu_167_p2 == 1'd0)))) begin
        y_stream_TREADY_int_regslice = 1'b1;
    end else begin
        y_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[3'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln30_fu_167_p2 == 1'd0)))) begin
        z_s_stream_TREADY_int_regslice = 1'b1;
    end else begin
        z_s_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[3'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln30_fu_167_p2 == 1'd0)))) begin
        z_stream_TREADY_int_regslice = 1'b1;
    end else begin
        z_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = 1'b0;

assign ap_block_pp0_stage0_01001 = 1'b0;

assign ap_block_pp0_stage0_11001 = 1'b0;

assign ap_block_pp0_stage0_subdone = 1'b0;

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((icmp_ln30_fu_167_p2 == 1'd0) & (1'b1 == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((regslice_both_o_stream_U_apdone_blk == 1'b1) | (1'b1 == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter4 = (1'b1 == 1'b0);

always @ (*) begin
    ap_condition_frp_pvb_no_bkwd_prs = (pf_o_stream_U_pf_ready == 1'b1);
end

always @ (*) begin
    ap_condition_frp_pvb_no_fwd_prs = ~(((z_s_stream_TVALID_int_regslice == 1'b0) & (icmp_ln30_fu_167_p2 == 1'd0)) | ((z_stream_TVALID_int_regslice == 1'b0) & (icmp_ln30_fu_167_p2 == 1'd0)) | ((y_s_stream_TVALID_int_regslice == 1'b0) & (icmp_ln30_fu_167_p2 == 1'd0)) | ((y_stream_TVALID_int_regslice == 1'b0) & (icmp_ln30_fu_167_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_frp_pvb_pf_start = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ct_2_fu_161_p2 = (ap_sig_allocacmp_ct_1 + 10'd1);

assign icmp_ln30_fu_167_p2 = ((ap_sig_allocacmp_ct_1 == 10'd640) ? 1'b1 : 1'b0);

assign lhs_V_fu_247_p1 = y_s_stream_TDATA_int_regslice[3:0];

assign o_stream_TDATA = pf_o_stream_U_data_out;

assign o_stream_TDATA_blk_n = 1'b1;

assign pf_o_stream_U_frpsig_data_in = $signed(tmp_9_fu_667_p14);

assign r_V_1_fu_507_p2 = sext_ln42_2_fu_447_p1 << sh_prom_i_i_i_fu_468_p1;

assign r_V_2_fu_501_p2 = sext_ln42_3_fu_450_p1 << sh_prom_i_i_i_fu_468_p1;

assign r_V_3_fu_495_p2 = sext_ln42_4_fu_453_p1 << sh_prom_i_i_i_fu_468_p1;

assign r_V_4_fu_489_p2 = sext_ln42_5_fu_456_p1 << sh_prom_i_i_i_fu_468_p1;

assign r_V_5_fu_483_p2 = sext_ln42_6_fu_459_p1 << sh_prom_i_i_i_fu_468_p1;

assign r_V_6_fu_477_p2 = sext_ln42_7_fu_462_p1 << sh_prom_i_i_i_fu_468_p1;

assign r_V_7_fu_471_p2 = sext_ln42_8_fu_465_p1 << sh_prom_i_i_i_fu_468_p1;

assign r_V_fu_513_p2 = sext_ln42_fu_444_p1 << sh_prom_i_i_i_fu_468_p1;

assign regslice_both_o_stream_U_apdone_blk = 1'b0;

assign ret_V_fu_337_p2 = (zext_ln186_1_fu_333_p1 + zext_ln186_fu_251_p1);

assign rhs_V_fu_329_p1 = z_s_stream_TDATA_int_regslice[3:0];

assign sext_ln42_1_fu_529_p1 = $signed(trunc_ln2_fu_519_p4);

assign sext_ln42_2_fu_447_p1 = ret_V_2_reg_883;

assign sext_ln42_3_fu_450_p1 = ret_V_3_reg_888;

assign sext_ln42_4_fu_453_p1 = ret_V_4_reg_893;

assign sext_ln42_5_fu_456_p1 = ret_V_5_reg_898;

assign sext_ln42_6_fu_459_p1 = ret_V_6_reg_903;

assign sext_ln42_7_fu_462_p1 = ret_V_7_reg_908;

assign sext_ln42_8_fu_465_p1 = ret_V_8_reg_913;

assign sext_ln42_9_fu_543_p1 = $signed(trunc_ln1669_6_fu_533_p4);

assign sext_ln42_fu_444_p1 = ret_V_1_reg_878;

assign sext_ln44_1_fu_621_p1 = $signed(tmp_5_fu_611_p4);

assign sext_ln44_2_fu_635_p1 = $signed(tmp_6_fu_625_p4);

assign sext_ln44_3_fu_649_p1 = $signed(tmp_7_fu_639_p4);

assign sext_ln44_4_fu_663_p1 = $signed(tmp_8_fu_653_p4);

assign sext_ln44_fu_607_p1 = $signed(tmp_s_fu_597_p4);

assign sh_prom_i_i_i_fu_468_p1 = ret_V_reg_793_pp0_iter2_reg;

assign tmp_1_fu_565_p3 = r_V_2_fu_501_p2[32'd10];

assign tmp_2_fu_573_p3 = r_V_3_fu_495_p2[32'd10];

assign tmp_3_fu_581_p3 = r_V_4_fu_489_p2[32'd10];

assign tmp_4_fu_589_p3 = r_V_5_fu_483_p2[32'd10];

assign tmp_5_fu_611_p4 = {{r_V_2_fu_501_p2[33:11]}};

assign tmp_6_fu_625_p4 = {{r_V_3_fu_495_p2[33:11]}};

assign tmp_7_fu_639_p4 = {{r_V_4_fu_489_p2[33:11]}};

assign tmp_8_fu_653_p4 = {{r_V_5_fu_483_p2[33:11]}};

assign tmp_9_fu_667_p14 = {{{{{{{{{{{{{trunc_ln1669_7_fu_547_p4}, {sext_ln42_9_fu_543_p1}}, {sext_ln44_4_fu_663_p1}}, {tmp_4_fu_589_p3}}, {sext_ln44_3_fu_649_p1}}, {tmp_3_fu_581_p3}}, {sext_ln44_2_fu_635_p1}}, {tmp_2_fu_573_p3}}, {sext_ln44_1_fu_621_p1}}, {tmp_1_fu_565_p3}}, {sext_ln44_fu_607_p1}}, {tmp_fu_557_p3}}, {sext_ln42_1_fu_529_p1}};

assign tmp_fu_557_p3 = r_V_1_fu_507_p2[32'd10];

assign tmp_s_fu_597_p4 = {{r_V_1_fu_507_p2[33:11]}};

assign trunc_ln1669_6_fu_533_p4 = {{r_V_6_fu_477_p2[33:10]}};

assign trunc_ln1669_7_fu_547_p4 = {{r_V_7_fu_471_p2[33:10]}};

assign trunc_ln2_fu_519_p4 = {{r_V_fu_513_p2[33:10]}};

assign trunc_ln32_fu_173_p1 = y_stream_TDATA_int_regslice[7:0];

assign trunc_ln34_fu_255_p1 = z_stream_TDATA_int_regslice[7:0];

assign y_s_stream_TDATA_blk_n = 1'b1;

assign y_s_stream_TREADY = regslice_both_y_s_stream_U_ack_in;

assign y_stream_TDATA_blk_n = 1'b1;

assign y_stream_TREADY = regslice_both_y_stream_U_ack_in;

assign z_s_stream_TDATA_blk_n = 1'b1;

assign z_s_stream_TREADY = regslice_both_z_s_stream_U_ack_in;

assign z_stream_TDATA_blk_n = 1'b1;

assign z_stream_TREADY = regslice_both_z_stream_U_ack_in;

assign zext_ln186_1_fu_333_p1 = rhs_V_fu_329_p1;

assign zext_ln186_fu_251_p1 = lhs_V_fu_247_p1;

endmodule //YZ_do_yz_Loop_VITIS_LOOP_30_1_proc1
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

module YZ_flow_control_loop_pipe(
        ap_clk,
        ap_rst,
        ap_start,
        ap_ready,
        ap_done,
        ap_continue,
        ap_start_int,
        ap_ready_int,
        ap_done_int,
        ap_continue_int,
        ap_loop_init,
        ap_loop_exit_ready,
        ap_loop_exit_done
);

input   ap_clk;
input   ap_rst;

//Block level handshake with outside loop
input   ap_start;
output  ap_ready;
output  ap_done;
input   ap_continue;

//Block level handshake with loop body
output  ap_start_int;
input   ap_ready_int;
input   ap_done_int;
output  ap_continue_int;

//Init live in variables
output   ap_loop_init;
reg ap_loop_init;

//Exit signal from loop body
input   ap_loop_exit_ready;
input   ap_loop_exit_done;

// power-on initialization
initial begin
//#0 ap_loop_init = 1'b1;
end

assign ap_start_int = ap_start;

assign ap_continue_int = ap_continue;

assign ap_done = ap_loop_exit_done;

assign ap_ready = ap_loop_exit_ready;

//ap_loop_init is valid for the first II
//of the first loop run so as to enable
//the init block ops which are pushed into
//the first state of the pipeline region
always @ (posedge ap_clk)
begin
    if (ap_rst == 1'b1) begin
        ap_loop_init <= 1'b1;
    end else if(ap_loop_exit_ready == 1'b1) begin
        ap_loop_init <= 1'b1;
    end else if(ap_ready_int == 1'b1) begin
        ap_loop_init <= 1'b0;
    end
end

endmodule
        
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

(* keep_hierarchy = "yes" *)
module YZ_frp_fifoout
  (
   ap_clk,
   ap_rst,
   data_in,
   data_in_vld,
   data_in_last,

   data_out,
   data_out_vld,

   ap_start,
   data_out_read,

   valid,
   num_valid_datasets,
   pf_ready,
   pf_done,
   empty,
   pf_all_done,
   pf_continue
);
   parameter BlockingType = 1;  // 'frp_fifoout' type parameter: '1' for blocking port(AXIS/FIFO/AP_HS)
                                //                               '0' for non-blocking port(Memory/AP_VLD...)
   parameter PipeLatency = 4;
   parameter PipelineII  = 1;
   parameter DataWidth   = 32;
   parameter NumWrites   = 1;
   parameter CeilLog2Stages  = 2;
   parameter CeilLog2FDepth  = 2;
   parameter PfAllDoneEnable = 2;
   
   localparam NUM_STAGES = (PipeLatency+PipelineII-1) / PipelineII; // Ceil(Latency/II)
   
   function isDefined;
      input val;
      begin
         isDefined = (val === 1'b0 || val === 1'b1);
      end
   endfunction

   input ap_clk;
   input ap_rst;
   input [DataWidth-1:0] data_in;
   input ap_start;
   input [PipeLatency-1:0] valid;
   input               data_in_vld, data_in_last;
   input [CeilLog2Stages:0] num_valid_datasets;
   input data_out_read;
   input pf_all_done;
   input pf_continue;

   output reg [DataWidth-1:0] data_out;
   output reg data_out_vld;
   output reg pf_ready;
   output reg pf_done;
   output  empty;

   assign empty=1'b0; // output port empty is not used


   ///////// custom fifo implementation /////////
   localparam FDEPTH = NUM_STAGES * NumWrites + 1;
   reg [DataWidth-1+2:0] fifo [0:FDEPTH-1]; // the "+2" is for extrabits for {data_in_last,data_in_vld}
   reg write_enable, read_enable;
   reg fifo_empty, fifo_full, sel_pipe;
   reg signed [CeilLog2FDepth:0] fifo_rdPtr; // range is -1 to FDEPTH-1
   reg [CeilLog2FDepth:0] fifo_avail;
   reg signed [CeilLog2FDepth+1:0] ready_chk; // max -ve value is (0 - fifo_avail)
   reg                  fail;
   reg     data_out_vld_fifo;

   integer WarningSuppressThreshold;
   initial begin // for co-sim assertion
       fifo_rdPtr = -1;
       fifo_empty = 1'b1;
       fifo_full = 1'b0;
       fail = 0;
//       if(!$value$plusargs("warning_suppress_threshold=%0d", WarningSuppressThreshold)) 
$display("This is YZ.\n");
           WarningSuppressThreshold = 5;
   end

   integer i;
   always @ (posedge ap_clk) begin : fifo_gen
      if (write_enable) begin
         for (i = 0; i < FDEPTH-1; i = i+1)
           fifo[i+1] <= fifo[i];
         fifo[0] <= {data_in_last, data_in_vld, data_in};
      end
   end
   // read ptr should have a positive address (MSB can be ignored)
   wire [DataWidth-1+2:0] fifo_out; // the "+2" is for extrabits for {data_in_last,data_in_vld}
   assign fifo_out = fifo[ fifo_rdPtr[CeilLog2FDepth-1:0] ];

   integer j;
   integer cnt_write_ovfl = 0;
   integer cnt_read_ovfl = 0;
   always @ (posedge ap_clk) begin : fifo_ptr
      if (ap_rst) begin
        fifo_rdPtr <= -1;
        fifo_empty <= 1'b1;
        fifo_full <= 1'b0;
      end
      else begin
          //// // synthesis translate_off
          //// if ($time > 0) begin
          ////    if ( write_enable && fifo_full && cnt_write_ovfl < WarningSuppressThreshold ) begin
          ////        $display("WARNING : fifo write overflow at time %0t", $time); fail=1;
          ////        cnt_write_ovfl = cnt_write_ovfl + 1;
          ////    end
          //// end
          //// // synthesis translate_on
         if (write_enable && !read_enable && !fifo_full) begin
           fifo_rdPtr <= fifo_rdPtr + 1;
           fifo_empty <= 1'b0;
           fifo_full <= (fifo_rdPtr == FDEPTH-2);
         end
         else if (read_enable && !write_enable && !fifo_empty) begin
           fifo_rdPtr <= fifo_rdPtr - 1;
           fifo_empty <= (fifo_rdPtr == 'd0);
           fifo_full <= 1'b0;
         end
      end
   end
   
   ///////// control logic /////////

   reg stalled, must_stall, data_cannot_vld, data_done, data_out_last_reg;
   reg data_out_last, internal_done;
   
    generate
        if(PfAllDoneEnable==2)
            always @(*) begin
                stalled = must_stall;
            end
        else
            always @ (posedge ap_clk) begin : stall_reg
                if (ap_rst) stalled <= 1'b0;
                else stalled <= must_stall;
            end
    endgenerate
   
    generate
        if (BlockingType == 1)
            always @ (*) begin : readen_control_for_blocking
                casex ({data_out_read, data_out_vld_fifo, data_out_last, fifo_empty, stalled})
                  5'b 1_X_X_0_0 : // when consumer reads and fifo is not empty.
                    read_enable = 1'b1;
                  5'b X_0_1_0_0 : // when no data in last and fifo is not empty.
                    read_enable = 1'b1;
                  default:
                    read_enable = 1'b0;
                endcase
            end
        else
            always @ (*) begin : readen_control_for_non_blocking
                casex ({fifo_empty, must_stall})
                  2'b 0_0: 
                    read_enable = 1'b1;
                  default:
                    read_enable = 1'b0;
                endcase
            end
    endgenerate

    generate
        if (BlockingType == 1)
            always @ (*) begin : writen_control_for_blocking
                casex ({ data_out_read, data_in_vld, fifo_empty, data_in_last, stalled })
                    5'b X_X_X_1_1 :
                        write_enable = 1'b1;
                    5'b X_1_X_X_1 :
                        write_enable = 1'b1;

                    5'b X_X_0_1_0 : // last valid, fifo has data
                        write_enable = 1'b1;
                    5'b 0_1_1_1_0 : // last valid, but consumer stalls (data_out_read==0), data_in_valid available
                        write_enable = 1'b1;
                    
                    5'b 0_1_X_X_0 : // data valid, but consumer stalls (data_out_read==0)
                        write_enable = 1'b1;
                    5'b 1_1_1_X_0 : // data valid, consumer ready, fifo is fifo_empty
                        write_enable = 1'b0;
                    5'b 1_1_0_X_0 : // data valid, consumer ready, fifo has data
                        write_enable = 1'b1;
                    default     :
                      write_enable = 1'b0;
                endcase
            end
        else if(BlockingType==0 && PfAllDoneEnable == 2)
            always @ (*) begin : writen_control_for_non_blocking
                casex ({ data_in_vld, fifo_empty, data_in_last, must_stall })
                  4'b 1_0_X_X :
                      write_enable = 1'b1;
                  4'b X_0_1_X :
                      write_enable = 1'b1;
                  4'b X_1_1_1 :
                      write_enable = 1'b1;
                  4'b 1_1_X_1 :
                      write_enable = 1'b1;
                  default     :
                      write_enable = 1'b0;
                endcase
            end
        else
            always @ (*) begin : writen_control_for_non_blocking
                casex ({ data_in_vld, fifo_empty, data_in_last, must_stall })
                  4'b 1_0_X_X :
                      write_enable = 1'b1;
                  4'b X_0_1_X :
                      write_enable = 1'b1;
                  4'b X_1_1_1 :
                      write_enable = 1'b1;
                  default     :
                      write_enable = 1'b0;
                endcase
            end
    endgenerate

    generate
        if (PfAllDoneEnable == 2)
            always @(posedge ap_clk) begin
                if(ap_rst) begin
                    data_cannot_vld<=1'b0;
                    data_out_last_reg<=1'b0;
                end else if(pf_all_done&&pf_continue) begin 
                    if(data_out_vld_fifo&&data_out_read&&data_out_last) data_cannot_vld<=1'b1 & (BlockingType==1);
                    else if(!data_out_vld_fifo&&data_out_last) data_cannot_vld<=1'b1;
                    else data_cannot_vld<=1'b0;

                    if(data_out_vld_fifo&&data_out_read&&data_out_last) data_out_last_reg<=data_out_last&(BlockingType==1);
                    else if(!data_out_vld_fifo&&data_out_last) data_out_last_reg<=data_out_last;
                    else data_out_last_reg<=1'b0;
                end else if(pf_all_done&&!pf_continue) begin 
                    data_cannot_vld<=1'b1;
                    data_out_last_reg<=data_out_last_reg;
                end else if(!pf_all_done) begin
                    if(data_out_last_reg) begin
                        data_cannot_vld<=1'b1;
                        data_out_last_reg<=data_out_last_reg;
                    end else if(data_out_vld_fifo&&!data_out_read) begin
                        data_cannot_vld<=1'b0;
                        data_out_last_reg<=1'b0;
                    end else if(data_out_vld_fifo&&data_out_read||!data_out_vld_fifo)begin
                        if(!data_out_last) data_cannot_vld<=1'b0;
                        else data_cannot_vld<=1'b1;
                        if(data_out_last) data_out_last_reg<=data_out_last;
                        else data_out_last_reg<=1'b0;
                    end
                end

                if(ap_rst) data_done<=1'b0;
                else if(must_stall) data_done <= data_done;
                else if ( (data_out_vld&&data_out_read||!data_out_vld_fifo&&data_out_last)||
                          (!pf_all_done||pf_all_done&&pf_continue) ) data_done <= 1'b1 & (BlockingType==1);
                else data_done <= 1'b0;
            end
    endgenerate

    generate
        if (PfAllDoneEnable == 2)
            always @ (*) begin : control
                ///////// internal signals /////////
                // data_out_vld is AMBA compliant (independent of data_out_read)
                sel_pipe    = fifo_empty;
                {data_out_last, data_out_vld_fifo, data_out} = sel_pipe ? {data_in_last, data_in_vld, data_in} : fifo_out;
                //for blocking mode, next transaction first data is already in YZ fifo. They can do handshake when
                //last transaction ap_done/ap_continue does handshake
                //for non_blocking mode, next transaction first data is not in YZ fifo
                data_out_vld = data_out_vld_fifo & (!data_cannot_vld || pf_continue&&pf_all_done&&data_done);

                if(pf_continue&&pf_all_done) begin
                    if(data_out_vld_fifo&&!data_out_read) must_stall=1'b1;
                    else if(data_out_vld_fifo&&data_out_read) must_stall=1'b1 & (BlockingType==0);
                    else must_stall=1'b0;

                    if(data_out_vld_fifo&&data_out_read) pf_done=data_out_last & (BlockingType==1);
                    else if(!data_out_vld_fifo&&data_out_last) pf_done=data_out_last;
                    else pf_done=1'b0;
                end else if(pf_all_done && !pf_continue) begin 
                    must_stall=1;
                    pf_done=data_out_last_reg;
                end else if(!pf_all_done) begin
                    if(data_out_last_reg) begin
                         must_stall=1'b1;
                         pf_done=data_out_last_reg;
                    end else if(data_out_vld_fifo&&!data_out_read) begin
                        must_stall=1'b1;
                        pf_done=1'b0;
                    end else if(data_out_vld_fifo&&data_out_read||!data_out_vld_fifo)begin
                        must_stall = 1'b0;
                        if(data_out_last) pf_done=data_out_last;
                        else pf_done=1'b0;
                    end else begin
                        must_stall = 1'b0;
                        pf_done = 1'b0;
                    end
                end else begin
                    must_stall = 1'b0;
                    pf_done = 1'b0;
                end

                ///////// outputs /////////
                fifo_avail = (FDEPTH - fifo_rdPtr - 1);
                // available has to be atleast one (or NumWrites) more than
                // valid transactions being processed in the pipeline. Then this
                // fifo buffer can accept the "valid" data in the following cycle.
                // pf_ready = (fifo_avail - (num_valid_datasets * NumWrites) >=
                // NumWrites);
                // above expr simplified for hardware
                                ready_chk = (NumWrites - fifo_avail + (num_valid_datasets * NumWrites));
                  pf_ready = ready_chk < 0;
            end // block: control
        else if (PfAllDoneEnable == 1)
            always @ (*) begin : control
               ///////// internal signals /////////
               // data_out_vld is AMBA compliant (independent of data_out_read)
               sel_pipe    = fifo_empty;
               {data_out_last, data_out_vld_fifo, data_out} = sel_pipe ? {data_in_last, data_in_vld, data_in} : fifo_out;
               data_out_vld = data_out_vld_fifo & !stalled;

               casex ({data_out_vld_fifo, data_out_last, pf_continue&pf_all_done, stalled, data_out_read})
                 5'b 0_0_X_0_X : {internal_done, must_stall} = 2'b 0_0;
                 5'b X_X_0_1_X : {internal_done, must_stall} = 2'b 1_1;  // when 'stalled', should wait until 'pf_continue'.
                 5'b X_X_1_1_X : {internal_done, must_stall} = 2'b 1_0;  // when 'pf_continue' arrived, 'stalled' register is de-asserted first.
                                                                         // This is to avoid the combinational loop on 'pf_done'.
                                                                         // loop: pf_done->ap_done->done_sync->ap_continue->pf_continue->pf_done.
                 5'b 0_1_0_0_X : {internal_done, must_stall} = 2'b 1_1;  // When there is only 'data_out_last', no need to wait 'data_out_read'.
                 5'b 0_1_1_0_X : {internal_done, must_stall} = 2'b 1_0;

                 5'b 1_1_X_X_0 : {internal_done, must_stall} = 2'b 0_0;  // when there are 'data_out_vld' and 'data_out_last' in the same cycle, 'internal_done' has to handshake with 'data_out_read'.
                 5'b 1_1_1_0_1 : {internal_done, must_stall} = 2'b 1_0;
                 5'b 1_1_0_0_1 : {internal_done, must_stall} = 2'b 1_1;
                 default       : {internal_done, must_stall} = 2'b 0_0;
               endcase
               pf_done = internal_done&!(pf_continue&pf_all_done);

               ///////// outputs /////////
               fifo_avail = (FDEPTH - fifo_rdPtr - 1);
               // available has to be atleast one (or NumWrites) more than
               // valid transactions being processed in the pipeline. Then this
               // fifo buffer can accept the "valid" data in the following cycle.
               // pf_ready = (fifo_avail - (num_valid_datasets * NumWrites) >=
               // NumWrites);
               // above expr simplified for hardware

                               ready_chk = (NumWrites - fifo_avail + (num_valid_datasets * NumWrites));
                 pf_ready = ready_chk < 0;
            end // block: control
        else
            always @ (*) begin : control
     
                 ///////// internal signals /////////
     
                 // data_out_vld is AMBA compliant (independent of data_out_read)
                 sel_pipe    = fifo_empty;
                 {data_out_last, data_out_vld_fifo, data_out} = sel_pipe ? {data_in_last, data_in_vld, data_in} : fifo_out;
                 data_out_vld = data_out_vld_fifo & !stalled;
     
                 casex ({data_out_vld_fifo, data_out_last, pf_continue, stalled, data_out_read})
                   5'b 0_0_X_0_X : {internal_done, must_stall} = 2'b 0_0;
                   5'b X_X_0_1_X : {internal_done, must_stall} = 2'b 1_1;  // when 'stalled', should wait until 'pf_continue'.
                   5'b X_X_1_1_X : {internal_done, must_stall} = 2'b 1_0;  // when 'pf_continue' arrived, 'stalled' register is de-asserted first.
                                                                           // This is to avoid the combinational loop on 'pf_done'.
                                                                           // loop: pf_done->ap_done->done_sync->ap_continue->pf_continue->pf_done.
                   5'b 0_1_0_0_X : {internal_done, must_stall} = 2'b 1_1;  // When there is only 'data_out_last', no need to wait 'data_out_read'.
                   5'b 0_1_1_0_X : {internal_done, must_stall} = 2'b 1_0;

                   5'b 1_1_X_X_0 : {internal_done, must_stall} = 2'b 0_0;  // when there are 'data_out_vld' and 'data_out_last' in the same cycle, 'internal_done' has to handshake with 'data_out_read'.
                   5'b 1_1_1_0_1 : {internal_done, must_stall} = 2'b 1_0;
                   5'b 1_1_0_0_1 : {internal_done, must_stall} = 2'b 1_1;
                   default       : {internal_done, must_stall} = 2'b 0_0;
                 endcase
                 pf_done = internal_done;

                 ///////// outputs /////////
                 fifo_avail = (FDEPTH - fifo_rdPtr - 1);
                 // available has to be atleast one (or NumWrites) more than
                 // valid transactions being processed in the pipeline. Then this
                 // fifo buffer can accept the "valid" data in the following cycle.
                 // pf_ready = (fifo_avail - (num_valid_datasets * NumWrites) >=
                 // NumWrites);
                 // above expr simplified for hardware

                             ready_chk = (NumWrites - fifo_avail + (num_valid_datasets * NumWrites));
                     pf_ready = ready_chk < 0;
            end // block: control
       endgenerate
endmodule // pipeline_fifo
    
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

(* keep_hierarchy = "yes" *)
module YZ_frp_pipeline_valid
  (ap_clk,
   ap_rst,
   valid_in,
   exitcond,

   valid_out,
   num_valid_datasets);

   parameter PipelineLatency =  4;
   parameter PipelineII      =  1;
   parameter ExitLatency = -1;
   parameter CeilLog2Stages   = 2;
   
   localparam NUM_STAGES = (PipelineLatency+PipelineII-1) / PipelineII; // Ceil(Latency/II)
   
   function isDefined;
      input val;
      begin
         isDefined = (val === 1'b0 || val === 1'b1);
      end
   endfunction

   input ap_clk;
   input ap_rst;
   input valid_in;
   input exitcond;
   
   
   output [PipelineLatency-1:0] valid_out;
   output [CeilLog2Stages:0] num_valid_datasets;
   reg signed [CeilLog2Stages+1:0] nvd_reg;
   assign num_valid_datasets=nvd_reg;

   reg fail;
   reg [PipelineLatency-2:0] v2;

   integer WarningSuppressThreshold;
   initial begin // for co-sim assertion
       v2 = 0;
       fail = 0;
       nvd_reg = 0;
//       if(!$value$plusargs("warning_suppress_threshold=%0d", WarningSuppressThreshold)) 
$display("This is YZ.\n");
           WarningSuppressThreshold = 5;
   end

   reg [PipelineLatency-1:0] valid_out_tmp;

   assign valid_out=valid_out_tmp;
   ///////// pipeline data valid (flushable impl) /////////
   reg [PipelineLatency-2:0] v1;
   genvar i;
   generate for (i = 0; i < PipelineLatency-1; i = i+1)
     always @ (posedge ap_clk) begin
        if (ap_rst)
          v2[i] <= 0;
        else begin
           v1[i] = (i == 0) ? valid_in : v2[i-1];
           v2[i] <= (ExitLatency==i) ? (!exitcond & v1[i]) : v1[i];
        end
     end
   endgenerate

   integer j;
   ///// // synthesis translate_off
   ///// integer cnt_nvd_ovfl_warning[PipelineLatency-1:0];
   ///// // synthesis translate_on
   always @(*) begin

       valid_out_tmp = {v2, valid_in};

       //// // synthesis translate_off
       //// if ($time > 0) begin
       ////    for (j = 1; j < PipelineLatency; j = j+1) begin : loop_block
       ////       if ( !(!valid_out_tmp[j] || nvd_reg <= NUM_STAGES) && 
       ////            cnt_nvd_ovfl_warning[j] < WarningSuppressThreshold ) begin
       ////          $display("WARNING : nvd_reg overflow. valid_out_tmp[%0d]=%b nvd=%0d nstg=%0d (at time %0t)",
       ////                 j, valid_out_tmp[j], nvd_reg, NUM_STAGES, $time);
       ////          fail=1; 
       ////          cnt_nvd_ovfl_warning[j] = cnt_nvd_ovfl_warning[j] + 1;
       ////          disable loop_block;
       ////       end
       ////    end // for (j = 1; j < PipelineLatency; j = j+1)
       //// end // if ($time > 0)
       //// // synthesis translate_on
   end

   wire   valid_disable;
   assign valid_disable = (ExitLatency == -1) ? 1'b0 : (valid_out_tmp[ExitLatency] & exitcond);
   
   // Count the num valid_out_tmp datasets in the pipe stages other than the
   // first. We do NOT count valid_out_tmp[0], otherwise it will be a
   // combination loop: nvd -> pfifo.ap_ready -> valid_in -> valid_out_tmp[0] -> nvd
   reg signed [2:0] incr;
   integer cnt_nvd_out_range = 0;
   always @ (posedge ap_clk) begin
      if (ap_rst)
         nvd_reg <= 0;
      else begin
         casex ({valid_out_tmp[0], valid_out_tmp[PipelineLatency-1], valid_disable})
           3'b100:  incr =  1;
           3'b111:  incr = -1;
           3'b001:  incr = -1;
           3'b010:  incr = -1;
           3'b011:  incr = -2;
           default: incr =  0;
         endcase
         /// // synthesis translate_off
         /// if (!(0 <=($signed(nvd_reg)+incr)<=NUM_STAGES) && cnt_nvd_out_range<WarningSuppressThreshold) begin
         ///       $display("WARNING: nvd_reg out of range. incr=%d nvd=%0d nstg=%0d (at time %0t)",
         ///              incr, nvd_reg, NUM_STAGES, $time);
         ///    fail=1;
         ///    cnt_nvd_out_range = cnt_nvd_out_range+1;
         /// end
         /// // synthesis translate_on
         nvd_reg <= nvd_reg + incr;
      end
   end

   //// // synthesis translate_off
   //// integer cnt_valid_out_tmp[PipelineLatency-1:0];
   //// integer stg, stgc;
   //// always @ (posedge ap_clk) begin
   ////    stg = 0;
   ////    stgc = 0;
   ////    for (j = 0; j < PipelineLatency; j = j+1) begin : block_stgc
   ////       stgc = stgc + valid_out_tmp[j];
   ////       if (stg == PipelineII-1) begin
   ////          if ( !(stgc <= 1) && cnt_valid_out_tmp[j]<WarningSuppressThreshold) begin
   ////             $display("WARNING: valid_out_tmp=%b. %0d bits set in one pipe-stage ending at bit-%0d (at time %0t)",
   ////                    valid_out_tmp, stgc, j, $time);
   ////             fail=1; 
   ////             cnt_valid_out_tmp[j] = cnt_valid_out_tmp[j] + 1;
   ////             disable block_stgc;
   ////          end
   ////          stgc = 0;
   ////          stg  = 0;
   ////       end else begin
   ////          stg = stg + 1;
   ////       end
   ////    end // for (j = 0; j < PipelineLatency; j = j+1)
   //// end // always @ (posedge ap_clk)
   //// // synthesis translate_on

endmodule // pipeline_valid
    
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

(* use_dsp = "yes" *) module YZ_mul_8s_8s_16_2_1(clk, ce, reset, din0, din1, dout);
parameter ID = 1;
parameter NUM_STAGE = 1;
parameter din0_WIDTH = 14;
parameter din1_WIDTH = 12;
parameter dout_WIDTH = 26;
input clk;
input ce;
input reset;
input signed [din0_WIDTH - 1 : 0] din0;
input signed [din1_WIDTH - 1 : 0] din1;
output[dout_WIDTH - 1 : 0] dout;
reg signed [dout_WIDTH - 1 : 0] dout;
wire signed [dout_WIDTH - 1 : 0] tmp_product;

assign tmp_product = $signed(din0) * $signed(din1);
always @ (posedge clk) begin
    if (ce) begin
        dout <= tmp_product;
    end
end
endmodule
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1ns/1ps

module YZ_regslice_both
#(parameter 
    DataWidth=32
)(
    input ap_clk ,
    input ap_rst,

    input [DataWidth-1:0] data_in , 
    input vld_in , 
    output ack_in ,
    output [DataWidth-1:0] data_out, 
    output vld_out,
    input ack_out,
    output apdone_blk
);
 

reg   [1:0] B_V_data_1_state;
wire   [DataWidth-1:0] B_V_data_1_data_in;
reg   [DataWidth-1:0] B_V_data_1_data_out;
wire    B_V_data_1_vld_reg;
wire    B_V_data_1_vld_in;
wire    B_V_data_1_vld_out;
reg   [DataWidth-1:0] B_V_data_1_payload_A;
reg   [DataWidth-1:0] B_V_data_1_payload_B;
reg    B_V_data_1_sel_rd;
reg    B_V_data_1_sel_wr;
wire    B_V_data_1_sel;
wire    B_V_data_1_load_A;
wire    B_V_data_1_load_B;
wire    B_V_data_1_state_cmp_full;
wire    B_V_data_1_ack_in;
wire    B_V_data_1_ack_out;

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_out) & (1'b1 == B_V_data_1_ack_out))) begin
            B_V_data_1_sel_rd <= ~B_V_data_1_sel_rd;
        end else begin
            B_V_data_1_sel_rd <= B_V_data_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_in))) begin
            B_V_data_1_sel_wr <= ~B_V_data_1_sel_wr;
        end else begin
            B_V_data_1_sel_wr <= B_V_data_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_state <= 2'd0;
    end else begin
        if ((((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) | ((2'd2 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd2;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out)) | ((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd1;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b1 == B_V_data_1_ack_out)) | (~((1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)) & ~((1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) & (2'd3 == B_V_data_1_state)) | ((2'd2 == B_V_data_1_state) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd3;
        end else begin
            B_V_data_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_A)) begin
        B_V_data_1_payload_A <= B_V_data_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_B)) begin
        B_V_data_1_payload_B <= B_V_data_1_data_in;
    end
end

always @ (*) begin
    if ((1'b1 == B_V_data_1_sel)) begin
        B_V_data_1_data_out = B_V_data_1_payload_B;
    end else begin
        B_V_data_1_data_out = B_V_data_1_payload_A;
    end
end

assign B_V_data_1_ack_in = B_V_data_1_state[1'd1];
assign B_V_data_1_load_A = (~B_V_data_1_sel_wr & B_V_data_1_state_cmp_full);
assign B_V_data_1_load_B = (B_V_data_1_state_cmp_full & B_V_data_1_sel_wr);
assign B_V_data_1_sel = B_V_data_1_sel_rd;
assign B_V_data_1_state_cmp_full = ((B_V_data_1_state != 2'd1) ? 1'b1 : 1'b0);
assign B_V_data_1_vld_out = B_V_data_1_state[1'd0];

assign ack_in = B_V_data_1_ack_in;
assign B_V_data_1_data_in = data_in;
assign B_V_data_1_vld_in = vld_in;

assign vld_out = B_V_data_1_vld_out;
assign data_out = B_V_data_1_data_out;
assign B_V_data_1_ack_out = ack_out;

assign apdone_blk = ((B_V_data_1_state == 2'd3 && ack_out == 1'b0) | (B_V_data_1_state == 2'd1));

endmodule // both

module YZ_regslice_both_w1
#(parameter 
    DataWidth=1
)(
    input ap_clk ,
    input ap_rst,

    input data_in , 
    input vld_in , 
    output ack_in ,
    output data_out, 
    output vld_out,
    input ack_out,
    output apdone_blk
);

reg     [1:0] B_V_data_1_state;
wire    B_V_data_1_data_in;
reg     B_V_data_1_data_out;
wire    B_V_data_1_vld_reg;
wire    B_V_data_1_vld_in;
wire    B_V_data_1_vld_out;
reg     B_V_data_1_payload_A;
reg     B_V_data_1_payload_B;
reg     B_V_data_1_sel_rd;
reg     B_V_data_1_sel_wr;
wire    B_V_data_1_sel;
wire    B_V_data_1_load_A;
wire    B_V_data_1_load_B;
wire    B_V_data_1_state_cmp_full;
wire    B_V_data_1_ack_in;
wire    B_V_data_1_ack_out;

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_out) & (1'b1 == B_V_data_1_ack_out))) begin
            B_V_data_1_sel_rd <= ~B_V_data_1_sel_rd;
        end else begin
            B_V_data_1_sel_rd <= B_V_data_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_in))) begin
            B_V_data_1_sel_wr <= ~B_V_data_1_sel_wr;
        end else begin
            B_V_data_1_sel_wr <= B_V_data_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_state <= 2'd0;
    end else begin
        if ((((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) | ((2'd2 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd2;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out)) | ((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd1;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b1 == B_V_data_1_ack_out)) | (~((1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)) & ~((1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) & (2'd3 == B_V_data_1_state)) | ((2'd2 == B_V_data_1_state) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd3;
        end else begin
            B_V_data_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_A)) begin
        B_V_data_1_payload_A <= B_V_data_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_B)) begin
        B_V_data_1_payload_B <= B_V_data_1_data_in;
    end
end

always @ (*) begin
    if ((1'b1 == B_V_data_1_sel)) begin
        B_V_data_1_data_out = B_V_data_1_payload_B;
    end else begin
        B_V_data_1_data_out = B_V_data_1_payload_A;
    end
end

assign B_V_data_1_ack_in = B_V_data_1_state[1'd1];
assign B_V_data_1_load_A = (~B_V_data_1_sel_wr & B_V_data_1_state_cmp_full);
assign B_V_data_1_load_B = (B_V_data_1_state_cmp_full & B_V_data_1_sel_wr);
assign B_V_data_1_sel = B_V_data_1_sel_rd;
assign B_V_data_1_state_cmp_full = ((B_V_data_1_state != 2'd1) ? 1'b1 : 1'b0);
assign B_V_data_1_vld_out = B_V_data_1_state[1'd0];

assign ack_in = B_V_data_1_ack_in;
assign B_V_data_1_data_in = data_in;
assign B_V_data_1_vld_in = vld_in;

assign vld_out = B_V_data_1_vld_out;
assign data_out = B_V_data_1_data_out;
assign B_V_data_1_ack_out = ack_out;

assign apdone_blk = ((B_V_data_1_state == 2'd3 && ack_out == 1'b0) | (B_V_data_1_state == 2'd1));

endmodule // both


