/* verilator lint_off PINMISSING */
/* verilator lint_off CASEINCOMPLETE */
/* verilator lint_off COMBDLY */
/* verilator lint_off CASEX */
/* verilator lint_off CASEOVERLAP */
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="B_BUFFER_B_BUFFER,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvc1902-vsva2197-2MP-e-S,HLS_INPUT_CLOCK=2.500000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=1.936000,HLS_SYN_LAT=186,HLS_SYN_TPT=187,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=136,HLS_SYN_LUT=274,HLS_VERSION=2022_2}" *)

module B_BUFFER (
        i_stream_TDATA,
        i_s_stream_TDATA,
        q_stream_TDATA,
        s_stream_TDATA,
        ap_clk,
        ap_rst_n,
        i_stream_TVALID,
        i_stream_TREADY,
        q_stream_TVALID,
        q_stream_TREADY,
        ap_start,
        ap_done,
        i_s_stream_TVALID,
        i_s_stream_TREADY,
        s_stream_TVALID,
        s_stream_TREADY,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [63:0] i_stream_TDATA;
input  [7:0] i_s_stream_TDATA;
output  [63:0] q_stream_TDATA;
output  [7:0] s_stream_TDATA;
input   ap_clk;
input   ap_rst_n;
input   i_stream_TVALID;
output   i_stream_TREADY;
output   q_stream_TVALID;
input   q_stream_TREADY;
input   ap_start;
output   ap_done;
input   i_s_stream_TVALID;
output   i_s_stream_TREADY;
output   s_stream_TVALID;
input   s_stream_TREADY;
output   ap_ready;
output   ap_idle;
input   ap_continue;

 reg    ap_rst_n_inv;
wire    do_buffer_1_U0_ap_start;
wire    do_buffer_1_U0_ap_done;
wire    do_buffer_1_U0_ap_continue;
wire    do_buffer_1_U0_ap_idle;
wire    do_buffer_1_U0_ap_ready;
wire    do_buffer_1_U0_i_stream_TREADY;
wire   [63:0] do_buffer_1_U0_q_stream_TDATA;
wire    do_buffer_1_U0_q_stream_TVALID;
wire    ap_sync_continue;
wire    do_buffer_U0_ap_start;
wire    do_buffer_U0_ap_done;
wire    do_buffer_U0_ap_continue;
wire    do_buffer_U0_ap_idle;
wire    do_buffer_U0_ap_ready;
wire    do_buffer_U0_i_s_stream_TREADY;
wire   [7:0] do_buffer_U0_s_stream_TDATA;
wire    do_buffer_U0_s_stream_TVALID;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_do_buffer_1_U0_ap_ready;
wire    ap_sync_do_buffer_1_U0_ap_ready;
reg    ap_sync_reg_do_buffer_U0_ap_ready;
wire    ap_sync_do_buffer_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_sync_reg_do_buffer_1_U0_ap_ready = 1'b0;
//#0 ap_sync_reg_do_buffer_U0_ap_ready = 1'b0;
end

B_BUFFER_do_buffer_1 do_buffer_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(do_buffer_1_U0_ap_start),
    .ap_done(do_buffer_1_U0_ap_done),
    .ap_continue(do_buffer_1_U0_ap_continue),
    .ap_idle(do_buffer_1_U0_ap_idle),
    .ap_ready(do_buffer_1_U0_ap_ready),
    .i_stream_TDATA(i_stream_TDATA),
    .i_stream_TVALID(i_stream_TVALID),
    .i_stream_TREADY(do_buffer_1_U0_i_stream_TREADY),
    .q_stream_TDATA(do_buffer_1_U0_q_stream_TDATA),
    .q_stream_TVALID(do_buffer_1_U0_q_stream_TVALID),
    .q_stream_TREADY(q_stream_TREADY)
);

B_BUFFER_do_buffer do_buffer_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(do_buffer_U0_ap_start),
    .ap_done(do_buffer_U0_ap_done),
    .ap_continue(do_buffer_U0_ap_continue),
    .ap_idle(do_buffer_U0_ap_idle),
    .ap_ready(do_buffer_U0_ap_ready),
    .i_s_stream_TDATA(i_s_stream_TDATA),
    .i_s_stream_TVALID(i_s_stream_TVALID),
    .i_s_stream_TREADY(do_buffer_U0_i_s_stream_TREADY),
    .s_stream_TDATA(do_buffer_U0_s_stream_TDATA),
    .s_stream_TVALID(do_buffer_U0_s_stream_TVALID),
    .s_stream_TREADY(s_stream_TREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_do_buffer_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_do_buffer_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_do_buffer_1_U0_ap_ready <= ap_sync_do_buffer_1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_do_buffer_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_do_buffer_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_do_buffer_U0_ap_ready <= ap_sync_do_buffer_U0_ap_ready;
        end
    end
end

assign ap_done = ap_sync_done;

assign ap_idle = (do_buffer_U0_ap_idle & do_buffer_1_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_do_buffer_1_U0_ap_ready = (do_buffer_1_U0_ap_ready | ap_sync_reg_do_buffer_1_U0_ap_ready);

assign ap_sync_do_buffer_U0_ap_ready = (do_buffer_U0_ap_ready | ap_sync_reg_do_buffer_U0_ap_ready);

assign ap_sync_done = (do_buffer_U0_ap_done & do_buffer_1_U0_ap_done);

assign ap_sync_ready = (ap_sync_do_buffer_U0_ap_ready & ap_sync_do_buffer_1_U0_ap_ready);

assign do_buffer_1_U0_ap_continue = ap_sync_continue;

assign do_buffer_1_U0_ap_start = ((ap_sync_reg_do_buffer_1_U0_ap_ready ^ 1'b1) & ap_start);

assign do_buffer_U0_ap_continue = ap_sync_continue;

assign do_buffer_U0_ap_start = ((ap_sync_reg_do_buffer_U0_ap_ready ^ 1'b1) & ap_start);

assign i_s_stream_TREADY = do_buffer_U0_i_s_stream_TREADY;

assign i_stream_TREADY = do_buffer_1_U0_i_stream_TREADY;

assign q_stream_TDATA = do_buffer_1_U0_q_stream_TDATA;

assign q_stream_TVALID = do_buffer_1_U0_q_stream_TVALID;

assign s_stream_TDATA = do_buffer_U0_s_stream_TDATA;

assign s_stream_TVALID = do_buffer_U0_s_stream_TVALID;

endmodule //B_BUFFER
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module B_BUFFER_do_buffer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        i_s_stream_TDATA,
        i_s_stream_TVALID,
        i_s_stream_TREADY,
        s_stream_TDATA,
        s_stream_TVALID,
        s_stream_TREADY
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] i_s_stream_TDATA;
input   i_s_stream_TVALID;
output   i_s_stream_TREADY;
output  [7:0] s_stream_TDATA;
output   s_stream_TVALID;
input   s_stream_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] BUF_V_0_address0;
reg    BUF_V_0_ce0;
reg    BUF_V_0_we0;
wire   [3:0] BUF_V_0_q0;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_done;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_idle;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_ready;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_i_s_stream_TREADY;
wire   [3:0] grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_address0;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_ce0;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_we0;
wire   [3:0] grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_d0;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_done;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_idle;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_ready;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_s_stream_TREADY;
wire   [3:0] grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_BUF_V_0_address0;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_BUF_V_0_ce0;
wire   [7:0] grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_s_stream_TDATA;
wire    grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_s_stream_TVALID;
reg    grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    regslice_both_s_stream_U_apdone_blk;
reg   [6:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    regslice_both_i_s_stream_U_apdone_blk;
wire   [7:0] i_s_stream_TDATA_int_regslice;
wire    i_s_stream_TVALID_int_regslice;
reg    i_s_stream_TREADY_int_regslice;
wire    regslice_both_i_s_stream_U_ack_in;
wire    s_stream_TREADY_int_regslice;
wire    regslice_both_s_stream_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_done_reg = 1'b0;
//#0 ap_CS_fsm = 7'd1;
//#0 grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start_reg = 1'b0;
//#0 grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start_reg = 1'b0;
end

B_BUFFER_do_buffer_BUF_V_0_RAM_AUTO_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
BUF_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(BUF_V_0_address0),
    .ce0(BUF_V_0_ce0),
    .we0(BUF_V_0_we0),
    .d0(grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_d0),
    .q0(BUF_V_0_q0)
);

B_BUFFER_do_buffer_Pipeline_VITIS_LOOP_33_3 grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start),
    .ap_done(grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_done),
    .ap_idle(grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_idle),
    .ap_ready(grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_ready),
    .i_s_stream_TVALID(i_s_stream_TVALID_int_regslice),
    .i_s_stream_TDATA(i_s_stream_TDATA_int_regslice),
    .i_s_stream_TREADY(grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_i_s_stream_TREADY),
    .BUF_V_0_address0(grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_address0),
    .BUF_V_0_ce0(grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_ce0),
    .BUF_V_0_we0(grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_we0),
    .BUF_V_0_d0(grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_d0)
);

B_BUFFER_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3 grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start),
    .ap_done(grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_done),
    .ap_idle(grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_idle),
    .ap_ready(grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_ready),
    .s_stream_TREADY(grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_s_stream_TREADY),
    .BUF_V_0_address0(grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_BUF_V_0_address0),
    .BUF_V_0_ce0(grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_BUF_V_0_ce0),
    .BUF_V_0_q0(BUF_V_0_q0),
    .s_stream_TDATA(grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_s_stream_TDATA),
    .s_stream_TVALID(grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_s_stream_TVALID)
);

B_BUFFER_regslice_both #(
    .DataWidth( 8 ))
regslice_both_i_s_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(i_s_stream_TDATA),
    .vld_in(i_s_stream_TVALID),
    .ack_in(regslice_both_i_s_stream_U_ack_in),
    .data_out(i_s_stream_TDATA_int_regslice),
    .vld_out(i_s_stream_TVALID_int_regslice),
    .ack_out(i_s_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_s_stream_U_apdone_blk)
);

B_BUFFER_regslice_both #(
    .DataWidth( 8 ))
regslice_both_s_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_s_stream_TDATA),
    .vld_in(grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_s_stream_TVALID),
    .ack_in(s_stream_TREADY_int_regslice),
    .data_out(s_stream_TDATA),
    .vld_out(regslice_both_s_stream_U_vld_out),
    .ack_out(s_stream_TREADY),
    .apdone_blk(regslice_both_s_stream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_s_stream_U_apdone_blk == 1'b0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start_reg <= 1'b1;
        end else if ((grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_ready == 1'b1)) begin
            grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start_reg <= 1'b1;
        end else if ((grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_ready == 1'b1)) begin
            grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        BUF_V_0_address0 = grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_BUF_V_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        BUF_V_0_address0 = grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_address0;
    end else begin
        BUF_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        BUF_V_0_ce0 = grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_BUF_V_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        BUF_V_0_ce0 = grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_ce0;
    end else begin
        BUF_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        BUF_V_0_we0 = grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_we0;
    end else begin
        BUF_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_s_stream_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_s_stream_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_s_stream_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_s_stream_TREADY_int_regslice = grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_i_s_stream_TREADY;
    end else begin
        i_s_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_s_stream_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start = grp_do_buffer_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start_reg;

assign grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start = grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start_reg;

assign grp_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_s_stream_TREADY = (s_stream_TREADY_int_regslice & ap_CS_fsm_state6);

assign i_s_stream_TREADY = regslice_both_i_s_stream_U_ack_in;

assign s_stream_TVALID = regslice_both_s_stream_U_vld_out;

endmodule //B_BUFFER_do_buffer
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module B_BUFFER_do_buffer_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        i_stream_TDATA,
        i_stream_TVALID,
        i_stream_TREADY,
        q_stream_TDATA,
        q_stream_TVALID,
        q_stream_TREADY
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] i_stream_TDATA;
input   i_stream_TVALID;
output   i_stream_TREADY;
output  [63:0] q_stream_TDATA;
output   q_stream_TVALID;
input   q_stream_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] BUF_V_0_address0;
reg    BUF_V_0_ce0;
reg    BUF_V_0_we0;
wire   [63:0] BUF_V_0_q0;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_done;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_idle;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_ready;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_i_stream_TREADY;
wire   [3:0] grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_address0;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_ce0;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_we0;
wire   [63:0] grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_d0;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_done;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_idle;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_ready;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_q_stream_TREADY;
wire   [3:0] grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_BUF_V_0_address0;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_BUF_V_0_ce0;
wire   [63:0] grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_q_stream_TDATA;
wire    grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_q_stream_TVALID;
reg    grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    regslice_both_q_stream_U_apdone_blk;
reg   [6:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    regslice_both_i_stream_U_apdone_blk;
wire   [63:0] i_stream_TDATA_int_regslice;
wire    i_stream_TVALID_int_regslice;
reg    i_stream_TREADY_int_regslice;
wire    regslice_both_i_stream_U_ack_in;
wire    q_stream_TREADY_int_regslice;
wire    regslice_both_q_stream_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_done_reg = 1'b0;
//#0 ap_CS_fsm = 7'd1;
//#0 grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start_reg = 1'b0;
//#0 grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start_reg = 1'b0;
end

B_BUFFER_do_buffer_1_BUF_V_0_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
BUF_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(BUF_V_0_address0),
    .ce0(BUF_V_0_ce0),
    .we0(BUF_V_0_we0),
    .d0(grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_d0),
    .q0(BUF_V_0_q0)
);

B_BUFFER_do_buffer_1_Pipeline_VITIS_LOOP_33_3 grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start),
    .ap_done(grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_done),
    .ap_idle(grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_idle),
    .ap_ready(grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_ready),
    .i_stream_TVALID(i_stream_TVALID_int_regslice),
    .i_stream_TDATA(i_stream_TDATA_int_regslice),
    .i_stream_TREADY(grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_i_stream_TREADY),
    .BUF_V_0_address0(grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_address0),
    .BUF_V_0_ce0(grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_ce0),
    .BUF_V_0_we0(grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_we0),
    .BUF_V_0_d0(grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_d0)
);

B_BUFFER_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3 grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start),
    .ap_done(grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_done),
    .ap_idle(grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_idle),
    .ap_ready(grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_ready),
    .q_stream_TREADY(grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_q_stream_TREADY),
    .BUF_V_0_address0(grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_BUF_V_0_address0),
    .BUF_V_0_ce0(grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_BUF_V_0_ce0),
    .BUF_V_0_q0(BUF_V_0_q0),
    .q_stream_TDATA(grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_q_stream_TDATA),
    .q_stream_TVALID(grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_q_stream_TVALID)
);

B_BUFFER_regslice_both #(
    .DataWidth( 64 ))
regslice_both_i_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(i_stream_TDATA),
    .vld_in(i_stream_TVALID),
    .ack_in(regslice_both_i_stream_U_ack_in),
    .data_out(i_stream_TDATA_int_regslice),
    .vld_out(i_stream_TVALID_int_regslice),
    .ack_out(i_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_stream_U_apdone_blk)
);

B_BUFFER_regslice_both #(
    .DataWidth( 64 ))
regslice_both_q_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_q_stream_TDATA),
    .vld_in(grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_q_stream_TVALID),
    .ack_in(q_stream_TREADY_int_regslice),
    .data_out(q_stream_TDATA),
    .vld_out(regslice_both_q_stream_U_vld_out),
    .ack_out(q_stream_TREADY),
    .apdone_blk(regslice_both_q_stream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_q_stream_U_apdone_blk == 1'b0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start_reg <= 1'b1;
        end else if ((grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_ready == 1'b1)) begin
            grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start_reg <= 1'b1;
        end else if ((grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_ready == 1'b1)) begin
            grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        BUF_V_0_address0 = grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_BUF_V_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        BUF_V_0_address0 = grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_address0;
    end else begin
        BUF_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        BUF_V_0_ce0 = grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_BUF_V_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        BUF_V_0_ce0 = grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_ce0;
    end else begin
        BUF_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        BUF_V_0_we0 = grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_BUF_V_0_we0;
    end else begin
        BUF_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_q_stream_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_q_stream_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_q_stream_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_stream_TREADY_int_regslice = grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_i_stream_TREADY;
    end else begin
        i_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (regslice_both_q_stream_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start = grp_do_buffer_1_Pipeline_VITIS_LOOP_33_3_fu_30_ap_start_reg;

assign grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start = grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_ap_start_reg;

assign grp_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3_fu_37_q_stream_TREADY = (q_stream_TREADY_int_regslice & ap_CS_fsm_state6);

assign i_stream_TREADY = regslice_both_i_stream_U_ack_in;

assign q_stream_TVALID = regslice_both_q_stream_U_vld_out;

endmodule //B_BUFFER_do_buffer_1
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module B_BUFFER_do_buffer_1_BUF_V_0_RAM_AUTO_1R1W (
     
    address0, ce0,
    d0, we0, 
    q0, 
     
    reset, clk);

parameter DataWidth = 64;
parameter AddressWidth = 4;
parameter AddressRange = 16;
 
input[AddressWidth-1:0] address0;
input ce0;
input[DataWidth-1:0] d0;
input we0; 
output reg[DataWidth-1:0] q0; 

input reset;
input clk;

(* ram_style = "auto"  *)reg [DataWidth-1:0] ram[0:AddressRange-1];


 





//read first
always @(posedge clk)  
begin 
    if (ce0) begin
        if (we0) 
            ram[address0] <= d0; 
        q0 <= ram[address0];

    end
end 
 
 

endmodule

// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module B_BUFFER_do_buffer_1_Pipeline_VITIS_LOOP_33_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i_stream_TVALID,
        i_stream_TDATA,
        i_stream_TREADY,
        BUF_V_0_address0,
        BUF_V_0_ce0,
        BUF_V_0_we0,
        BUF_V_0_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   i_stream_TVALID;
input  [63:0] i_stream_TDATA;
output   i_stream_TREADY;
output  [3:0] BUF_V_0_address0;
output   BUF_V_0_ce0;
output   BUF_V_0_we0;
output  [63:0] BUF_V_0_d0;

reg ap_idle;
reg i_stream_TREADY;
reg BUF_V_0_ce0;
reg BUF_V_0_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln33_fu_76_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    i_stream_TDATA_blk_n;
wire   [63:0] zext_ln33_fu_82_p1;
reg   [4:0] ct_fu_38;
wire   [4:0] add_ln33_fu_70_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_ct_2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_96;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_CS_fsm = 1'd1;
//#0 ap_done_reg = 1'b0;
end

B_BUFFER_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_76_p2 == 1'd0) & (i_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_96)) begin
        if ((icmp_ln33_fu_76_p2 == 1'd0)) begin
            ct_fu_38 <= add_ln33_fu_70_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ct_fu_38 <= 5'd0;
        end
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_76_p2 == 1'd0) & (i_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        BUF_V_0_ce0 = 1'b1;
    end else begin
        BUF_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_76_p2 == 1'd0) & (i_stream_TVALID == 1'b0))) & (icmp_ln33_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        BUF_V_0_we0 = 1'b1;
    end else begin
        BUF_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln33_fu_76_p2 == 1'd0) & (i_stream_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_76_p2 == 1'd0) & (i_stream_TVALID == 1'b0))) & (icmp_ln33_fu_76_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_76_p2 == 1'd0) & (i_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_76_p2 == 1'd0) & (i_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_ct_2 = 5'd0;
    end else begin
        ap_sig_allocacmp_ct_2 = ct_fu_38;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln33_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        i_stream_TDATA_blk_n = i_stream_TVALID;
    end else begin
        i_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_76_p2 == 1'd0) & (i_stream_TVALID == 1'b0))) & (icmp_ln33_fu_76_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        i_stream_TREADY = 1'b1;
    end else begin
        i_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign BUF_V_0_address0 = zext_ln33_fu_82_p1;

assign BUF_V_0_d0 = i_stream_TDATA;

assign add_ln33_fu_70_p2 = (ap_sig_allocacmp_ct_2 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln33_fu_76_p2 == 1'd0) & (i_stream_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_96 = (~((ap_start_int == 1'b0) | ((icmp_ln33_fu_76_p2 == 1'd0) & (i_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln33_fu_76_p2 = ((ap_sig_allocacmp_ct_2 == 5'd16) ? 1'b1 : 1'b0);

assign zext_ln33_fu_82_p1 = ap_sig_allocacmp_ct_2;

endmodule //B_BUFFER_do_buffer_1_Pipeline_VITIS_LOOP_33_3
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module B_BUFFER_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        q_stream_TREADY,
        BUF_V_0_address0,
        BUF_V_0_ce0,
        BUF_V_0_q0,
        q_stream_TDATA,
        q_stream_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   q_stream_TREADY;
output  [3:0] BUF_V_0_address0;
output   BUF_V_0_ce0;
input  [63:0] BUF_V_0_q0;
output  [63:0] q_stream_TDATA;
output   q_stream_TVALID;

reg ap_idle;
reg BUF_V_0_ce0;
reg q_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln79_fu_94_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    q_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln80_fu_117_p1;
reg   [4:0] ct_1_fu_46;
wire   [4:0] add_ln80_fu_122_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_ct_1_load;
reg   [7:0] indvar_flatten_fu_50;
wire   [7:0] add_ln79_fu_88_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln80_fu_103_p2;
wire   [4:0] select_ln79_fu_109_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_CS_fsm = 1'd1;
//#0 ap_enable_reg_pp0_iter1 = 1'b0;
//#0 ap_done_reg = 1'b0;
end

B_BUFFER_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln79_fu_94_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ct_1_fu_46 <= add_ln80_fu_122_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ct_1_fu_46 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln79_fu_94_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_50 <= add_ln79_fu_88_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_50 <= 8'd0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        BUF_V_0_ce0 = 1'b1;
    end else begin
        BUF_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln79_fu_94_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ct_1_load = 5'd0;
    end else begin
        ap_sig_allocacmp_ct_1_load = ct_1_fu_46;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        q_stream_TDATA_blk_n = q_stream_TREADY;
    end else begin
        q_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        q_stream_TVALID = 1'b1;
    end else begin
        q_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign BUF_V_0_address0 = zext_ln80_fu_117_p1;

assign add_ln79_fu_88_p2 = (ap_sig_allocacmp_indvar_flatten_load + 8'd1);

assign add_ln80_fu_122_p2 = (select_ln79_fu_109_p3 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((q_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((q_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((q_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (q_stream_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln79_fu_94_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 8'd160) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_103_p2 = ((ap_sig_allocacmp_ct_1_load == 5'd16) ? 1'b1 : 1'b0);

assign q_stream_TDATA = BUF_V_0_q0;

assign select_ln79_fu_109_p3 = ((icmp_ln80_fu_103_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_ct_1_load);

assign zext_ln80_fu_117_p1 = select_ln79_fu_109_p3;

endmodule //B_BUFFER_do_buffer_1_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module B_BUFFER_do_buffer_BUF_V_0_RAM_AUTO_1R1W (
     
    address0, ce0,
    d0, we0, 
    q0, 
     
    reset, clk);

parameter DataWidth = 4;
parameter AddressWidth = 4;
parameter AddressRange = 16;
 
input[AddressWidth-1:0] address0;
input ce0;
input[DataWidth-1:0] d0;
input we0; 
output reg[DataWidth-1:0] q0; 

input reset;
input clk;

(* ram_style = "auto"  *)reg [DataWidth-1:0] ram[0:AddressRange-1];


 





//read first
always @(posedge clk)  
begin 
    if (ce0) begin
        if (we0) 
            ram[address0] <= d0; 
        q0 <= ram[address0];

    end
end 
 
 

endmodule

// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module B_BUFFER_do_buffer_Pipeline_VITIS_LOOP_33_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i_s_stream_TVALID,
        i_s_stream_TDATA,
        i_s_stream_TREADY,
        BUF_V_0_address0,
        BUF_V_0_ce0,
        BUF_V_0_we0,
        BUF_V_0_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   i_s_stream_TVALID;
input  [7:0] i_s_stream_TDATA;
output   i_s_stream_TREADY;
output  [3:0] BUF_V_0_address0;
output   BUF_V_0_ce0;
output   BUF_V_0_we0;
output  [3:0] BUF_V_0_d0;

reg ap_idle;
reg i_s_stream_TREADY;
reg BUF_V_0_ce0;
reg BUF_V_0_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln33_fu_75_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    i_s_stream_TDATA_blk_n;
wire   [63:0] zext_ln33_fu_81_p1;
reg   [4:0] ct_fu_38;
wire   [4:0] add_ln33_fu_69_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_ct_1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_99;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_CS_fsm = 1'd1;
//#0 ap_done_reg = 1'b0;
end

B_BUFFER_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_75_p2 == 1'd0) & (i_s_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_99)) begin
        if ((icmp_ln33_fu_75_p2 == 1'd0)) begin
            ct_fu_38 <= add_ln33_fu_69_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ct_fu_38 <= 5'd0;
        end
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_75_p2 == 1'd0) & (i_s_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        BUF_V_0_ce0 = 1'b1;
    end else begin
        BUF_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_75_p2 == 1'd0) & (i_s_stream_TVALID == 1'b0))) & (icmp_ln33_fu_75_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        BUF_V_0_we0 = 1'b1;
    end else begin
        BUF_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln33_fu_75_p2 == 1'd0) & (i_s_stream_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_75_p2 == 1'd0) & (i_s_stream_TVALID == 1'b0))) & (icmp_ln33_fu_75_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_75_p2 == 1'd0) & (i_s_stream_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_75_p2 == 1'd0) & (i_s_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_ct_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_ct_1 = ct_fu_38;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln33_fu_75_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        i_s_stream_TDATA_blk_n = i_s_stream_TVALID;
    end else begin
        i_s_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln33_fu_75_p2 == 1'd0) & (i_s_stream_TVALID == 1'b0))) & (icmp_ln33_fu_75_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        i_s_stream_TREADY = 1'b1;
    end else begin
        i_s_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign BUF_V_0_address0 = zext_ln33_fu_81_p1;

assign BUF_V_0_d0 = i_s_stream_TDATA[3:0];

assign add_ln33_fu_69_p2 = (ap_sig_allocacmp_ct_1 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln33_fu_75_p2 == 1'd0) & (i_s_stream_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_99 = (~((ap_start_int == 1'b0) | ((icmp_ln33_fu_75_p2 == 1'd0) & (i_s_stream_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln33_fu_75_p2 = ((ap_sig_allocacmp_ct_1 == 5'd16) ? 1'b1 : 1'b0);

assign zext_ln33_fu_81_p1 = ap_sig_allocacmp_ct_1;

endmodule //B_BUFFER_do_buffer_Pipeline_VITIS_LOOP_33_3
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module B_BUFFER_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        s_stream_TREADY,
        BUF_V_0_address0,
        BUF_V_0_ce0,
        BUF_V_0_q0,
        s_stream_TDATA,
        s_stream_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   s_stream_TREADY;
output  [3:0] BUF_V_0_address0;
output   BUF_V_0_ce0;
input  [3:0] BUF_V_0_q0;
output  [7:0] s_stream_TDATA;
output   s_stream_TVALID;

reg ap_idle;
reg BUF_V_0_ce0;
reg s_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln79_fu_93_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln80_fu_116_p1;
reg   [4:0] ct_fu_46;
wire   [4:0] add_ln80_fu_121_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_ct_load;
reg   [7:0] indvar_flatten_fu_50;
wire   [7:0] add_ln79_fu_87_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln80_fu_102_p2;
wire   [4:0] select_ln79_fu_108_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_CS_fsm = 1'd1;
//#0 ap_enable_reg_pp0_iter1 = 1'b0;
//#0 ap_done_reg = 1'b0;
end

B_BUFFER_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln79_fu_93_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ct_fu_46 <= add_ln80_fu_121_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ct_fu_46 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln79_fu_93_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_50 <= add_ln79_fu_87_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_50 <= 8'd0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        BUF_V_0_ce0 = 1'b1;
    end else begin
        BUF_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln79_fu_93_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ct_load = 5'd0;
    end else begin
        ap_sig_allocacmp_ct_load = ct_fu_46;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_stream_TDATA_blk_n = s_stream_TREADY;
    end else begin
        s_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_stream_TVALID = 1'b1;
    end else begin
        s_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign BUF_V_0_address0 = zext_ln80_fu_116_p1;

assign add_ln79_fu_87_p2 = (ap_sig_allocacmp_indvar_flatten_load + 8'd1);

assign add_ln80_fu_121_p2 = (select_ln79_fu_108_p3 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((s_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((s_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((s_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (s_stream_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln79_fu_93_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 8'd160) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_102_p2 = ((ap_sig_allocacmp_ct_load == 5'd16) ? 1'b1 : 1'b0);

assign s_stream_TDATA = BUF_V_0_q0;

assign select_ln79_fu_108_p3 = ((icmp_ln80_fu_102_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_ct_load);

assign zext_ln80_fu_116_p1 = select_ln79_fu_108_p3;

endmodule //B_BUFFER_do_buffer_Pipeline_VITIS_LOOP_79_2_VITIS_LOOP_80_3
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

module B_BUFFER_flow_control_loop_pipe_sequential_init(
        ap_clk,
        ap_rst,
        ap_start,
        ap_ready,
        ap_done,
        ap_start_int,
        ap_ready_int,
        ap_done_int,
        ap_continue_int,
        ap_loop_init,
        ap_loop_exit_ready,
        ap_loop_exit_done
);

input   ap_clk;
input   ap_rst;

//Block level handshake with outside loop
input   ap_start;
output  ap_ready;
output  ap_done;

//Block level handshake with loop body
output  ap_start_int;
input   ap_ready_int;
input   ap_done_int;
output  ap_continue_int;

//Init live in variables
output   ap_loop_init;
wire     ap_loop_init;
reg ap_loop_init_int;
reg ap_done;
reg ap_done_cache;

//Exit signal from loop body
input   ap_loop_exit_ready;
input   ap_loop_exit_done;

// power-on initialization
initial begin
//#0 ap_loop_init_int = 1'b1;
//#0 ap_done_cache = 1'b0;
end

assign ap_start_int = ap_start;

assign ap_continue_int = 1'b1;

assign ap_ready = ap_loop_exit_ready;

//ap_loop_init is valid for the first II
//of the first loop run so as to enable
//the init block ops which are pushed into
//the first state of the pipeline region
always @ (posedge ap_clk)
begin
    if (ap_rst == 1'b1) begin
        ap_loop_init_int <= 1'b1;
    end else if(ap_loop_exit_done == 1'b1) begin
        ap_loop_init_int <= 1'b1;
    end else if(ap_ready_int == 1'b1) begin
        ap_loop_init_int <= 1'b0;
    end
end

assign ap_loop_init = ap_loop_init_int & ap_start;

// if no ap_continue port and current module is not B_BUFFER module, 
// ap_done handshakes with ap_start. Internally, flow control sends out 
// ap_conintue_int = 1'b1 so the ap_done_int is asserted high for 1 clock cycle.
// ap_done_cache is used to record ap_done_int, and de-assert if ap_start_int
// is asserted, so DUT can start the next run
always @(posedge ap_clk)
begin
    if (ap_rst == 1'b1) begin
        ap_done_cache <= 1'b0;
    end else if (ap_done_int == 1'b1) begin
        ap_done_cache <= 1'b1;
    end else if (ap_start_int == 1'b1) begin
        ap_done_cache <= 1'b0;
    end
end

// if no ap_continue port and current module is not B_BUFFER module, ap_done handshakes with ap_start
always @(*)
begin
    if ((ap_done_int == 1'b1) || ((ap_done_cache == 1'b1) && (ap_start_int == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

endmodule
        
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1ns/1ps

module B_BUFFER_regslice_both
#(parameter 
    DataWidth=32
)(
    input ap_clk ,
    input ap_rst,

    input [DataWidth-1:0] data_in , 
    input vld_in , 
    output ack_in ,
    output [DataWidth-1:0] data_out, 
    output vld_out,
    input ack_out,
    output apdone_blk
);
 

reg   [1:0] B_V_data_1_state;
wire   [DataWidth-1:0] B_V_data_1_data_in;
reg   [DataWidth-1:0] B_V_data_1_data_out;
wire    B_V_data_1_vld_reg;
wire    B_V_data_1_vld_in;
wire    B_V_data_1_vld_out;
reg   [DataWidth-1:0] B_V_data_1_payload_A;
reg   [DataWidth-1:0] B_V_data_1_payload_B;
reg    B_V_data_1_sel_rd;
reg    B_V_data_1_sel_wr;
wire    B_V_data_1_sel;
wire    B_V_data_1_load_A;
wire    B_V_data_1_load_B;
wire    B_V_data_1_state_cmp_full;
wire    B_V_data_1_ack_in;
wire    B_V_data_1_ack_out;

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_out) & (1'b1 == B_V_data_1_ack_out))) begin
            B_V_data_1_sel_rd <= ~B_V_data_1_sel_rd;
        end else begin
            B_V_data_1_sel_rd <= B_V_data_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_in))) begin
            B_V_data_1_sel_wr <= ~B_V_data_1_sel_wr;
        end else begin
            B_V_data_1_sel_wr <= B_V_data_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_state <= 2'd0;
    end else begin
        if ((((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) | ((2'd2 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd2;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out)) | ((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd1;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b1 == B_V_data_1_ack_out)) | (~((1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)) & ~((1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) & (2'd3 == B_V_data_1_state)) | ((2'd2 == B_V_data_1_state) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd3;
        end else begin
            B_V_data_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_A)) begin
        B_V_data_1_payload_A <= B_V_data_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_B)) begin
        B_V_data_1_payload_B <= B_V_data_1_data_in;
    end
end

always @ (*) begin
    if ((1'b1 == B_V_data_1_sel)) begin
        B_V_data_1_data_out = B_V_data_1_payload_B;
    end else begin
        B_V_data_1_data_out = B_V_data_1_payload_A;
    end
end

assign B_V_data_1_ack_in = B_V_data_1_state[1'd1];
assign B_V_data_1_load_A = (~B_V_data_1_sel_wr & B_V_data_1_state_cmp_full);
assign B_V_data_1_load_B = (B_V_data_1_state_cmp_full & B_V_data_1_sel_wr);
assign B_V_data_1_sel = B_V_data_1_sel_rd;
assign B_V_data_1_state_cmp_full = ((B_V_data_1_state != 2'd1) ? 1'b1 : 1'b0);
assign B_V_data_1_vld_out = B_V_data_1_state[1'd0];

assign ack_in = B_V_data_1_ack_in;
assign B_V_data_1_data_in = data_in;
assign B_V_data_1_vld_in = vld_in;

assign vld_out = B_V_data_1_vld_out;
assign data_out = B_V_data_1_data_out;
assign B_V_data_1_ack_out = ack_out;

assign apdone_blk = ((B_V_data_1_state == 2'd3 && ack_out == 1'b0) | (B_V_data_1_state == 2'd1));

endmodule // both

module B_BUFFER_regslice_both_w1
#(parameter 
    DataWidth=1
)(
    input ap_clk ,
    input ap_rst,

    input data_in , 
    input vld_in , 
    output ack_in ,
    output data_out, 
    output vld_out,
    input ack_out,
    output apdone_blk
);

reg     [1:0] B_V_data_1_state;
wire    B_V_data_1_data_in;
reg     B_V_data_1_data_out;
wire    B_V_data_1_vld_reg;
wire    B_V_data_1_vld_in;
wire    B_V_data_1_vld_out;
reg     B_V_data_1_payload_A;
reg     B_V_data_1_payload_B;
reg     B_V_data_1_sel_rd;
reg     B_V_data_1_sel_wr;
wire    B_V_data_1_sel;
wire    B_V_data_1_load_A;
wire    B_V_data_1_load_B;
wire    B_V_data_1_state_cmp_full;
wire    B_V_data_1_ack_in;
wire    B_V_data_1_ack_out;

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_out) & (1'b1 == B_V_data_1_ack_out))) begin
            B_V_data_1_sel_rd <= ~B_V_data_1_sel_rd;
        end else begin
            B_V_data_1_sel_rd <= B_V_data_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_in))) begin
            B_V_data_1_sel_wr <= ~B_V_data_1_sel_wr;
        end else begin
            B_V_data_1_sel_wr <= B_V_data_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_state <= 2'd0;
    end else begin
        if ((((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) | ((2'd2 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd2;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out)) | ((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd1;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b1 == B_V_data_1_ack_out)) | (~((1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)) & ~((1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) & (2'd3 == B_V_data_1_state)) | ((2'd2 == B_V_data_1_state) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd3;
        end else begin
            B_V_data_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_A)) begin
        B_V_data_1_payload_A <= B_V_data_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_B)) begin
        B_V_data_1_payload_B <= B_V_data_1_data_in;
    end
end

always @ (*) begin
    if ((1'b1 == B_V_data_1_sel)) begin
        B_V_data_1_data_out = B_V_data_1_payload_B;
    end else begin
        B_V_data_1_data_out = B_V_data_1_payload_A;
    end
end

assign B_V_data_1_ack_in = B_V_data_1_state[1'd1];
assign B_V_data_1_load_A = (~B_V_data_1_sel_wr & B_V_data_1_state_cmp_full);
assign B_V_data_1_load_B = (B_V_data_1_state_cmp_full & B_V_data_1_sel_wr);
assign B_V_data_1_sel = B_V_data_1_sel_rd;
assign B_V_data_1_state_cmp_full = ((B_V_data_1_state != 2'd1) ? 1'b1 : 1'b0);
assign B_V_data_1_vld_out = B_V_data_1_state[1'd0];

assign ack_in = B_V_data_1_ack_in;
assign B_V_data_1_data_in = data_in;
assign B_V_data_1_vld_in = vld_in;

assign vld_out = B_V_data_1_vld_out;
assign data_out = B_V_data_1_data_out;
assign B_V_data_1_ack_out = ack_out;

assign apdone_blk = ((B_V_data_1_state == 2'd3 && ack_out == 1'b0) | (B_V_data_1_state == 2'd1));

endmodule // both


