/* verilator lint_off PINMISSING */
/* verilator lint_off CASEINCOMPLETE */
/* verilator lint_off COMBDLY */
/* verilator lint_off CASEX */
/* verilator lint_off CASEOVERLAP */
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="SILU_DEMUX_SILU_DEMUX,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvc1902-vsva2197-2MP-e-S,HLS_INPUT_CLOCK=2.500000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.295500,HLS_SYN_LAT=1315,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=93,HLS_SYN_LUT=73,HLS_VERSION=2022_2}" *)

module SILU_DEMUX (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        silu_stream_TVALID,
        silu_s_stream_TVALID,
        x_stream_TREADY,
        x_s_stream_TREADY,
        x_stream2_TREADY,
        x_s_stream2_TREADY,
        z_stream_TREADY,
        z_s_stream_TREADY,
        C_stream_TREADY,
        C_s_stream_TREADY,
        B_stream_TREADY,
        B_s_stream_TREADY,
        silu_stream_TDATA,
        silu_stream_TREADY,
        silu_s_stream_TDATA,
        silu_s_stream_TREADY,
        x_stream_TDATA,
        x_stream_TVALID,
        x_s_stream_TDATA,
        x_s_stream_TVALID,
        x_stream2_TDATA,
        x_stream2_TVALID,
        x_s_stream2_TDATA,
        x_s_stream2_TVALID,
        B_stream_TDATA,
        B_stream_TVALID,
        B_s_stream_TDATA,
        B_s_stream_TVALID,
        C_stream_TDATA,
        C_stream_TVALID,
        C_s_stream_TDATA,
        C_s_stream_TVALID,
        z_stream_TDATA,
        z_stream_TVALID,
        z_s_stream_TDATA,
        z_s_stream_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   silu_stream_TVALID;
input   silu_s_stream_TVALID;
input   x_stream_TREADY;
input   x_s_stream_TREADY;
input   x_stream2_TREADY;
input   x_s_stream2_TREADY;
input   z_stream_TREADY;
input   z_s_stream_TREADY;
input   C_stream_TREADY;
input   C_s_stream_TREADY;
input   B_stream_TREADY;
input   B_s_stream_TREADY;
input  [63:0] silu_stream_TDATA;
output   silu_stream_TREADY;
input  [7:0] silu_s_stream_TDATA;
output   silu_s_stream_TREADY;
output  [63:0] x_stream_TDATA;
output   x_stream_TVALID;
output  [7:0] x_s_stream_TDATA;
output   x_s_stream_TVALID;
output  [63:0] x_stream2_TDATA;
output   x_stream2_TVALID;
output  [7:0] x_s_stream2_TDATA;
output   x_s_stream2_TVALID;
output  [63:0] B_stream_TDATA;
output   B_stream_TVALID;
output  [7:0] B_s_stream_TDATA;
output   B_s_stream_TVALID;
output  [63:0] C_stream_TDATA;
output   C_stream_TVALID;
output  [7:0] C_s_stream_TDATA;
output   C_s_stream_TVALID;
output  [63:0] z_stream_TDATA;
output   z_stream_TVALID;
output  [7:0] z_s_stream_TDATA;
output   z_s_stream_TVALID;

reg ap_idle;
reg x_stream_TVALID;
reg x_s_stream_TVALID;
reg x_stream2_TVALID;
reg x_s_stream2_TVALID;
reg B_stream_TVALID;
reg B_s_stream_TVALID;
reg C_stream_TVALID;
reg C_s_stream_TVALID;
reg z_stream_TVALID;
reg z_s_stream_TVALID;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln78_fu_184_p2;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln82_reg_296;
reg   [0:0] icmp_ln86_reg_300;
reg   [0:0] trunc_ln78_reg_275;
reg    ap_predicate_op56_write_state2;
reg    ap_predicate_op59_write_state2;
reg    ap_predicate_op60_write_state2;
reg    ap_predicate_op61_write_state2;
reg    ap_predicate_op62_write_state2;
reg    ap_predicate_op65_write_state2;
reg    ap_predicate_op66_write_state2;
reg    ap_predicate_op69_write_state2;
wire    regslice_both_x_stream_U_apdone_blk;
wire    regslice_both_x_s_stream_U_apdone_blk;
wire    regslice_both_x_stream2_U_apdone_blk;
wire    regslice_both_x_s_stream2_U_apdone_blk;
wire    regslice_both_B_stream_U_apdone_blk;
wire    regslice_both_B_s_stream_U_apdone_blk;
wire    regslice_both_C_stream_U_apdone_blk;
wire    regslice_both_C_s_stream_U_apdone_blk;
wire    regslice_both_z_stream_U_apdone_blk;
wire    regslice_both_z_s_stream_U_apdone_blk;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln82_reg_296_pp0_iter1_reg;
reg   [0:0] icmp_ln86_reg_300_pp0_iter1_reg;
reg   [0:0] trunc_ln78_reg_275_pp0_iter1_reg;
reg    ap_predicate_op74_write_state3;
reg    ap_predicate_op75_write_state3;
reg    ap_predicate_op76_write_state3;
reg    ap_predicate_op77_write_state3;
reg    ap_predicate_op79_write_state3;
reg    ap_predicate_op80_write_state3;
reg    ap_predicate_op82_write_state3;
reg    ap_predicate_op83_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_loop_exit_ready;
reg    ap_loop_exit_ready_pp0_iter1_reg;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
wire    silu_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
wire    silu_s_stream_TDATA_blk_n;
wire    x_stream_TDATA_blk_n;
wire    x_s_stream_TDATA_blk_n;
wire    x_stream2_TDATA_blk_n;
wire    x_s_stream2_TDATA_blk_n;
wire    B_stream_TDATA_blk_n;
wire    B_s_stream_TDATA_blk_n;
wire    C_stream_TDATA_blk_n;
wire    C_s_stream_TDATA_blk_n;
wire    z_stream_TDATA_blk_n;
wire    z_s_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln78_fu_190_p1;
reg   [63:0] silu_stream_read_reg_279;
reg   [7:0] silu_s_stream_read_reg_288;
wire   [0:0] icmp_ln82_fu_204_p2;
wire   [0:0] icmp_ln86_fu_220_p2;
wire   [7:0] zext_ln92_fu_234_p1;
reg   [10:0] ct_fu_84;
wire   [10:0] ct_2_fu_178_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_ct_1;
wire    ap_block_pp0_stage0_01001;
wire   [6:0] tmp_fu_194_p4;
wire   [5:0] tmp_1_fu_210_p4;
wire   [3:0] trunc_ln92_fu_231_p1;
wire   [3:0] trunc_ln98_fu_240_p1;
wire   [3:0] trunc_ln88_fu_248_p1;
wire   [3:0] trunc_ln84_fu_256_p1;
wire    ap_continue_int;
reg    ap_done_int_frp;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [2:0] frp_pipeline_valid_U_valid_out;
wire   [2:0] frp_pipeline_valid_U_num_valid_datasets;
wire   [7:0] pf_B_s_stream_U_data_out;
wire    pf_B_s_stream_U_data_out_vld;
wire    pf_B_s_stream_U_pf_ready;
wire    pf_B_s_stream_U_pf_done;
wire   [63:0] pf_B_stream_U_data_out;
wire    pf_B_stream_U_data_out_vld;
wire    pf_B_stream_U_pf_ready;
wire    pf_B_stream_U_pf_done;
wire   [7:0] pf_C_s_stream_U_data_out;
wire    pf_C_s_stream_U_data_out_vld;
wire    pf_C_s_stream_U_pf_ready;
wire    pf_C_s_stream_U_pf_done;
wire   [63:0] pf_C_stream_U_data_out;
wire    pf_C_stream_U_data_out_vld;
wire    pf_C_stream_U_pf_ready;
wire    pf_C_stream_U_pf_done;
wire   [7:0] pf_x_s_stream2_U_data_out;
wire    pf_x_s_stream2_U_data_out_vld;
wire    pf_x_s_stream2_U_pf_ready;
wire    pf_x_s_stream2_U_pf_done;
wire   [7:0] pf_x_s_stream_U_data_out;
wire    pf_x_s_stream_U_data_out_vld;
wire    pf_x_s_stream_U_pf_ready;
wire    pf_x_s_stream_U_pf_done;
wire   [63:0] pf_x_stream2_U_data_out;
wire    pf_x_stream2_U_data_out_vld;
wire    pf_x_stream2_U_pf_ready;
wire    pf_x_stream2_U_pf_done;
wire   [63:0] pf_x_stream_U_data_out;
wire    pf_x_stream_U_data_out_vld;
wire    pf_x_stream_U_pf_ready;
wire    pf_x_stream_U_pf_done;
wire   [7:0] pf_z_s_stream_U_data_out;
wire    pf_z_s_stream_U_data_out_vld;
wire    pf_z_s_stream_U_pf_ready;
wire    pf_z_s_stream_U_pf_done;
wire   [63:0] pf_z_stream_U_data_out;
wire    pf_z_stream_U_data_out_vld;
wire    pf_z_stream_U_pf_ready;
wire    pf_z_stream_U_pf_done;
wire    pf_data_in_last;
reg    ap_condition_frp_pvb_no_fwd_prs;
reg    ap_condition_frp_pvb_no_bkwd_prs;
reg    ap_condition_frp_pvb_pf_start;
reg    ap_frp_vld_in;
reg    frp_pipeline_valid_U_exitcond;
reg    pf_B_s_stream_U_data_in_vld;
wire   [7:0] pf_B_s_stream_U_frpsig_data_in;
wire    pf_sync_continue;
reg    pf_all_done;
reg    pf_B_stream_U_data_in_vld;
reg    pf_C_s_stream_U_data_in_vld;
wire   [7:0] pf_C_s_stream_U_frpsig_data_in;
reg    pf_C_stream_U_data_in_vld;
reg    pf_x_s_stream2_U_data_in_vld;
reg    pf_x_s_stream_U_data_in_vld;
reg    pf_x_stream2_U_data_in_vld;
reg    pf_x_stream_U_data_in_vld;
reg    pf_z_s_stream_U_data_in_vld;
wire   [7:0] pf_z_s_stream_U_frpsig_data_in;
reg    pf_z_stream_U_data_in_vld;
wire    regslice_both_silu_stream_U_apdone_blk;
wire   [63:0] silu_stream_TDATA_int_regslice;
wire    silu_stream_TVALID_int_regslice;
reg    silu_stream_TREADY_int_regslice;
wire    regslice_both_silu_stream_U_ack_in;
wire    regslice_both_silu_s_stream_U_apdone_blk;
wire   [7:0] silu_s_stream_TDATA_int_regslice;
wire    silu_s_stream_TVALID_int_regslice;
reg    silu_s_stream_TREADY_int_regslice;
wire    regslice_both_silu_s_stream_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_CS_fsm = 1'd1;
//#0 ap_done_reg = 1'b0;
//#0 pf_all_done = 1'b0;
end

SILU_DEMUX_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(pf_all_done),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(pf_all_done),
    .ap_continue(ap_continue)
);

SILU_DEMUX_frp_pipeline_valid #(
    .PipelineLatency( 3 ),
    .PipelineII( 1 ),
    .CeilLog2Stages( 2 ),
    .ExitLatency( 0 ))
frp_pipeline_valid_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .valid_in(ap_frp_vld_in),
    .exitcond(frp_pipeline_valid_U_exitcond),
    .valid_out(frp_pipeline_valid_U_valid_out),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

SILU_DEMUX_frp_fifoout #(
    .BlockingType( 1 ),
    .PipeLatency( 3 ),
    .PipelineII( 1 ),
    .DataWidth( 8 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 2 ),
    .CeilLog2FDepth( 2 ),
    .PfAllDoneEnable( 2 ))
pf_B_s_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pf_B_s_stream_U_frpsig_data_in),
    .data_out(pf_B_s_stream_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(pf_B_s_stream_U_data_in_vld),
    .data_out_vld(pf_B_s_stream_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_B_s_stream_U_pf_ready),
    .pf_done(pf_B_s_stream_U_pf_done),
    .data_out_read(B_s_stream_TREADY),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

SILU_DEMUX_frp_fifoout #(
    .BlockingType( 1 ),
    .PipeLatency( 3 ),
    .PipelineII( 1 ),
    .DataWidth( 64 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 2 ),
    .CeilLog2FDepth( 2 ),
    .PfAllDoneEnable( 2 ))
pf_B_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(silu_stream_read_reg_279),
    .data_out(pf_B_stream_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(pf_B_stream_U_data_in_vld),
    .data_out_vld(pf_B_stream_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_B_stream_U_pf_ready),
    .pf_done(pf_B_stream_U_pf_done),
    .data_out_read(B_stream_TREADY),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

SILU_DEMUX_frp_fifoout #(
    .BlockingType( 1 ),
    .PipeLatency( 3 ),
    .PipelineII( 1 ),
    .DataWidth( 8 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 2 ),
    .CeilLog2FDepth( 2 ),
    .PfAllDoneEnable( 2 ))
pf_C_s_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pf_C_s_stream_U_frpsig_data_in),
    .data_out(pf_C_s_stream_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(pf_C_s_stream_U_data_in_vld),
    .data_out_vld(pf_C_s_stream_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_C_s_stream_U_pf_ready),
    .pf_done(pf_C_s_stream_U_pf_done),
    .data_out_read(C_s_stream_TREADY),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

SILU_DEMUX_frp_fifoout #(
    .BlockingType( 1 ),
    .PipeLatency( 3 ),
    .PipelineII( 1 ),
    .DataWidth( 64 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 2 ),
    .CeilLog2FDepth( 2 ),
    .PfAllDoneEnable( 2 ))
pf_C_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(silu_stream_read_reg_279),
    .data_out(pf_C_stream_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(pf_C_stream_U_data_in_vld),
    .data_out_vld(pf_C_stream_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_C_stream_U_pf_ready),
    .pf_done(pf_C_stream_U_pf_done),
    .data_out_read(C_stream_TREADY),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

SILU_DEMUX_frp_fifoout #(
    .BlockingType( 1 ),
    .PipeLatency( 3 ),
    .PipelineII( 1 ),
    .DataWidth( 8 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 2 ),
    .CeilLog2FDepth( 2 ),
    .PfAllDoneEnable( 2 ))
pf_x_s_stream2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(zext_ln92_fu_234_p1),
    .data_out(pf_x_s_stream2_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(pf_x_s_stream2_U_data_in_vld),
    .data_out_vld(pf_x_s_stream2_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_x_s_stream2_U_pf_ready),
    .pf_done(pf_x_s_stream2_U_pf_done),
    .data_out_read(x_s_stream2_TREADY),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

SILU_DEMUX_frp_fifoout #(
    .BlockingType( 1 ),
    .PipeLatency( 3 ),
    .PipelineII( 1 ),
    .DataWidth( 8 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 2 ),
    .CeilLog2FDepth( 2 ),
    .PfAllDoneEnable( 2 ))
pf_x_s_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(zext_ln92_fu_234_p1),
    .data_out(pf_x_s_stream_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(pf_x_s_stream_U_data_in_vld),
    .data_out_vld(pf_x_s_stream_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_x_s_stream_U_pf_ready),
    .pf_done(pf_x_s_stream_U_pf_done),
    .data_out_read(x_s_stream_TREADY),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

SILU_DEMUX_frp_fifoout #(
    .BlockingType( 1 ),
    .PipeLatency( 3 ),
    .PipelineII( 1 ),
    .DataWidth( 64 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 2 ),
    .CeilLog2FDepth( 2 ),
    .PfAllDoneEnable( 2 ))
pf_x_stream2_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(silu_stream_read_reg_279),
    .data_out(pf_x_stream2_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(pf_x_stream2_U_data_in_vld),
    .data_out_vld(pf_x_stream2_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_x_stream2_U_pf_ready),
    .pf_done(pf_x_stream2_U_pf_done),
    .data_out_read(x_stream2_TREADY),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

SILU_DEMUX_frp_fifoout #(
    .BlockingType( 1 ),
    .PipeLatency( 3 ),
    .PipelineII( 1 ),
    .DataWidth( 64 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 2 ),
    .CeilLog2FDepth( 2 ),
    .PfAllDoneEnable( 2 ))
pf_x_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(silu_stream_read_reg_279),
    .data_out(pf_x_stream_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(pf_x_stream_U_data_in_vld),
    .data_out_vld(pf_x_stream_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_x_stream_U_pf_ready),
    .pf_done(pf_x_stream_U_pf_done),
    .data_out_read(x_stream_TREADY),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

SILU_DEMUX_frp_fifoout #(
    .BlockingType( 1 ),
    .PipeLatency( 3 ),
    .PipelineII( 1 ),
    .DataWidth( 8 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 2 ),
    .CeilLog2FDepth( 2 ),
    .PfAllDoneEnable( 2 ))
pf_z_s_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pf_z_s_stream_U_frpsig_data_in),
    .data_out(pf_z_s_stream_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(pf_z_s_stream_U_data_in_vld),
    .data_out_vld(pf_z_s_stream_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_z_s_stream_U_pf_ready),
    .pf_done(pf_z_s_stream_U_pf_done),
    .data_out_read(z_s_stream_TREADY),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

SILU_DEMUX_frp_fifoout #(
    .BlockingType( 1 ),
    .PipeLatency( 3 ),
    .PipelineII( 1 ),
    .DataWidth( 64 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 2 ),
    .CeilLog2FDepth( 2 ),
    .PfAllDoneEnable( 2 ))
pf_z_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(silu_stream_read_reg_279),
    .data_out(pf_z_stream_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(pf_z_stream_U_data_in_vld),
    .data_out_vld(pf_z_stream_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(pf_sync_continue),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_z_stream_U_pf_ready),
    .pf_done(pf_z_stream_U_pf_done),
    .data_out_read(z_stream_TREADY),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

SILU_DEMUX_regslice_both #(
    .DataWidth( 64 ))
regslice_both_silu_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(silu_stream_TDATA),
    .vld_in(silu_stream_TVALID),
    .ack_in(regslice_both_silu_stream_U_ack_in),
    .data_out(silu_stream_TDATA_int_regslice),
    .vld_out(silu_stream_TVALID_int_regslice),
    .ack_out(silu_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_silu_stream_U_apdone_blk)
);

SILU_DEMUX_regslice_both #(
    .DataWidth( 8 ))
regslice_both_silu_s_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(silu_s_stream_TDATA),
    .vld_in(silu_s_stream_TVALID),
    .ack_in(regslice_both_silu_s_stream_U_ack_in),
    .data_out(silu_s_stream_TDATA_int_regslice),
    .vld_out(silu_s_stream_TVALID_int_regslice),
    .ack_out(silu_s_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_silu_s_stream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        pf_all_done <= 1'b0;
    end else begin
        pf_all_done <= (pf_z_stream_U_pf_done & pf_z_s_stream_U_pf_done & pf_x_stream_U_pf_done & pf_x_stream2_U_pf_done & pf_x_s_stream_U_pf_done & pf_x_s_stream2_U_pf_done & pf_C_stream_U_pf_done & pf_C_s_stream_U_pf_done & pf_B_stream_U_pf_done & pf_B_s_stream_U_pf_done);
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd0] == 1'b1) & ((icmp_ln78_fu_184_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ct_fu_84 <= ct_2_fu_178_p2;
    end else if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ct_fu_84 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln82_reg_296_pp0_iter1_reg <= icmp_ln82_reg_296;
        icmp_ln86_reg_300_pp0_iter1_reg <= icmp_ln86_reg_300;
        trunc_ln78_reg_275_pp0_iter1_reg <= trunc_ln78_reg_275;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln78_fu_184_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln82_reg_296 <= icmp_ln82_fu_204_p2;
        silu_s_stream_read_reg_288 <= silu_s_stream_TDATA_int_regslice;
        silu_stream_read_reg_279 <= silu_stream_TDATA_int_regslice;
        trunc_ln78_reg_275 <= trunc_ln78_fu_190_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln78_fu_184_p2 == 1'd0) & (icmp_ln82_fu_204_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln86_reg_300 <= icmp_ln86_fu_220_p2;
    end
end

always @ (*) begin
    if ((pf_B_s_stream_U_data_out_vld == 1'b1)) begin
        B_s_stream_TVALID = 1'b1;
    end else begin
        B_s_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((pf_B_stream_U_data_out_vld == 1'b1)) begin
        B_stream_TVALID = 1'b1;
    end else begin
        B_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((pf_C_s_stream_U_data_out_vld == 1'b1)) begin
        C_s_stream_TVALID = 1'b1;
    end else begin
        C_s_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((pf_C_stream_U_data_out_vld == 1'b1)) begin
        C_stream_TVALID = 1'b1;
    end else begin
        C_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd0] == 1'b1) & ((icmp_ln78_fu_184_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int_frp = 1'b1;
    end else begin
        ap_done_int_frp = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1)) begin
        ap_enable_reg_pp0_iter1 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter1 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[2'd2] == 1'b1)) begin
        ap_enable_reg_pp0_iter2 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_condition_frp_pvb_pf_start) & (1'b1 == ap_condition_frp_pvb_no_bkwd_prs) & (1'b1 == ap_condition_frp_pvb_no_fwd_prs))) begin
        ap_frp_vld_in = 1'b1;
    end else begin
        ap_frp_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd0] == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ct_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_ct_1 = ct_fu_84;
    end
end

always @ (*) begin
    if (((icmp_ln78_fu_184_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        frp_pipeline_valid_U_exitcond = 1'b1;
    end else begin
        frp_pipeline_valid_U_exitcond = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((icmp_ln82_reg_296 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        pf_B_s_stream_U_data_in_vld = 1'b1;
    end else begin
        pf_B_s_stream_U_data_in_vld = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((icmp_ln82_reg_296 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        pf_B_stream_U_data_in_vld = 1'b1;
    end else begin
        pf_B_stream_U_data_in_vld = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op69_write_state2 == 1'b1)))) begin
        pf_C_s_stream_U_data_in_vld = 1'b1;
    end else begin
        pf_C_s_stream_U_data_in_vld = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op66_write_state2 == 1'b1)))) begin
        pf_C_stream_U_data_in_vld = 1'b1;
    end else begin
        pf_C_stream_U_data_in_vld = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((ap_predicate_op61_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        pf_x_s_stream2_U_data_in_vld = 1'b1;
    end else begin
        pf_x_s_stream2_U_data_in_vld = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((ap_predicate_op59_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        pf_x_s_stream_U_data_in_vld = 1'b1;
    end else begin
        pf_x_s_stream_U_data_in_vld = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((ap_predicate_op60_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        pf_x_stream2_U_data_in_vld = 1'b1;
    end else begin
        pf_x_stream2_U_data_in_vld = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((ap_predicate_op56_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        pf_x_stream_U_data_in_vld = 1'b1;
    end else begin
        pf_x_stream_U_data_in_vld = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((ap_predicate_op65_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        pf_z_s_stream_U_data_in_vld = 1'b1;
    end else begin
        pf_z_s_stream_U_data_in_vld = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((ap_predicate_op62_write_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        pf_z_stream_U_data_in_vld = 1'b1;
    end else begin
        pf_z_stream_U_data_in_vld = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd0] == 1'b1) & ((icmp_ln78_fu_184_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        silu_s_stream_TREADY_int_regslice = 1'b1;
    end else begin
        silu_s_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd0] == 1'b1) & ((icmp_ln78_fu_184_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        silu_stream_TREADY_int_regslice = 1'b1;
    end else begin
        silu_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((pf_x_s_stream2_U_data_out_vld == 1'b1)) begin
        x_s_stream2_TVALID = 1'b1;
    end else begin
        x_s_stream2_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((pf_x_s_stream_U_data_out_vld == 1'b1)) begin
        x_s_stream_TVALID = 1'b1;
    end else begin
        x_s_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((pf_x_stream2_U_data_out_vld == 1'b1)) begin
        x_stream2_TVALID = 1'b1;
    end else begin
        x_stream2_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((pf_x_stream_U_data_out_vld == 1'b1)) begin
        x_stream_TVALID = 1'b1;
    end else begin
        x_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((pf_z_s_stream_U_data_out_vld == 1'b1)) begin
        z_s_stream_TVALID = 1'b1;
    end else begin
        z_s_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((pf_z_stream_U_data_out_vld == 1'b1)) begin
        z_stream_TVALID = 1'b1;
    end else begin
        z_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_s_stream_TDATA = pf_B_s_stream_U_data_out;

assign B_s_stream_TDATA_blk_n = 1'b1;

assign B_stream_TDATA = pf_B_stream_U_data_out;

assign B_stream_TDATA_blk_n = 1'b1;

assign C_s_stream_TDATA = pf_C_s_stream_U_data_out;

assign C_s_stream_TDATA_blk_n = 1'b1;

assign C_stream_TDATA = pf_C_stream_U_data_out;

assign C_stream_TDATA_blk_n = 1'b1;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = 1'b0;

assign ap_block_pp0_stage0_01001 = 1'b0;

assign ap_block_pp0_stage0_11001 = 1'b0;

assign ap_block_pp0_stage0_subdone = 1'b0;

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | ((icmp_ln78_fu_184_p2 == 1'd0) & (1'b1 == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((regslice_both_z_s_stream_U_apdone_blk == 1'b1) | (regslice_both_z_stream_U_apdone_blk == 1'b1) | (regslice_both_C_s_stream_U_apdone_blk == 1'b1) | (regslice_both_C_stream_U_apdone_blk == 1'b1) | (regslice_both_B_s_stream_U_apdone_blk == 1'b1) | (regslice_both_B_stream_U_apdone_blk == 1'b1) | (regslice_both_x_s_stream2_U_apdone_blk == 1'b1) | (regslice_both_x_stream2_U_apdone_blk == 1'b1) | (regslice_both_x_s_stream_U_apdone_blk == 1'b1) | (regslice_both_x_stream_U_apdone_blk == 1'b1) | ((ap_predicate_op65_write_state2 == 1'b1) & (1'b1 == 1'b0)) | ((ap_predicate_op62_write_state2 == 1'b1) & (1'b1 == 1'b0)) | ((ap_predicate_op61_write_state2 == 1'b1) & (1'b1 == 1'b0)) | ((ap_predicate_op60_write_state2 == 1'b1) & (1'b1 == 1'b0)) | ((ap_predicate_op59_write_state2 == 1'b1) & (1'b1 == 1'b0)) | ((ap_predicate_op56_write_state2 == 1'b1) & (1'b1 == 1'b0)) | ((1'b1 == 1'b0) & (ap_predicate_op69_write_state2 == 1'b1)) | ((1'b1 == 1'b0) & (ap_predicate_op66_write_state2 == 1'b1)) | ((icmp_ln82_reg_296 == 1'd1) & (1'b1 == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (((1'b1 == 1'b0) & (icmp_ln82_reg_296_pp0_iter1_reg == 1'd1)) | ((1'b1 == 1'b0) & (ap_predicate_op83_write_state3 == 1'b1)) | ((1'b1 == 1'b0) & (ap_predicate_op82_write_state3 == 1'b1)) | ((1'b1 == 1'b0) & (ap_predicate_op80_write_state3 == 1'b1)) | ((1'b1 == 1'b0) & (ap_predicate_op79_write_state3 == 1'b1)) | ((1'b1 == 1'b0) & (ap_predicate_op77_write_state3 == 1'b1)) | ((1'b1 == 1'b0) & (ap_predicate_op76_write_state3 == 1'b1)) | ((1'b1 == 1'b0) & (ap_predicate_op75_write_state3 == 1'b1)) | ((1'b1 == 1'b0) & (ap_predicate_op74_write_state3 == 1'b1)));
end

always @ (*) begin
    ap_condition_frp_pvb_no_bkwd_prs = ((pf_z_stream_U_pf_ready == 1'b1) & (pf_z_s_stream_U_pf_ready == 1'b1) & (pf_x_stream_U_pf_ready == 1'b1) & (pf_x_stream2_U_pf_ready == 1'b1) & (pf_x_s_stream_U_pf_ready == 1'b1) & (pf_x_s_stream2_U_pf_ready == 1'b1) & (pf_C_stream_U_pf_ready == 1'b1) & (pf_C_s_stream_U_pf_ready == 1'b1) & (pf_B_stream_U_pf_ready == 1'b1) & (pf_B_s_stream_U_pf_ready == 1'b1));
end

always @ (*) begin
    ap_condition_frp_pvb_no_fwd_prs = ~(((silu_s_stream_TVALID_int_regslice == 1'b0) & (icmp_ln78_fu_184_p2 == 1'd0)) | ((silu_stream_TVALID_int_regslice == 1'b0) & (icmp_ln78_fu_184_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_frp_pvb_pf_start = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op56_write_state2 = ((trunc_ln78_reg_275 == 1'd0) & (icmp_ln86_reg_300 == 1'd0) & (icmp_ln82_reg_296 == 1'd0));
end

always @ (*) begin
    ap_predicate_op59_write_state2 = ((trunc_ln78_reg_275 == 1'd0) & (icmp_ln86_reg_300 == 1'd0) & (icmp_ln82_reg_296 == 1'd0));
end

always @ (*) begin
    ap_predicate_op60_write_state2 = ((trunc_ln78_reg_275 == 1'd0) & (icmp_ln86_reg_300 == 1'd0) & (icmp_ln82_reg_296 == 1'd0));
end

always @ (*) begin
    ap_predicate_op61_write_state2 = ((trunc_ln78_reg_275 == 1'd0) & (icmp_ln86_reg_300 == 1'd0) & (icmp_ln82_reg_296 == 1'd0));
end

always @ (*) begin
    ap_predicate_op62_write_state2 = ((trunc_ln78_reg_275 == 1'd1) & (icmp_ln86_reg_300 == 1'd0) & (icmp_ln82_reg_296 == 1'd0));
end

always @ (*) begin
    ap_predicate_op65_write_state2 = ((trunc_ln78_reg_275 == 1'd1) & (icmp_ln86_reg_300 == 1'd0) & (icmp_ln82_reg_296 == 1'd0));
end

always @ (*) begin
    ap_predicate_op66_write_state2 = ((icmp_ln86_reg_300 == 1'd1) & (icmp_ln82_reg_296 == 1'd0));
end

always @ (*) begin
    ap_predicate_op69_write_state2 = ((icmp_ln86_reg_300 == 1'd1) & (icmp_ln82_reg_296 == 1'd0));
end

always @ (*) begin
    ap_predicate_op74_write_state3 = ((trunc_ln78_reg_275_pp0_iter1_reg == 1'd0) & (icmp_ln86_reg_300_pp0_iter1_reg == 1'd0) & (icmp_ln82_reg_296_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op75_write_state3 = ((trunc_ln78_reg_275_pp0_iter1_reg == 1'd0) & (icmp_ln86_reg_300_pp0_iter1_reg == 1'd0) & (icmp_ln82_reg_296_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op76_write_state3 = ((trunc_ln78_reg_275_pp0_iter1_reg == 1'd0) & (icmp_ln86_reg_300_pp0_iter1_reg == 1'd0) & (icmp_ln82_reg_296_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op77_write_state3 = ((trunc_ln78_reg_275_pp0_iter1_reg == 1'd0) & (icmp_ln86_reg_300_pp0_iter1_reg == 1'd0) & (icmp_ln82_reg_296_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op79_write_state3 = ((trunc_ln78_reg_275_pp0_iter1_reg == 1'd1) & (icmp_ln86_reg_300_pp0_iter1_reg == 1'd0) & (icmp_ln82_reg_296_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op80_write_state3 = ((trunc_ln78_reg_275_pp0_iter1_reg == 1'd1) & (icmp_ln86_reg_300_pp0_iter1_reg == 1'd0) & (icmp_ln82_reg_296_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op82_write_state3 = ((icmp_ln86_reg_300_pp0_iter1_reg == 1'd1) & (icmp_ln82_reg_296_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op83_write_state3 = ((icmp_ln86_reg_300_pp0_iter1_reg == 1'd1) & (icmp_ln82_reg_296_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ct_2_fu_178_p2 = (ap_sig_allocacmp_ct_1 + 11'd1);

assign icmp_ln78_fu_184_p2 = ((ap_sig_allocacmp_ct_1 == 11'd1312) ? 1'b1 : 1'b0);

assign icmp_ln82_fu_204_p2 = ((tmp_fu_194_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_220_p2 = ((tmp_1_fu_210_p4 == 6'd0) ? 1'b1 : 1'b0);

assign pf_B_s_stream_U_frpsig_data_in = trunc_ln84_fu_256_p1;

assign pf_C_s_stream_U_frpsig_data_in = trunc_ln88_fu_248_p1;

assign pf_data_in_last = ap_done_int_frp;

assign pf_sync_continue = (pf_all_done & ap_continue_int);

assign pf_z_s_stream_U_frpsig_data_in = trunc_ln98_fu_240_p1;

assign regslice_both_B_s_stream_U_apdone_blk = 1'b0;

assign regslice_both_B_stream_U_apdone_blk = 1'b0;

assign regslice_both_C_s_stream_U_apdone_blk = 1'b0;

assign regslice_both_C_stream_U_apdone_blk = 1'b0;

assign regslice_both_x_s_stream2_U_apdone_blk = 1'b0;

assign regslice_both_x_s_stream_U_apdone_blk = 1'b0;

assign regslice_both_x_stream2_U_apdone_blk = 1'b0;

assign regslice_both_x_stream_U_apdone_blk = 1'b0;

assign regslice_both_z_s_stream_U_apdone_blk = 1'b0;

assign regslice_both_z_stream_U_apdone_blk = 1'b0;

assign silu_s_stream_TDATA_blk_n = 1'b1;

assign silu_s_stream_TREADY = regslice_both_silu_s_stream_U_ack_in;

assign silu_stream_TDATA_blk_n = 1'b1;

assign silu_stream_TREADY = regslice_both_silu_stream_U_ack_in;

assign tmp_1_fu_210_p4 = {{ap_sig_allocacmp_ct_1[10:5]}};

assign tmp_fu_194_p4 = {{ap_sig_allocacmp_ct_1[10:4]}};

assign trunc_ln78_fu_190_p1 = ap_sig_allocacmp_ct_1[0:0];

assign trunc_ln84_fu_256_p1 = silu_s_stream_read_reg_288[3:0];

assign trunc_ln88_fu_248_p1 = silu_s_stream_read_reg_288[3:0];

assign trunc_ln92_fu_231_p1 = silu_s_stream_read_reg_288[3:0];

assign trunc_ln98_fu_240_p1 = silu_s_stream_read_reg_288[3:0];

assign x_s_stream2_TDATA = pf_x_s_stream2_U_data_out;

assign x_s_stream2_TDATA_blk_n = 1'b1;

assign x_s_stream_TDATA = pf_x_s_stream_U_data_out;

assign x_s_stream_TDATA_blk_n = 1'b1;

assign x_stream2_TDATA = pf_x_stream2_U_data_out;

assign x_stream2_TDATA_blk_n = 1'b1;

assign x_stream_TDATA = pf_x_stream_U_data_out;

assign x_stream_TDATA_blk_n = 1'b1;

assign z_s_stream_TDATA = pf_z_s_stream_U_data_out;

assign z_s_stream_TDATA_blk_n = 1'b1;

assign z_stream_TDATA = pf_z_stream_U_data_out;

assign z_stream_TDATA_blk_n = 1'b1;

assign zext_ln92_fu_234_p1 = trunc_ln92_fu_231_p1;

endmodule //SILU_DEMUX
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

module SILU_DEMUX_flow_control_loop_pipe(
        ap_clk,
        ap_rst,
        ap_start,
        ap_ready,
        ap_done,
        ap_continue,
        ap_start_int,
        ap_ready_int,
        ap_done_int,
        ap_continue_int,
        ap_loop_init,
        ap_loop_exit_ready,
        ap_loop_exit_done
);

input   ap_clk;
input   ap_rst;

//Block level handshake with outside loop
input   ap_start;
output  ap_ready;
output  ap_done;
input   ap_continue;

//Block level handshake with loop body
output  ap_start_int;
input   ap_ready_int;
input   ap_done_int;
output  ap_continue_int;

//Init live in variables
output   ap_loop_init;
reg ap_loop_init;

//Exit signal from loop body
input   ap_loop_exit_ready;
input   ap_loop_exit_done;

// power-on initialization
initial begin
//#0 ap_loop_init = 1'b1;
end

assign ap_start_int = ap_start;

assign ap_continue_int = ap_continue;

assign ap_done = ap_loop_exit_done;

assign ap_ready = ap_loop_exit_ready;

//ap_loop_init is valid for the first II
//of the first loop run so as to enable
//the init block ops which are pushed into
//the first state of the pipeline region
always @ (posedge ap_clk)
begin
    if (ap_rst == 1'b1) begin
        ap_loop_init <= 1'b1;
    end else if(ap_loop_exit_ready == 1'b1) begin
        ap_loop_init <= 1'b1;
    end else if(ap_ready_int == 1'b1) begin
        ap_loop_init <= 1'b0;
    end
end

endmodule
        
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

(* keep_hierarchy = "yes" *)
module SILU_DEMUX_frp_fifoout
  (
   ap_clk,
   ap_rst,
   data_in,
   data_in_vld,
   data_in_last,

   data_out,
   data_out_vld,

   ap_start,
   data_out_read,

   valid,
   num_valid_datasets,
   pf_ready,
   pf_done,
   empty,
   pf_all_done,
   pf_continue
);
   parameter BlockingType = 1;  // 'frp_fifoout' type parameter: '1' for blocking port(AXIS/FIFO/AP_HS)
                                //                               '0' for non-blocking port(Memory/AP_VLD...)
   parameter PipeLatency = 4;
   parameter PipelineII  = 1;
   parameter DataWidth   = 32;
   parameter NumWrites   = 1;
   parameter CeilLog2Stages  = 2;
   parameter CeilLog2FDepth  = 2;
   parameter PfAllDoneEnable = 2;
   
   localparam NUM_STAGES = (PipeLatency+PipelineII-1) / PipelineII; // Ceil(Latency/II)
   
   function isDefined;
      input val;
      begin
         isDefined = (val === 1'b0 || val === 1'b1);
      end
   endfunction

   input ap_clk;
   input ap_rst;
   input [DataWidth-1:0] data_in;
   input ap_start;
   input [PipeLatency-1:0] valid;
   input               data_in_vld, data_in_last;
   input [CeilLog2Stages:0] num_valid_datasets;
   input data_out_read;
   input pf_all_done;
   input pf_continue;

   output reg [DataWidth-1:0] data_out;
   output reg data_out_vld;
   output reg pf_ready;
   output reg pf_done;
   output  empty;

   assign empty=1'b0; // output port empty is not used


   ///////// custom fifo implementation /////////
   localparam FDEPTH = NUM_STAGES * NumWrites + 1;
   reg [DataWidth-1+2:0] fifo [0:FDEPTH-1]; // the "+2" is for extrabits for {data_in_last,data_in_vld}
   reg write_enable, read_enable;
   reg fifo_empty, fifo_full, sel_pipe;
   reg signed [CeilLog2FDepth:0] fifo_rdPtr; // range is -1 to FDEPTH-1
   reg [CeilLog2FDepth:0] fifo_avail;
   reg signed [CeilLog2FDepth+1:0] ready_chk; // max -ve value is (0 - fifo_avail)
   reg                  fail;
   reg     data_out_vld_fifo;

   integer WarningSuppressThreshold;
   initial begin // for co-sim assertion
       fifo_rdPtr = -1;
       fifo_empty = 1'b1;
       fifo_full = 1'b0;
       fail = 0;
//       if(!$value$plusargs("warning_suppress_threshold=%0d", WarningSuppressThreshold)) 
$display("This is SILU_DEMUX.\n");
           WarningSuppressThreshold = 5;
   end

   integer i;
   always @ (posedge ap_clk) begin : fifo_gen
      if (write_enable) begin
         for (i = 0; i < FDEPTH-1; i = i+1)
           fifo[i+1] <= fifo[i];
         fifo[0] <= {data_in_last, data_in_vld, data_in};
      end
   end
   // read ptr should have a positive address (MSB can be ignored)
   wire [DataWidth-1+2:0] fifo_out; // the "+2" is for extrabits for {data_in_last,data_in_vld}
   assign fifo_out = fifo[ fifo_rdPtr[CeilLog2FDepth-1:0] ];

   integer j;
   integer cnt_write_ovfl = 0;
   integer cnt_read_ovfl = 0;
   always @ (posedge ap_clk) begin : fifo_ptr
      if (ap_rst) begin
        fifo_rdPtr <= -1;
        fifo_empty <= 1'b1;
        fifo_full <= 1'b0;
      end
      else begin
          //// // synthesis translate_off
          //// if ($time > 0) begin
          ////    if ( write_enable && fifo_full && cnt_write_ovfl < WarningSuppressThreshold ) begin
          ////        $display("WARNING : fifo write overflow at time %0t", $time); fail=1;
          ////        cnt_write_ovfl = cnt_write_ovfl + 1;
          ////    end
          //// end
          //// // synthesis translate_on
         if (write_enable && !read_enable && !fifo_full) begin
           fifo_rdPtr <= fifo_rdPtr + 1;
           fifo_empty <= 1'b0;
           fifo_full <= (fifo_rdPtr == FDEPTH-2);
         end
         else if (read_enable && !write_enable && !fifo_empty) begin
           fifo_rdPtr <= fifo_rdPtr - 1;
           fifo_empty <= (fifo_rdPtr == 'd0);
           fifo_full <= 1'b0;
         end
      end
   end
   
   ///////// control logic /////////

   reg stalled, must_stall, data_cannot_vld, data_done, data_out_last_reg;
   reg data_out_last, internal_done;
   
    generate
        if(PfAllDoneEnable==2)
            always @(*) begin
                stalled = must_stall;
            end
        else
            always @ (posedge ap_clk) begin : stall_reg
                if (ap_rst) stalled <= 1'b0;
                else stalled <= must_stall;
            end
    endgenerate
   
    generate
        if (BlockingType == 1)
            always @ (*) begin : readen_control_for_blocking
                casex ({data_out_read, data_out_vld_fifo, data_out_last, fifo_empty, stalled})
                  5'b 1_X_X_0_0 : // when consumer reads and fifo is not empty.
                    read_enable = 1'b1;
                  5'b X_0_1_0_0 : // when no data in last and fifo is not empty.
                    read_enable = 1'b1;
                  default:
                    read_enable = 1'b0;
                endcase
            end
        else
            always @ (*) begin : readen_control_for_non_blocking
                casex ({fifo_empty, must_stall})
                  2'b 0_0: 
                    read_enable = 1'b1;
                  default:
                    read_enable = 1'b0;
                endcase
            end
    endgenerate

    generate
        if (BlockingType == 1)
            always @ (*) begin : writen_control_for_blocking
                casex ({ data_out_read, data_in_vld, fifo_empty, data_in_last, stalled })
                    5'b X_X_X_1_1 :
                        write_enable = 1'b1;
                    5'b X_1_X_X_1 :
                        write_enable = 1'b1;

                    5'b X_X_0_1_0 : // last valid, fifo has data
                        write_enable = 1'b1;
                    5'b 0_1_1_1_0 : // last valid, but consumer stalls (data_out_read==0), data_in_valid available
                        write_enable = 1'b1;
                    
                    5'b 0_1_X_X_0 : // data valid, but consumer stalls (data_out_read==0)
                        write_enable = 1'b1;
                    5'b 1_1_1_X_0 : // data valid, consumer ready, fifo is fifo_empty
                        write_enable = 1'b0;
                    5'b 1_1_0_X_0 : // data valid, consumer ready, fifo has data
                        write_enable = 1'b1;
                    default     :
                      write_enable = 1'b0;
                endcase
            end
        else if(BlockingType==0 && PfAllDoneEnable == 2)
            always @ (*) begin : writen_control_for_non_blocking
                casex ({ data_in_vld, fifo_empty, data_in_last, must_stall })
                  4'b 1_0_X_X :
                      write_enable = 1'b1;
                  4'b X_0_1_X :
                      write_enable = 1'b1;
                  4'b X_1_1_1 :
                      write_enable = 1'b1;
                  4'b 1_1_X_1 :
                      write_enable = 1'b1;
                  default     :
                      write_enable = 1'b0;
                endcase
            end
        else
            always @ (*) begin : writen_control_for_non_blocking
                casex ({ data_in_vld, fifo_empty, data_in_last, must_stall })
                  4'b 1_0_X_X :
                      write_enable = 1'b1;
                  4'b X_0_1_X :
                      write_enable = 1'b1;
                  4'b X_1_1_1 :
                      write_enable = 1'b1;
                  default     :
                      write_enable = 1'b0;
                endcase
            end
    endgenerate

    generate
        if (PfAllDoneEnable == 2)
            always @(posedge ap_clk) begin
                if(ap_rst) begin
                    data_cannot_vld<=1'b0;
                    data_out_last_reg<=1'b0;
                end else if(pf_all_done&&pf_continue) begin 
                    if(data_out_vld_fifo&&data_out_read&&data_out_last) data_cannot_vld<=1'b1 & (BlockingType==1);
                    else if(!data_out_vld_fifo&&data_out_last) data_cannot_vld<=1'b1;
                    else data_cannot_vld<=1'b0;

                    if(data_out_vld_fifo&&data_out_read&&data_out_last) data_out_last_reg<=data_out_last&(BlockingType==1);
                    else if(!data_out_vld_fifo&&data_out_last) data_out_last_reg<=data_out_last;
                    else data_out_last_reg<=1'b0;
                end else if(pf_all_done&&!pf_continue) begin 
                    data_cannot_vld<=1'b1;
                    data_out_last_reg<=data_out_last_reg;
                end else if(!pf_all_done) begin
                    if(data_out_last_reg) begin
                        data_cannot_vld<=1'b1;
                        data_out_last_reg<=data_out_last_reg;
                    end else if(data_out_vld_fifo&&!data_out_read) begin
                        data_cannot_vld<=1'b0;
                        data_out_last_reg<=1'b0;
                    end else if(data_out_vld_fifo&&data_out_read||!data_out_vld_fifo)begin
                        if(!data_out_last) data_cannot_vld<=1'b0;
                        else data_cannot_vld<=1'b1;
                        if(data_out_last) data_out_last_reg<=data_out_last;
                        else data_out_last_reg<=1'b0;
                    end
                end

                if(ap_rst) data_done<=1'b0;
                else if(must_stall) data_done <= data_done;
                else if ( (data_out_vld&&data_out_read||!data_out_vld_fifo&&data_out_last)||
                          (!pf_all_done||pf_all_done&&pf_continue) ) data_done <= 1'b1 & (BlockingType==1);
                else data_done <= 1'b0;
            end
    endgenerate

    generate
        if (PfAllDoneEnable == 2)
            always @ (*) begin : control
                ///////// internal signals /////////
                // data_out_vld is AMBA compliant (independent of data_out_read)
                sel_pipe    = fifo_empty;
                {data_out_last, data_out_vld_fifo, data_out} = sel_pipe ? {data_in_last, data_in_vld, data_in} : fifo_out;
                //for blocking mode, next transaction first data is already in SILU_DEMUX fifo. They can do handshake when
                //last transaction ap_done/ap_continue does handshake
                //for non_blocking mode, next transaction first data is not in SILU_DEMUX fifo
                data_out_vld = data_out_vld_fifo & (!data_cannot_vld || pf_continue&&pf_all_done&&data_done);

                if(pf_continue&&pf_all_done) begin
                    if(data_out_vld_fifo&&!data_out_read) must_stall=1'b1;
                    else if(data_out_vld_fifo&&data_out_read) must_stall=1'b1 & (BlockingType==0);
                    else must_stall=1'b0;

                    if(data_out_vld_fifo&&data_out_read) pf_done=data_out_last & (BlockingType==1);
                    else if(!data_out_vld_fifo&&data_out_last) pf_done=data_out_last;
                    else pf_done=1'b0;
                end else if(pf_all_done && !pf_continue) begin 
                    must_stall=1;
                    pf_done=data_out_last_reg;
                end else if(!pf_all_done) begin
                    if(data_out_last_reg) begin
                         must_stall=1'b1;
                         pf_done=data_out_last_reg;
                    end else if(data_out_vld_fifo&&!data_out_read) begin
                        must_stall=1'b1;
                        pf_done=1'b0;
                    end else if(data_out_vld_fifo&&data_out_read||!data_out_vld_fifo)begin
                        must_stall = 1'b0;
                        if(data_out_last) pf_done=data_out_last;
                        else pf_done=1'b0;
                    end else begin
                        must_stall = 1'b0;
                        pf_done = 1'b0;
                    end
                end else begin
                    must_stall = 1'b0;
                    pf_done = 1'b0;
                end

                ///////// outputs /////////
                fifo_avail = (FDEPTH - fifo_rdPtr - 1);
                // available has to be atleast one (or NumWrites) more than
                // valid transactions being processed in the pipeline. Then this
                // fifo buffer can accept the "valid" data in the following cycle.
                // pf_ready = (fifo_avail - (num_valid_datasets * NumWrites) >=
                // NumWrites);
                // above expr simplified for hardware
                                ready_chk = (NumWrites - fifo_avail + (num_valid_datasets * NumWrites));
                  pf_ready = ready_chk < 0;
            end // block: control
        else if (PfAllDoneEnable == 1)
            always @ (*) begin : control
               ///////// internal signals /////////
               // data_out_vld is AMBA compliant (independent of data_out_read)
               sel_pipe    = fifo_empty;
               {data_out_last, data_out_vld_fifo, data_out} = sel_pipe ? {data_in_last, data_in_vld, data_in} : fifo_out;
               data_out_vld = data_out_vld_fifo & !stalled;

               casex ({data_out_vld_fifo, data_out_last, pf_continue&pf_all_done, stalled, data_out_read})
                 5'b 0_0_X_0_X : {internal_done, must_stall} = 2'b 0_0;
                 5'b X_X_0_1_X : {internal_done, must_stall} = 2'b 1_1;  // when 'stalled', should wait until 'pf_continue'.
                 5'b X_X_1_1_X : {internal_done, must_stall} = 2'b 1_0;  // when 'pf_continue' arrived, 'stalled' register is de-asserted first.
                                                                         // This is to avoid the combinational loop on 'pf_done'.
                                                                         // loop: pf_done->ap_done->done_sync->ap_continue->pf_continue->pf_done.
                 5'b 0_1_0_0_X : {internal_done, must_stall} = 2'b 1_1;  // When there is only 'data_out_last', no need to wait 'data_out_read'.
                 5'b 0_1_1_0_X : {internal_done, must_stall} = 2'b 1_0;

                 5'b 1_1_X_X_0 : {internal_done, must_stall} = 2'b 0_0;  // when there are 'data_out_vld' and 'data_out_last' in the same cycle, 'internal_done' has to handshake with 'data_out_read'.
                 5'b 1_1_1_0_1 : {internal_done, must_stall} = 2'b 1_0;
                 5'b 1_1_0_0_1 : {internal_done, must_stall} = 2'b 1_1;
                 default       : {internal_done, must_stall} = 2'b 0_0;
               endcase
               pf_done = internal_done&!(pf_continue&pf_all_done);

               ///////// outputs /////////
               fifo_avail = (FDEPTH - fifo_rdPtr - 1);
               // available has to be atleast one (or NumWrites) more than
               // valid transactions being processed in the pipeline. Then this
               // fifo buffer can accept the "valid" data in the following cycle.
               // pf_ready = (fifo_avail - (num_valid_datasets * NumWrites) >=
               // NumWrites);
               // above expr simplified for hardware

                               ready_chk = (NumWrites - fifo_avail + (num_valid_datasets * NumWrites));
                 pf_ready = ready_chk < 0;
            end // block: control
        else
            always @ (*) begin : control
     
                 ///////// internal signals /////////
     
                 // data_out_vld is AMBA compliant (independent of data_out_read)
                 sel_pipe    = fifo_empty;
                 {data_out_last, data_out_vld_fifo, data_out} = sel_pipe ? {data_in_last, data_in_vld, data_in} : fifo_out;
                 data_out_vld = data_out_vld_fifo & !stalled;
     
                 casex ({data_out_vld_fifo, data_out_last, pf_continue, stalled, data_out_read})
                   5'b 0_0_X_0_X : {internal_done, must_stall} = 2'b 0_0;
                   5'b X_X_0_1_X : {internal_done, must_stall} = 2'b 1_1;  // when 'stalled', should wait until 'pf_continue'.
                   5'b X_X_1_1_X : {internal_done, must_stall} = 2'b 1_0;  // when 'pf_continue' arrived, 'stalled' register is de-asserted first.
                                                                           // This is to avoid the combinational loop on 'pf_done'.
                                                                           // loop: pf_done->ap_done->done_sync->ap_continue->pf_continue->pf_done.
                   5'b 0_1_0_0_X : {internal_done, must_stall} = 2'b 1_1;  // When there is only 'data_out_last', no need to wait 'data_out_read'.
                   5'b 0_1_1_0_X : {internal_done, must_stall} = 2'b 1_0;

                   5'b 1_1_X_X_0 : {internal_done, must_stall} = 2'b 0_0;  // when there are 'data_out_vld' and 'data_out_last' in the same cycle, 'internal_done' has to handshake with 'data_out_read'.
                   5'b 1_1_1_0_1 : {internal_done, must_stall} = 2'b 1_0;
                   5'b 1_1_0_0_1 : {internal_done, must_stall} = 2'b 1_1;
                   default       : {internal_done, must_stall} = 2'b 0_0;
                 endcase
                 pf_done = internal_done;

                 ///////// outputs /////////
                 fifo_avail = (FDEPTH - fifo_rdPtr - 1);
                 // available has to be atleast one (or NumWrites) more than
                 // valid transactions being processed in the pipeline. Then this
                 // fifo buffer can accept the "valid" data in the following cycle.
                 // pf_ready = (fifo_avail - (num_valid_datasets * NumWrites) >=
                 // NumWrites);
                 // above expr simplified for hardware

                             ready_chk = (NumWrites - fifo_avail + (num_valid_datasets * NumWrites));
                     pf_ready = ready_chk < 0;
            end // block: control
       endgenerate
endmodule // pipeline_fifo
    
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

(* keep_hierarchy = "yes" *)
module SILU_DEMUX_frp_pipeline_valid
  (ap_clk,
   ap_rst,
   valid_in,
   exitcond,

   valid_out,
   num_valid_datasets);

   parameter PipelineLatency =  4;
   parameter PipelineII      =  1;
   parameter ExitLatency = -1;
   parameter CeilLog2Stages   = 2;
   
   localparam NUM_STAGES = (PipelineLatency+PipelineII-1) / PipelineII; // Ceil(Latency/II)
   
   function isDefined;
      input val;
      begin
         isDefined = (val === 1'b0 || val === 1'b1);
      end
   endfunction

   input ap_clk;
   input ap_rst;
   input valid_in;
   input exitcond;
   
   
   output [PipelineLatency-1:0] valid_out;
   output [CeilLog2Stages:0] num_valid_datasets;
   reg signed [CeilLog2Stages+1:0] nvd_reg;
   assign num_valid_datasets=nvd_reg;

   reg fail;
   reg [PipelineLatency-2:0] v2;

   integer WarningSuppressThreshold;
   initial begin // for co-sim assertion
       v2 = 0;
       fail = 0;
       nvd_reg = 0;
//       if(!$value$plusargs("warning_suppress_threshold=%0d", WarningSuppressThreshold)) 
$display("This is SILU_DEMUX.\n");
           WarningSuppressThreshold = 5;
   end

   reg [PipelineLatency-1:0] valid_out_tmp;

   assign valid_out=valid_out_tmp;
   ///////// pipeline data valid (flushable impl) /////////
   reg [PipelineLatency-2:0] v1;
   genvar i;
   generate for (i = 0; i < PipelineLatency-1; i = i+1)
     always @ (posedge ap_clk) begin
        if (ap_rst)
          v2[i] <= 0;
        else begin
           v1[i] = (i == 0) ? valid_in : v2[i-1];
           v2[i] <= (ExitLatency==i) ? (!exitcond & v1[i]) : v1[i];
        end
     end
   endgenerate

   integer j;
   ///// // synthesis translate_off
   ///// integer cnt_nvd_ovfl_warning[PipelineLatency-1:0];
   ///// // synthesis translate_on
   always @(*) begin

       valid_out_tmp = {v2, valid_in};

       //// // synthesis translate_off
       //// if ($time > 0) begin
       ////    for (j = 1; j < PipelineLatency; j = j+1) begin : loop_block
       ////       if ( !(!valid_out_tmp[j] || nvd_reg <= NUM_STAGES) && 
       ////            cnt_nvd_ovfl_warning[j] < WarningSuppressThreshold ) begin
       ////          $display("WARNING : nvd_reg overflow. valid_out_tmp[%0d]=%b nvd=%0d nstg=%0d (at time %0t)",
       ////                 j, valid_out_tmp[j], nvd_reg, NUM_STAGES, $time);
       ////          fail=1; 
       ////          cnt_nvd_ovfl_warning[j] = cnt_nvd_ovfl_warning[j] + 1;
       ////          disable loop_block;
       ////       end
       ////    end // for (j = 1; j < PipelineLatency; j = j+1)
       //// end // if ($time > 0)
       //// // synthesis translate_on
   end

   wire   valid_disable;
   assign valid_disable = (ExitLatency == -1) ? 1'b0 : (valid_out_tmp[ExitLatency] & exitcond);
   
   // Count the num valid_out_tmp datasets in the pipe stages other than the
   // first. We do NOT count valid_out_tmp[0], otherwise it will be a
   // combination loop: nvd -> pfifo.ap_ready -> valid_in -> valid_out_tmp[0] -> nvd
   reg signed [2:0] incr;
   integer cnt_nvd_out_range = 0;
   always @ (posedge ap_clk) begin
      if (ap_rst)
         nvd_reg <= 0;
      else begin
         casex ({valid_out_tmp[0], valid_out_tmp[PipelineLatency-1], valid_disable})
           3'b100:  incr =  1;
           3'b111:  incr = -1;
           3'b001:  incr = -1;
           3'b010:  incr = -1;
           3'b011:  incr = -2;
           default: incr =  0;
         endcase
         /// // synthesis translate_off
         /// if (!(0 <=($signed(nvd_reg)+incr)<=NUM_STAGES) && cnt_nvd_out_range<WarningSuppressThreshold) begin
         ///       $display("WARNING: nvd_reg out of range. incr=%d nvd=%0d nstg=%0d (at time %0t)",
         ///              incr, nvd_reg, NUM_STAGES, $time);
         ///    fail=1;
         ///    cnt_nvd_out_range = cnt_nvd_out_range+1;
         /// end
         /// // synthesis translate_on
         nvd_reg <= nvd_reg + incr;
      end
   end

   //// // synthesis translate_off
   //// integer cnt_valid_out_tmp[PipelineLatency-1:0];
   //// integer stg, stgc;
   //// always @ (posedge ap_clk) begin
   ////    stg = 0;
   ////    stgc = 0;
   ////    for (j = 0; j < PipelineLatency; j = j+1) begin : block_stgc
   ////       stgc = stgc + valid_out_tmp[j];
   ////       if (stg == PipelineII-1) begin
   ////          if ( !(stgc <= 1) && cnt_valid_out_tmp[j]<WarningSuppressThreshold) begin
   ////             $display("WARNING: valid_out_tmp=%b. %0d bits set in one pipe-stage ending at bit-%0d (at time %0t)",
   ////                    valid_out_tmp, stgc, j, $time);
   ////             fail=1; 
   ////             cnt_valid_out_tmp[j] = cnt_valid_out_tmp[j] + 1;
   ////             disable block_stgc;
   ////          end
   ////          stgc = 0;
   ////          stg  = 0;
   ////       end else begin
   ////          stg = stg + 1;
   ////       end
   ////    end // for (j = 0; j < PipelineLatency; j = j+1)
   //// end // always @ (posedge ap_clk)
   //// // synthesis translate_on

endmodule // pipeline_valid
    
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1ns/1ps

module SILU_DEMUX_regslice_both
#(parameter 
    DataWidth=32
)(
    input ap_clk ,
    input ap_rst,

    input [DataWidth-1:0] data_in , 
    input vld_in , 
    output ack_in ,
    output [DataWidth-1:0] data_out, 
    output vld_out,
    input ack_out,
    output apdone_blk
);
 

reg   [1:0] B_V_data_1_state;
wire   [DataWidth-1:0] B_V_data_1_data_in;
reg   [DataWidth-1:0] B_V_data_1_data_out;
wire    B_V_data_1_vld_reg;
wire    B_V_data_1_vld_in;
wire    B_V_data_1_vld_out;
reg   [DataWidth-1:0] B_V_data_1_payload_A;
reg   [DataWidth-1:0] B_V_data_1_payload_B;
reg    B_V_data_1_sel_rd;
reg    B_V_data_1_sel_wr;
wire    B_V_data_1_sel;
wire    B_V_data_1_load_A;
wire    B_V_data_1_load_B;
wire    B_V_data_1_state_cmp_full;
wire    B_V_data_1_ack_in;
wire    B_V_data_1_ack_out;

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_out) & (1'b1 == B_V_data_1_ack_out))) begin
            B_V_data_1_sel_rd <= ~B_V_data_1_sel_rd;
        end else begin
            B_V_data_1_sel_rd <= B_V_data_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_in))) begin
            B_V_data_1_sel_wr <= ~B_V_data_1_sel_wr;
        end else begin
            B_V_data_1_sel_wr <= B_V_data_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_state <= 2'd0;
    end else begin
        if ((((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) | ((2'd2 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd2;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out)) | ((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd1;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b1 == B_V_data_1_ack_out)) | (~((1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)) & ~((1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) & (2'd3 == B_V_data_1_state)) | ((2'd2 == B_V_data_1_state) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd3;
        end else begin
            B_V_data_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_A)) begin
        B_V_data_1_payload_A <= B_V_data_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_B)) begin
        B_V_data_1_payload_B <= B_V_data_1_data_in;
    end
end

always @ (*) begin
    if ((1'b1 == B_V_data_1_sel)) begin
        B_V_data_1_data_out = B_V_data_1_payload_B;
    end else begin
        B_V_data_1_data_out = B_V_data_1_payload_A;
    end
end

assign B_V_data_1_ack_in = B_V_data_1_state[1'd1];
assign B_V_data_1_load_A = (~B_V_data_1_sel_wr & B_V_data_1_state_cmp_full);
assign B_V_data_1_load_B = (B_V_data_1_state_cmp_full & B_V_data_1_sel_wr);
assign B_V_data_1_sel = B_V_data_1_sel_rd;
assign B_V_data_1_state_cmp_full = ((B_V_data_1_state != 2'd1) ? 1'b1 : 1'b0);
assign B_V_data_1_vld_out = B_V_data_1_state[1'd0];

assign ack_in = B_V_data_1_ack_in;
assign B_V_data_1_data_in = data_in;
assign B_V_data_1_vld_in = vld_in;

assign vld_out = B_V_data_1_vld_out;
assign data_out = B_V_data_1_data_out;
assign B_V_data_1_ack_out = ack_out;

assign apdone_blk = ((B_V_data_1_state == 2'd3 && ack_out == 1'b0) | (B_V_data_1_state == 2'd1));

endmodule // both

module SILU_DEMUX_regslice_both_w1
#(parameter 
    DataWidth=1
)(
    input ap_clk ,
    input ap_rst,

    input data_in , 
    input vld_in , 
    output ack_in ,
    output data_out, 
    output vld_out,
    input ack_out,
    output apdone_blk
);

reg     [1:0] B_V_data_1_state;
wire    B_V_data_1_data_in;
reg     B_V_data_1_data_out;
wire    B_V_data_1_vld_reg;
wire    B_V_data_1_vld_in;
wire    B_V_data_1_vld_out;
reg     B_V_data_1_payload_A;
reg     B_V_data_1_payload_B;
reg     B_V_data_1_sel_rd;
reg     B_V_data_1_sel_wr;
wire    B_V_data_1_sel;
wire    B_V_data_1_load_A;
wire    B_V_data_1_load_B;
wire    B_V_data_1_state_cmp_full;
wire    B_V_data_1_ack_in;
wire    B_V_data_1_ack_out;

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_out) & (1'b1 == B_V_data_1_ack_out))) begin
            B_V_data_1_sel_rd <= ~B_V_data_1_sel_rd;
        end else begin
            B_V_data_1_sel_rd <= B_V_data_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_in))) begin
            B_V_data_1_sel_wr <= ~B_V_data_1_sel_wr;
        end else begin
            B_V_data_1_sel_wr <= B_V_data_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_state <= 2'd0;
    end else begin
        if ((((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) | ((2'd2 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd2;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out)) | ((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd1;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b1 == B_V_data_1_ack_out)) | (~((1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)) & ~((1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) & (2'd3 == B_V_data_1_state)) | ((2'd2 == B_V_data_1_state) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd3;
        end else begin
            B_V_data_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_A)) begin
        B_V_data_1_payload_A <= B_V_data_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_B)) begin
        B_V_data_1_payload_B <= B_V_data_1_data_in;
    end
end

always @ (*) begin
    if ((1'b1 == B_V_data_1_sel)) begin
        B_V_data_1_data_out = B_V_data_1_payload_B;
    end else begin
        B_V_data_1_data_out = B_V_data_1_payload_A;
    end
end

assign B_V_data_1_ack_in = B_V_data_1_state[1'd1];
assign B_V_data_1_load_A = (~B_V_data_1_sel_wr & B_V_data_1_state_cmp_full);
assign B_V_data_1_load_B = (B_V_data_1_state_cmp_full & B_V_data_1_sel_wr);
assign B_V_data_1_sel = B_V_data_1_sel_rd;
assign B_V_data_1_state_cmp_full = ((B_V_data_1_state != 2'd1) ? 1'b1 : 1'b0);
assign B_V_data_1_vld_out = B_V_data_1_state[1'd0];

assign ack_in = B_V_data_1_ack_in;
assign B_V_data_1_data_in = data_in;
assign B_V_data_1_vld_in = vld_in;

assign vld_out = B_V_data_1_vld_out;
assign data_out = B_V_data_1_data_out;
assign B_V_data_1_ack_out = ack_out;

assign apdone_blk = ((B_V_data_1_state == 2'd3 && ack_out == 1'b0) | (B_V_data_1_state == 2'd1));

endmodule // both


