/* verilator lint_off PINMISSING */
/* verilator lint_off CASEINCOMPLETE */
/* verilator lint_off COMBDLY */
/* verilator lint_off CASEX */
/* verilator lint_off CASEOVERLAP */
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="RESIDUAL_RESIDUAL,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvc1902-vsva2197-2MP-e-S,HLS_INPUT_CLOCK=2.500000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.361000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1430,HLS_SYN_LUT=692,HLS_VERSION=2022_2}" *)

module RESIDUAL (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        l_begin,
        l_close,
        x_stream_TDATA,
        x_stream_TVALID,
        x_stream_TREADY,
        res_i_stream_TDATA,
        res_i_stream_TVALID,
        res_i_stream_TREADY,
        res_o_stream_TDATA,
        res_o_stream_TVALID,
        res_o_stream_TREADY,
        y_stream_TDATA,
        y_stream_TVALID,
        y_stream_TREADY
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] l_begin;
input  [31:0] l_close;
input  [255:0] x_stream_TDATA;
input   x_stream_TVALID;
output   x_stream_TREADY;
input  [255:0] res_i_stream_TDATA;
input   res_i_stream_TVALID;
output   res_i_stream_TREADY;
output  [255:0] res_o_stream_TDATA;
output   res_o_stream_TVALID;
input   res_o_stream_TREADY;
output  [255:0] y_stream_TDATA;
output   y_stream_TVALID;
input   y_stream_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [8:0] x_buf_V_address0;
reg    x_buf_V_ce0;
wire   [255:0] x_buf_V_q0;
reg   [8:0] x_buf_V_address1;
reg    x_buf_V_ce1;
reg    x_buf_V_we1;
reg   [255:0] x_buf_V_d1;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_start;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_done;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_idle;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_ready;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_stream_TREADY;
wire   [8:0] grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_buf_V_address1;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_buf_V_ce1;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_buf_V_we1;
wire   [255:0] grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_buf_V_d1;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_start;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_done;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_idle;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_ready;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_res_o_stream_TREADY;
wire   [8:0] grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_x_buf_V_address0;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_x_buf_V_ce0;
wire   [255:0] grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_res_o_stream_TDATA;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_res_o_stream_TVALID;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_start;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_done;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_idle;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_ready;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_y_stream_TREADY;
wire   [8:0] grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_x_buf_V_address0;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_x_buf_V_ce0;
wire   [255:0] grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_y_stream_TDATA;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_y_stream_TVALID;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_start;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_done;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_idle;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_ready;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_res_i_stream_TREADY;
wire   [8:0] grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_address0;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_ce0;
wire   [8:0] grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_address1;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_ce1;
wire    grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_we1;
wire   [255:0] grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_d1;
reg    grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_start_reg;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln78_fu_118_p2;
wire    ap_CS_fsm_state6;
reg    grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [31:0] l_fu_62;
wire   [31:0] l_3_fu_123_p2;
reg    ap_block_state1;
wire    ap_CS_fsm_state11;
wire    regslice_both_res_o_stream_U_apdone_blk;
wire    regslice_both_y_stream_U_apdone_blk;
reg    ap_block_state11;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    regslice_both_x_stream_U_apdone_blk;
wire   [255:0] x_stream_TDATA_int_regslice;
wire    x_stream_TVALID_int_regslice;
reg    x_stream_TREADY_int_regslice;
wire    regslice_both_x_stream_U_ack_in;
wire    regslice_both_res_i_stream_U_apdone_blk;
wire   [255:0] res_i_stream_TDATA_int_regslice;
wire    res_i_stream_TVALID_int_regslice;
reg    res_i_stream_TREADY_int_regslice;
wire    regslice_both_res_i_stream_U_ack_in;
wire    res_o_stream_TREADY_int_regslice;
wire    regslice_both_res_o_stream_U_vld_out;
wire    y_stream_TREADY_int_regslice;
wire    regslice_both_y_stream_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_done_reg = 1'b0;
//#0 ap_CS_fsm = 11'd1;
//#0 grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_start_reg = 1'b0;
//#0 grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_start_reg = 1'b0;
//#0 grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_start_reg = 1'b0;
//#0 grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_start_reg = 1'b0;
end

RESIDUAL_x_buf_V_RAM_2P_URAM_1R1W #(
    .DataWidth( 256 ),
    .AddressRange( 320 ),
    .AddressWidth( 9 ))
x_buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_buf_V_address0),
    .ce0(x_buf_V_ce0),
    .q0(x_buf_V_q0),
    .address1(x_buf_V_address1),
    .ce1(x_buf_V_ce1),
    .we1(x_buf_V_we1),
    .d1(x_buf_V_d1)
);

RESIDUAL_RESIDUAL_Pipeline_VITIS_LOOP_65_2 grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_start),
    .ap_done(grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_done),
    .ap_idle(grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_idle),
    .ap_ready(grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_ready),
    .x_stream_TVALID(x_stream_TVALID_int_regslice),
    .x_stream_TDATA(x_stream_TDATA_int_regslice),
    .x_stream_TREADY(grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_stream_TREADY),
    .x_buf_V_address1(grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_buf_V_address1),
    .x_buf_V_ce1(grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_buf_V_ce1),
    .x_buf_V_we1(grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_buf_V_we1),
    .x_buf_V_d1(grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_buf_V_d1)
);

RESIDUAL_RESIDUAL_Pipeline_VITIS_LOOP_81_7 grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_start),
    .ap_done(grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_done),
    .ap_idle(grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_idle),
    .ap_ready(grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_ready),
    .res_o_stream_TREADY(grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_res_o_stream_TREADY),
    .x_buf_V_address0(grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_x_buf_V_address0),
    .x_buf_V_ce0(grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_x_buf_V_ce0),
    .x_buf_V_q0(x_buf_V_q0),
    .res_o_stream_TDATA(grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_res_o_stream_TDATA),
    .res_o_stream_TVALID(grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_res_o_stream_TVALID)
);

RESIDUAL_RESIDUAL_Pipeline_VITIS_LOOP_125_19 grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_start),
    .ap_done(grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_done),
    .ap_idle(grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_idle),
    .ap_ready(grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_ready),
    .y_stream_TREADY(grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_y_stream_TREADY),
    .x_buf_V_address0(grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_x_buf_V_address0),
    .x_buf_V_ce0(grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_x_buf_V_ce0),
    .x_buf_V_q0(x_buf_V_q0),
    .y_stream_TDATA(grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_y_stream_TDATA),
    .y_stream_TVALID(grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_y_stream_TVALID)
);

RESIDUAL_RESIDUAL_Pipeline_VITIS_LOOP_94_10 grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_start),
    .ap_done(grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_done),
    .ap_idle(grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_idle),
    .ap_ready(grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_ready),
    .res_i_stream_TVALID(res_i_stream_TVALID_int_regslice),
    .res_i_stream_TDATA(res_i_stream_TDATA_int_regslice),
    .res_i_stream_TREADY(grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_res_i_stream_TREADY),
    .x_buf_V_address0(grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_address0),
    .x_buf_V_ce0(grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_ce0),
    .x_buf_V_q0(x_buf_V_q0),
    .x_buf_V_address1(grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_address1),
    .x_buf_V_ce1(grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_ce1),
    .x_buf_V_we1(grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_we1),
    .x_buf_V_d1(grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_d1)
);

RESIDUAL_regslice_both #(
    .DataWidth( 256 ))
regslice_both_x_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(x_stream_TDATA),
    .vld_in(x_stream_TVALID),
    .ack_in(regslice_both_x_stream_U_ack_in),
    .data_out(x_stream_TDATA_int_regslice),
    .vld_out(x_stream_TVALID_int_regslice),
    .ack_out(x_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_x_stream_U_apdone_blk)
);

RESIDUAL_regslice_both #(
    .DataWidth( 256 ))
regslice_both_res_i_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(res_i_stream_TDATA),
    .vld_in(res_i_stream_TVALID),
    .ack_in(regslice_both_res_i_stream_U_ack_in),
    .data_out(res_i_stream_TDATA_int_regslice),
    .vld_out(res_i_stream_TVALID_int_regslice),
    .ack_out(res_i_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_res_i_stream_U_apdone_blk)
);

RESIDUAL_regslice_both #(
    .DataWidth( 256 ))
regslice_both_res_o_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_res_o_stream_TDATA),
    .vld_in(grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_res_o_stream_TVALID),
    .ack_in(res_o_stream_TREADY_int_regslice),
    .data_out(res_o_stream_TDATA),
    .vld_out(regslice_both_res_o_stream_U_vld_out),
    .ack_out(res_o_stream_TREADY),
    .apdone_blk(regslice_both_res_o_stream_U_apdone_blk)
);

RESIDUAL_regslice_both #(
    .DataWidth( 256 ))
regslice_both_y_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_y_stream_TDATA),
    .vld_in(grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_y_stream_TVALID),
    .ack_in(y_stream_TREADY_int_regslice),
    .data_out(y_stream_TDATA),
    .vld_out(regslice_both_y_stream_U_vld_out),
    .ack_out(y_stream_TREADY),
    .apdone_blk(regslice_both_y_stream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((regslice_both_y_stream_U_apdone_blk == 1'b1) | (regslice_both_res_o_stream_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state11))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln78_fu_118_p2 == 1'd0))) begin
            grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_start_reg <= 1'b1;
        end else if ((grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_ready == 1'b1)) begin
            grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_start_reg <= 1'b1;
        end else if ((grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_ready == 1'b1)) begin
            grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln78_fu_118_p2 == 1'd1))) begin
            grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_start_reg <= 1'b1;
        end else if ((grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_ready == 1'b1)) begin
            grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_start_reg <= 1'b1;
        end else if ((grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_ready == 1'b1)) begin
            grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        l_fu_62 <= l_begin;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln78_fu_118_p2 == 1'd1))) begin
        l_fu_62 <= l_3_fu_123_p2;
    end
end

always @ (*) begin
    if ((grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_y_stream_U_apdone_blk == 1'b1) | (regslice_both_res_o_stream_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((regslice_both_y_stream_U_apdone_blk == 1'b1) | (regslice_both_res_o_stream_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((regslice_both_y_stream_U_apdone_blk == 1'b1) | (regslice_both_res_o_stream_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        res_i_stream_TREADY_int_regslice = grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_res_i_stream_TREADY;
    end else begin
        res_i_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        x_buf_V_address0 = grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_buf_V_address0 = grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_x_buf_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        x_buf_V_address0 = grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_x_buf_V_address0;
    end else begin
        x_buf_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        x_buf_V_address1 = grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_buf_V_address1 = grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_buf_V_address1;
    end else begin
        x_buf_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        x_buf_V_ce0 = grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        x_buf_V_ce0 = grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_x_buf_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        x_buf_V_ce0 = grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_x_buf_V_ce0;
    end else begin
        x_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        x_buf_V_ce1 = grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_buf_V_ce1 = grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_buf_V_ce1;
    end else begin
        x_buf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        x_buf_V_d1 = grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_buf_V_d1 = grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_buf_V_d1;
    end else begin
        x_buf_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        x_buf_V_we1 = grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_x_buf_V_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_buf_V_we1 = grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_buf_V_we1;
    end else begin
        x_buf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_stream_TREADY_int_regslice = grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_x_stream_TREADY;
    end else begin
        x_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln78_fu_118_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if ((~((regslice_both_y_stream_U_apdone_blk == 1'b1) | (regslice_both_res_o_stream_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state11 = ((regslice_both_y_stream_U_apdone_blk == 1'b1) | (regslice_both_res_o_stream_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_start = grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_ap_start_reg;

assign grp_RESIDUAL_Pipeline_VITIS_LOOP_125_19_fu_96_y_stream_TREADY = (y_stream_TREADY_int_regslice & ap_CS_fsm_state10);

assign grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_start = grp_RESIDUAL_Pipeline_VITIS_LOOP_65_2_fu_82_ap_start_reg;

assign grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_start = grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_ap_start_reg;

assign grp_RESIDUAL_Pipeline_VITIS_LOOP_81_7_fu_89_res_o_stream_TREADY = (res_o_stream_TREADY_int_regslice & ap_CS_fsm_state6);

assign grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_start = grp_RESIDUAL_Pipeline_VITIS_LOOP_94_10_fu_103_ap_start_reg;

assign icmp_ln78_fu_118_p2 = (($signed(l_fu_62) < $signed(l_close)) ? 1'b1 : 1'b0);

assign l_3_fu_123_p2 = (l_fu_62 + 32'd1);

assign res_i_stream_TREADY = regslice_both_res_i_stream_U_ack_in;

assign res_o_stream_TVALID = regslice_both_res_o_stream_U_vld_out;

assign x_stream_TREADY = regslice_both_x_stream_U_ack_in;

assign y_stream_TVALID = regslice_both_y_stream_U_vld_out;

endmodule //RESIDUAL
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

module RESIDUAL_flow_control_loop_pipe_sequential_init(
        ap_clk,
        ap_rst,
        ap_start,
        ap_ready,
        ap_done,
        ap_start_int,
        ap_ready_int,
        ap_done_int,
        ap_continue_int,
        ap_loop_init,
        ap_loop_exit_ready,
        ap_loop_exit_done
);

input   ap_clk;
input   ap_rst;

//Block level handshake with outside loop
input   ap_start;
output  ap_ready;
output  ap_done;

//Block level handshake with loop body
output  ap_start_int;
input   ap_ready_int;
input   ap_done_int;
output  ap_continue_int;

//Init live in variables
output   ap_loop_init;
wire     ap_loop_init;
reg ap_loop_init_int;
reg ap_done;
reg ap_done_cache;

//Exit signal from loop body
input   ap_loop_exit_ready;
input   ap_loop_exit_done;

// power-on initialization
initial begin
//#0 ap_loop_init_int = 1'b1;
//#0 ap_done_cache = 1'b0;
end

assign ap_start_int = ap_start;

assign ap_continue_int = 1'b1;

assign ap_ready = ap_loop_exit_ready;

//ap_loop_init is valid for the first II
//of the first loop run so as to enable
//the init block ops which are pushed into
//the first state of the pipeline region
always @ (posedge ap_clk)
begin
    if (ap_rst == 1'b1) begin
        ap_loop_init_int <= 1'b1;
    end else if(ap_loop_exit_done == 1'b1) begin
        ap_loop_init_int <= 1'b1;
    end else if(ap_ready_int == 1'b1) begin
        ap_loop_init_int <= 1'b0;
    end
end

assign ap_loop_init = ap_loop_init_int & ap_start;

// if no ap_continue port and current module is not RESIDUAL module, 
// ap_done handshakes with ap_start. Internally, flow control sends out 
// ap_conintue_int = 1'b1 so the ap_done_int is asserted high for 1 clock cycle.
// ap_done_cache is used to record ap_done_int, and de-assert if ap_start_int
// is asserted, so DUT can start the next run
always @(posedge ap_clk)
begin
    if (ap_rst == 1'b1) begin
        ap_done_cache <= 1'b0;
    end else if (ap_done_int == 1'b1) begin
        ap_done_cache <= 1'b1;
    end else if (ap_start_int == 1'b1) begin
        ap_done_cache <= 1'b0;
    end
end

// if no ap_continue port and current module is not RESIDUAL module, ap_done handshakes with ap_start
always @(*)
begin
    if ((ap_done_int == 1'b1) || ((ap_done_cache == 1'b1) && (ap_start_int == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

endmodule
        
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1ns/1ps

module RESIDUAL_regslice_both
#(parameter 
    DataWidth=32
)(
    input ap_clk ,
    input ap_rst,

    input [DataWidth-1:0] data_in , 
    input vld_in , 
    output ack_in ,
    output [DataWidth-1:0] data_out, 
    output vld_out,
    input ack_out,
    output apdone_blk
);
 

reg   [1:0] B_V_data_1_state;
wire   [DataWidth-1:0] B_V_data_1_data_in;
reg   [DataWidth-1:0] B_V_data_1_data_out;
wire    B_V_data_1_vld_reg;
wire    B_V_data_1_vld_in;
wire    B_V_data_1_vld_out;
reg   [DataWidth-1:0] B_V_data_1_payload_A;
reg   [DataWidth-1:0] B_V_data_1_payload_B;
reg    B_V_data_1_sel_rd;
reg    B_V_data_1_sel_wr;
wire    B_V_data_1_sel;
wire    B_V_data_1_load_A;
wire    B_V_data_1_load_B;
wire    B_V_data_1_state_cmp_full;
wire    B_V_data_1_ack_in;
wire    B_V_data_1_ack_out;

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_out) & (1'b1 == B_V_data_1_ack_out))) begin
            B_V_data_1_sel_rd <= ~B_V_data_1_sel_rd;
        end else begin
            B_V_data_1_sel_rd <= B_V_data_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_in))) begin
            B_V_data_1_sel_wr <= ~B_V_data_1_sel_wr;
        end else begin
            B_V_data_1_sel_wr <= B_V_data_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_state <= 2'd0;
    end else begin
        if ((((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) | ((2'd2 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd2;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out)) | ((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd1;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b1 == B_V_data_1_ack_out)) | (~((1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)) & ~((1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) & (2'd3 == B_V_data_1_state)) | ((2'd2 == B_V_data_1_state) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd3;
        end else begin
            B_V_data_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_A)) begin
        B_V_data_1_payload_A <= B_V_data_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_B)) begin
        B_V_data_1_payload_B <= B_V_data_1_data_in;
    end
end

always @ (*) begin
    if ((1'b1 == B_V_data_1_sel)) begin
        B_V_data_1_data_out = B_V_data_1_payload_B;
    end else begin
        B_V_data_1_data_out = B_V_data_1_payload_A;
    end
end

assign B_V_data_1_ack_in = B_V_data_1_state[1'd1];
assign B_V_data_1_load_A = (~B_V_data_1_sel_wr & B_V_data_1_state_cmp_full);
assign B_V_data_1_load_B = (B_V_data_1_state_cmp_full & B_V_data_1_sel_wr);
assign B_V_data_1_sel = B_V_data_1_sel_rd;
assign B_V_data_1_state_cmp_full = ((B_V_data_1_state != 2'd1) ? 1'b1 : 1'b0);
assign B_V_data_1_vld_out = B_V_data_1_state[1'd0];

assign ack_in = B_V_data_1_ack_in;
assign B_V_data_1_data_in = data_in;
assign B_V_data_1_vld_in = vld_in;

assign vld_out = B_V_data_1_vld_out;
assign data_out = B_V_data_1_data_out;
assign B_V_data_1_ack_out = ack_out;

assign apdone_blk = ((B_V_data_1_state == 2'd3 && ack_out == 1'b0) | (B_V_data_1_state == 2'd1));

endmodule // both

module RESIDUAL_regslice_both_w1
#(parameter 
    DataWidth=1
)(
    input ap_clk ,
    input ap_rst,

    input data_in , 
    input vld_in , 
    output ack_in ,
    output data_out, 
    output vld_out,
    input ack_out,
    output apdone_blk
);

reg     [1:0] B_V_data_1_state;
wire    B_V_data_1_data_in;
reg     B_V_data_1_data_out;
wire    B_V_data_1_vld_reg;
wire    B_V_data_1_vld_in;
wire    B_V_data_1_vld_out;
reg     B_V_data_1_payload_A;
reg     B_V_data_1_payload_B;
reg     B_V_data_1_sel_rd;
reg     B_V_data_1_sel_wr;
wire    B_V_data_1_sel;
wire    B_V_data_1_load_A;
wire    B_V_data_1_load_B;
wire    B_V_data_1_state_cmp_full;
wire    B_V_data_1_ack_in;
wire    B_V_data_1_ack_out;

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_out) & (1'b1 == B_V_data_1_ack_out))) begin
            B_V_data_1_sel_rd <= ~B_V_data_1_sel_rd;
        end else begin
            B_V_data_1_sel_rd <= B_V_data_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_in))) begin
            B_V_data_1_sel_wr <= ~B_V_data_1_sel_wr;
        end else begin
            B_V_data_1_sel_wr <= B_V_data_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_state <= 2'd0;
    end else begin
        if ((((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) | ((2'd2 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd2;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out)) | ((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd1;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b1 == B_V_data_1_ack_out)) | (~((1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)) & ~((1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) & (2'd3 == B_V_data_1_state)) | ((2'd2 == B_V_data_1_state) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd3;
        end else begin
            B_V_data_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_A)) begin
        B_V_data_1_payload_A <= B_V_data_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_B)) begin
        B_V_data_1_payload_B <= B_V_data_1_data_in;
    end
end

always @ (*) begin
    if ((1'b1 == B_V_data_1_sel)) begin
        B_V_data_1_data_out = B_V_data_1_payload_B;
    end else begin
        B_V_data_1_data_out = B_V_data_1_payload_A;
    end
end

assign B_V_data_1_ack_in = B_V_data_1_state[1'd1];
assign B_V_data_1_load_A = (~B_V_data_1_sel_wr & B_V_data_1_state_cmp_full);
assign B_V_data_1_load_B = (B_V_data_1_state_cmp_full & B_V_data_1_sel_wr);
assign B_V_data_1_sel = B_V_data_1_sel_rd;
assign B_V_data_1_state_cmp_full = ((B_V_data_1_state != 2'd1) ? 1'b1 : 1'b0);
assign B_V_data_1_vld_out = B_V_data_1_state[1'd0];

assign ack_in = B_V_data_1_ack_in;
assign B_V_data_1_data_in = data_in;
assign B_V_data_1_vld_in = vld_in;

assign vld_out = B_V_data_1_vld_out;
assign data_out = B_V_data_1_data_out;
assign B_V_data_1_ack_out = ack_out;

assign apdone_blk = ((B_V_data_1_state == 2'd3 && ack_out == 1'b0) | (B_V_data_1_state == 2'd1));

endmodule // both


// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module RESIDUAL_RESIDUAL_Pipeline_VITIS_LOOP_125_19 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_stream_TREADY,
        x_buf_V_address0,
        x_buf_V_ce0,
        x_buf_V_q0,
        y_stream_TDATA,
        y_stream_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   y_stream_TREADY;
output  [8:0] x_buf_V_address0;
output   x_buf_V_ce0;
input  [255:0] x_buf_V_q0;
output  [255:0] y_stream_TDATA;
output   y_stream_TVALID;

reg ap_idle;
reg x_buf_V_ce0;
reg y_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln125_fu_85_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    y_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln125_fu_91_p1;
reg   [8:0] ct_2_fu_46;
wire   [8:0] add_ln125_fu_79_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_ct;
reg    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_CS_fsm = 1'd1;
//#0 ap_enable_reg_pp0_iter1 = 1'b0;
//#0 ap_done_reg = 1'b0;
end

RESIDUAL_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln125_fu_85_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ct_2_fu_46 <= add_ln125_fu_79_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ct_2_fu_46 <= 9'd0;
        end
    end
end

always @ (*) begin
    if (((icmp_ln125_fu_85_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ct = 9'd0;
    end else begin
        ap_sig_allocacmp_ct = ct_2_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_V_ce0 = 1'b1;
    end else begin
        x_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_stream_TDATA_blk_n = y_stream_TREADY;
    end else begin
        y_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_stream_TVALID = 1'b1;
    end else begin
        y_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln125_fu_79_p2 = (ap_sig_allocacmp_ct + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((y_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((y_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((y_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (y_stream_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln125_fu_85_p2 = ((ap_sig_allocacmp_ct == 9'd320) ? 1'b1 : 1'b0);

assign x_buf_V_address0 = zext_ln125_fu_91_p1;

assign y_stream_TDATA = x_buf_V_q0;

assign zext_ln125_fu_91_p1 = ap_sig_allocacmp_ct;

endmodule //RESIDUAL_RESIDUAL_Pipeline_VITIS_LOOP_125_19
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module RESIDUAL_RESIDUAL_Pipeline_VITIS_LOOP_65_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_stream_TVALID,
        x_stream_TDATA,
        x_stream_TREADY,
        x_buf_V_address1,
        x_buf_V_ce1,
        x_buf_V_we1,
        x_buf_V_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   x_stream_TVALID;
input  [255:0] x_stream_TDATA;
output   x_stream_TREADY;
output  [8:0] x_buf_V_address1;
output   x_buf_V_ce1;
output   x_buf_V_we1;
output  [255:0] x_buf_V_d1;

reg ap_idle;
reg x_stream_TREADY;
reg x_buf_V_ce1;
reg x_buf_V_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln65_fu_87_p2;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    x_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg   [8:0] ct_2_reg_109;
reg    ap_block_pp0_stage0_11001;
reg   [255:0] x_stream_read_reg_117;
wire   [63:0] zext_ln65_fu_98_p1;
reg   [8:0] ct_fu_46;
wire   [8:0] add_ln65_fu_81_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_ct_2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_CS_fsm = 1'd1;
//#0 ap_enable_reg_pp0_iter1 = 1'b0;
//#0 ap_done_reg = 1'b0;
end

RESIDUAL_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln65_fu_87_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            ct_fu_46 <= add_ln65_fu_81_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ct_fu_46 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ct_2_reg_109 <= ap_sig_allocacmp_ct_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln65_fu_87_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_stream_read_reg_117 <= x_stream_TDATA;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln65_fu_87_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ct_2 = 9'd0;
    end else begin
        ap_sig_allocacmp_ct_2 = ct_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_V_ce1 = 1'b1;
    end else begin
        x_buf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_V_we1 = 1'b1;
    end else begin
        x_buf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln65_fu_87_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_stream_TDATA_blk_n = x_stream_TVALID;
    end else begin
        x_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln65_fu_87_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_stream_TREADY = 1'b1;
    end else begin
        x_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln65_fu_81_p2 = (ap_sig_allocacmp_ct_2 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((icmp_ln65_fu_87_p2 == 1'd0) & (x_stream_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((icmp_ln65_fu_87_p2 == 1'd0) & (x_stream_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln65_fu_87_p2 == 1'd0) & (x_stream_TVALID == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln65_fu_87_p2 = ((ap_sig_allocacmp_ct_2 == 9'd320) ? 1'b1 : 1'b0);

assign x_buf_V_address1 = zext_ln65_fu_98_p1;

assign x_buf_V_d1 = x_stream_read_reg_117;

assign zext_ln65_fu_98_p1 = ct_2_reg_109;

endmodule //RESIDUAL_RESIDUAL_Pipeline_VITIS_LOOP_65_2
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module RESIDUAL_RESIDUAL_Pipeline_VITIS_LOOP_81_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        res_o_stream_TREADY,
        x_buf_V_address0,
        x_buf_V_ce0,
        x_buf_V_q0,
        res_o_stream_TDATA,
        res_o_stream_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   res_o_stream_TREADY;
output  [8:0] x_buf_V_address0;
output   x_buf_V_ce0;
input  [255:0] x_buf_V_q0;
output  [255:0] res_o_stream_TDATA;
output   res_o_stream_TVALID;

reg ap_idle;
reg x_buf_V_ce0;
reg res_o_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln81_fu_85_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    res_o_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln81_fu_91_p1;
reg   [8:0] ct_1_fu_46;
wire   [8:0] add_ln81_fu_79_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_ct;
reg    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_CS_fsm = 1'd1;
//#0 ap_enable_reg_pp0_iter1 = 1'b0;
//#0 ap_done_reg = 1'b0;
end

RESIDUAL_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln81_fu_85_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ct_1_fu_46 <= add_ln81_fu_79_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ct_1_fu_46 <= 9'd0;
        end
    end
end

always @ (*) begin
    if (((icmp_ln81_fu_85_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ct = 9'd0;
    end else begin
        ap_sig_allocacmp_ct = ct_1_fu_46;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_o_stream_TDATA_blk_n = res_o_stream_TREADY;
    end else begin
        res_o_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_o_stream_TVALID = 1'b1;
    end else begin
        res_o_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_V_ce0 = 1'b1;
    end else begin
        x_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln81_fu_79_p2 = (ap_sig_allocacmp_ct + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((res_o_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((res_o_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((res_o_stream_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (res_o_stream_TREADY == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln81_fu_85_p2 = ((ap_sig_allocacmp_ct == 9'd320) ? 1'b1 : 1'b0);

assign res_o_stream_TDATA = x_buf_V_q0;

assign x_buf_V_address0 = zext_ln81_fu_91_p1;

assign zext_ln81_fu_91_p1 = ap_sig_allocacmp_ct;

endmodule //RESIDUAL_RESIDUAL_Pipeline_VITIS_LOOP_81_7
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module RESIDUAL_RESIDUAL_Pipeline_VITIS_LOOP_94_10 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        res_i_stream_TVALID,
        res_i_stream_TDATA,
        res_i_stream_TREADY,
        x_buf_V_address0,
        x_buf_V_ce0,
        x_buf_V_q0,
        x_buf_V_address1,
        x_buf_V_ce1,
        x_buf_V_we1,
        x_buf_V_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   res_i_stream_TVALID;
input  [255:0] res_i_stream_TDATA;
output   res_i_stream_TREADY;
output  [8:0] x_buf_V_address0;
output   x_buf_V_ce0;
input  [255:0] x_buf_V_q0;
output  [8:0] x_buf_V_address1;
output   x_buf_V_ce1;
output   x_buf_V_we1;
output  [255:0] x_buf_V_d1;

reg ap_idle;
reg res_i_stream_TREADY;
reg x_buf_V_ce0;
reg x_buf_V_ce1;
reg x_buf_V_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln94_fu_121_p2;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    res_i_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] trunc_ln102_fu_132_p1;
reg   [31:0] trunc_ln102_reg_341;
reg   [31:0] trunc_ln102_reg_341_pp0_iter1_reg;
reg   [31:0] tmp_reg_346;
reg   [31:0] tmp_reg_346_pp0_iter1_reg;
reg   [31:0] tmp_1_reg_351;
reg   [31:0] tmp_1_reg_351_pp0_iter1_reg;
reg   [31:0] tmp_2_reg_356;
reg   [31:0] tmp_2_reg_356_pp0_iter1_reg;
reg   [31:0] tmp_3_reg_361;
reg   [31:0] tmp_3_reg_361_pp0_iter1_reg;
reg   [31:0] trunc_ln102_6_reg_366;
reg   [31:0] trunc_ln102_6_reg_366_pp0_iter1_reg;
reg   [31:0] trunc_ln102_7_reg_371;
reg   [31:0] trunc_ln102_7_reg_371_pp0_iter1_reg;
reg   [31:0] tmp_s_reg_376;
reg   [31:0] tmp_s_reg_376_pp0_iter1_reg;
reg   [8:0] x_buf_V_addr_reg_381;
reg   [8:0] x_buf_V_addr_reg_381_pp0_iter1_reg;
reg   [8:0] x_buf_V_addr_reg_381_pp0_iter2_reg;
wire   [31:0] trunc_ln110_fu_211_p1;
reg   [31:0] trunc_ln110_reg_387;
reg   [31:0] tmp_4_reg_392;
reg   [31:0] tmp_5_reg_397;
reg   [31:0] tmp_6_reg_402;
reg   [31:0] tmp_7_reg_407;
reg   [31:0] tmp_8_reg_412;
reg   [31:0] tmp_9_reg_417;
reg   [31:0] tmp_10_reg_422;
wire   [31:0] add_ln116_fu_285_p2;
reg   [31:0] add_ln116_reg_427;
wire   [31:0] add_ln116_1_fu_289_p2;
reg   [31:0] add_ln116_1_reg_432;
wire   [31:0] add_ln116_2_fu_293_p2;
reg   [31:0] add_ln116_2_reg_437;
wire   [31:0] add_ln116_3_fu_297_p2;
reg   [31:0] add_ln116_3_reg_442;
wire   [31:0] add_ln116_4_fu_301_p2;
reg   [31:0] add_ln116_4_reg_447;
wire   [31:0] add_ln116_5_fu_305_p2;
reg   [31:0] add_ln116_5_reg_452;
wire   [31:0] add_ln116_6_fu_309_p2;
reg   [31:0] add_ln116_6_reg_457;
wire   [31:0] add_ln116_7_fu_313_p2;
reg   [31:0] add_ln116_7_reg_462;
wire   [63:0] ct_3_cast_fu_127_p1;
reg   [8:0] ct_fu_80;
wire   [8:0] add_ln94_fu_115_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_ct_1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_CS_fsm = 1'd1;
//#0 ap_enable_reg_pp0_iter1 = 1'b0;
//#0 ap_enable_reg_pp0_iter2 = 1'b0;
//#0 ap_enable_reg_pp0_iter3 = 1'b0;
//#0 ap_done_reg = 1'b0;
end

RESIDUAL_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln94_fu_121_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            ct_fu_80 <= add_ln94_fu_115_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ct_fu_80 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln116_1_reg_432 <= add_ln116_1_fu_289_p2;
        add_ln116_2_reg_437 <= add_ln116_2_fu_293_p2;
        add_ln116_3_reg_442 <= add_ln116_3_fu_297_p2;
        add_ln116_4_reg_447 <= add_ln116_4_fu_301_p2;
        add_ln116_5_reg_452 <= add_ln116_5_fu_305_p2;
        add_ln116_6_reg_457 <= add_ln116_6_fu_309_p2;
        add_ln116_7_reg_462 <= add_ln116_7_fu_313_p2;
        add_ln116_reg_427 <= add_ln116_fu_285_p2;
        x_buf_V_addr_reg_381_pp0_iter2_reg <= x_buf_V_addr_reg_381_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        tmp_10_reg_422 <= {{x_buf_V_q0[255:224]}};
        tmp_1_reg_351_pp0_iter1_reg <= tmp_1_reg_351;
        tmp_2_reg_356_pp0_iter1_reg <= tmp_2_reg_356;
        tmp_3_reg_361_pp0_iter1_reg <= tmp_3_reg_361;
        tmp_4_reg_392 <= {{x_buf_V_q0[63:32]}};
        tmp_5_reg_397 <= {{x_buf_V_q0[95:64]}};
        tmp_6_reg_402 <= {{x_buf_V_q0[127:96]}};
        tmp_7_reg_407 <= {{x_buf_V_q0[159:128]}};
        tmp_8_reg_412 <= {{x_buf_V_q0[191:160]}};
        tmp_9_reg_417 <= {{x_buf_V_q0[223:192]}};
        tmp_reg_346_pp0_iter1_reg <= tmp_reg_346;
        tmp_s_reg_376_pp0_iter1_reg <= tmp_s_reg_376;
        trunc_ln102_6_reg_366_pp0_iter1_reg <= trunc_ln102_6_reg_366;
        trunc_ln102_7_reg_371_pp0_iter1_reg <= trunc_ln102_7_reg_371;
        trunc_ln102_reg_341_pp0_iter1_reg <= trunc_ln102_reg_341;
        trunc_ln110_reg_387 <= trunc_ln110_fu_211_p1;
        x_buf_V_addr_reg_381_pp0_iter1_reg <= x_buf_V_addr_reg_381;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln94_fu_121_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_1_reg_351 <= {{res_i_stream_TDATA[127:96]}};
        tmp_2_reg_356 <= {{res_i_stream_TDATA[159:128]}};
        tmp_3_reg_361 <= {{res_i_stream_TDATA[191:160]}};
        tmp_reg_346 <= {{res_i_stream_TDATA[95:64]}};
        tmp_s_reg_376 <= {{res_i_stream_TDATA[63:32]}};
        trunc_ln102_6_reg_366 <= {{res_i_stream_TDATA[223:192]}};
        trunc_ln102_7_reg_371 <= {{res_i_stream_TDATA[255:224]}};
        trunc_ln102_reg_341 <= trunc_ln102_fu_132_p1;
        x_buf_V_addr_reg_381 <= ct_3_cast_fu_127_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln94_fu_121_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ct_1 = 9'd0;
    end else begin
        ap_sig_allocacmp_ct_1 = ct_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln94_fu_121_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_i_stream_TDATA_blk_n = res_i_stream_TVALID;
    end else begin
        res_i_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln94_fu_121_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_i_stream_TREADY = 1'b1;
    end else begin
        res_i_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_buf_V_ce0 = 1'b1;
    end else begin
        x_buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        x_buf_V_ce1 = 1'b1;
    end else begin
        x_buf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        x_buf_V_we1 = 1'b1;
    end else begin
        x_buf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln116_1_fu_289_p2 = (tmp_4_reg_392 + tmp_s_reg_376_pp0_iter1_reg);

assign add_ln116_2_fu_293_p2 = (tmp_5_reg_397 + tmp_reg_346_pp0_iter1_reg);

assign add_ln116_3_fu_297_p2 = (tmp_6_reg_402 + tmp_1_reg_351_pp0_iter1_reg);

assign add_ln116_4_fu_301_p2 = (tmp_7_reg_407 + tmp_2_reg_356_pp0_iter1_reg);

assign add_ln116_5_fu_305_p2 = (tmp_8_reg_412 + tmp_3_reg_361_pp0_iter1_reg);

assign add_ln116_6_fu_309_p2 = (tmp_9_reg_417 + trunc_ln102_6_reg_366_pp0_iter1_reg);

assign add_ln116_7_fu_313_p2 = (tmp_10_reg_422 + trunc_ln102_7_reg_371_pp0_iter1_reg);

assign add_ln116_fu_285_p2 = (trunc_ln110_reg_387 + trunc_ln102_reg_341_pp0_iter1_reg);

assign add_ln94_fu_115_p2 = (ap_sig_allocacmp_ct_1 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((icmp_ln94_fu_121_p2 == 1'd0) & (res_i_stream_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((icmp_ln94_fu_121_p2 == 1'd0) & (res_i_stream_TVALID == 1'b0) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln94_fu_121_p2 == 1'd0) & (res_i_stream_TVALID == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ct_3_cast_fu_127_p1 = ap_sig_allocacmp_ct_1;

assign icmp_ln94_fu_121_p2 = ((ap_sig_allocacmp_ct_1 == 9'd320) ? 1'b1 : 1'b0);

assign trunc_ln102_fu_132_p1 = res_i_stream_TDATA[31:0];

assign trunc_ln110_fu_211_p1 = x_buf_V_q0[31:0];

assign x_buf_V_address0 = ct_3_cast_fu_127_p1;

assign x_buf_V_address1 = x_buf_V_addr_reg_381_pp0_iter2_reg;

assign x_buf_V_d1 = {{{{{{{{add_ln116_7_reg_462}, {add_ln116_6_reg_457}}, {add_ln116_5_reg_452}}, {add_ln116_4_reg_447}}, {add_ln116_3_reg_442}}, {add_ln116_2_reg_437}}, {add_ln116_1_reg_432}}, {add_ln116_reg_427}};

endmodule //RESIDUAL_RESIDUAL_Pipeline_VITIS_LOOP_94_10
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module RESIDUAL_x_buf_V_RAM_2P_URAM_1R1W (
     
    address0, ce0,
    
    q0, 
      
    address1, ce1,
    d1, we1, 
    
     
    reset, clk);

parameter DataWidth = 256;
parameter AddressWidth = 9;
parameter AddressRange = 320;
 
input[AddressWidth-1:0] address0;
input ce0;

output reg[DataWidth-1:0] q0; 
 
input[AddressWidth-1:0] address1;
input ce1;
input[DataWidth-1:0] d1;
input we1; 


input reset;
input clk;

(* ram_style = "hls_ultra" , cascade_height = 1 *)reg [DataWidth-1:0] ram[0:AddressRange-1];


 



always @(posedge clk) 
begin 
    if (ce0) begin
        q0 <= ram[address0];
    end
end 

 
  

always @(posedge clk)  
begin 
    if (ce1) begin
        if (we1) 
            ram[address1] <= d1; 
    end
end 



 
 

endmodule

