/* verilator lint_off PINMISSING */
/* verilator lint_off CASEINCOMPLETE */
/* verilator lint_off COMBDLY */
/* verilator lint_off CASEX */
/* verilator lint_off CASEOVERLAP */
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="UD_UD,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvc1902-vsva2197-2MP-e-S,HLS_INPUT_CLOCK=2.500000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=1.682000,HLS_SYN_LAT=650,HLS_SYN_TPT=651,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=296,HLS_SYN_LUT=1065,HLS_VERSION=2022_2}" *)

module UD (
        l,
        i_stream_TDATA,
        s_stream_TDATA,
        o_stream_TDATA,
        ap_clk,
        ap_rst_n,
        i_stream_TVALID,
        i_stream_TREADY,
        s_stream_TVALID,
        s_stream_TREADY,
        o_stream_TVALID,
        o_stream_TREADY,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] l;
input  [63:0] i_stream_TDATA;
input  [7:0] s_stream_TDATA;
output  [255:0] o_stream_TDATA;
input   ap_clk;
input   ap_rst_n;
input   i_stream_TVALID;
output   i_stream_TREADY;
input   s_stream_TVALID;
output   s_stream_TREADY;
output   o_stream_TVALID;
input   o_stream_TREADY;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire   [255:0] do_uD_U0_o_stream_TDATA;
 reg    ap_rst_n_inv;
wire    do_uD_U0_i_stream_TREADY;
wire    do_uD_U0_s_stream_TREADY;
wire    do_uD_U0_o_stream_TVALID;
wire    do_uD_U0_ap_start;
wire    do_uD_U0_ap_done;
wire    do_uD_U0_ap_ready;
wire    do_uD_U0_ap_idle;
wire    do_uD_U0_ap_continue;

UD_do_uD do_uD_U0(
    .l(l),
    .i_stream_TDATA(i_stream_TDATA),
    .s_stream_TDATA(s_stream_TDATA),
    .o_stream_TDATA(do_uD_U0_o_stream_TDATA),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .l_ap_vld(1'b1),
    .i_stream_TVALID(i_stream_TVALID),
    .i_stream_TREADY(do_uD_U0_i_stream_TREADY),
    .s_stream_TVALID(s_stream_TVALID),
    .s_stream_TREADY(do_uD_U0_s_stream_TREADY),
    .o_stream_TVALID(do_uD_U0_o_stream_TVALID),
    .o_stream_TREADY(o_stream_TREADY),
    .ap_start(do_uD_U0_ap_start),
    .ap_done(do_uD_U0_ap_done),
    .ap_ready(do_uD_U0_ap_ready),
    .ap_idle(do_uD_U0_ap_idle),
    .ap_continue(do_uD_U0_ap_continue)
);

assign ap_done = do_uD_U0_ap_done;

assign ap_idle = do_uD_U0_ap_idle;

assign ap_ready = do_uD_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign do_uD_U0_ap_continue = ap_continue;

assign do_uD_U0_ap_start = ap_start;

assign i_stream_TREADY = do_uD_U0_i_stream_TREADY;

assign o_stream_TDATA = do_uD_U0_o_stream_TDATA;

assign o_stream_TVALID = do_uD_U0_o_stream_TVALID;

assign s_stream_TREADY = do_uD_U0_s_stream_TREADY;

endmodule //UD
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module UD_do_uD (
        l,
        i_stream_TDATA,
        s_stream_TDATA,
        o_stream_TDATA,
        ap_clk,
        ap_rst,
        l_ap_vld,
        i_stream_TVALID,
        i_stream_TREADY,
        s_stream_TVALID,
        s_stream_TREADY,
        o_stream_TVALID,
        o_stream_TREADY,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] l;
input  [63:0] i_stream_TDATA;
input  [7:0] s_stream_TDATA;
output  [255:0] o_stream_TDATA;
input   ap_clk;
input   ap_rst;
input   l_ap_vld;
input   i_stream_TVALID;
output   i_stream_TREADY;
input   s_stream_TVALID;
output   s_stream_TREADY;
output   o_stream_TVALID;
input   o_stream_TREADY;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_start;
wire    do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_done;
wire    do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_continue;
wire    do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_idle;
wire    do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_ready;
wire   [5:0] do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_l;
wire    do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_i_stream_TREADY;
wire    do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_s_stream_TREADY;
wire   [255:0] do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_o_stream_TDATA;
wire    do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_o_stream_TVALID;

UD_do_uD_Loop_VITIS_LOOP_58_1_proc1 do_uD_Loop_VITIS_LOOP_58_1_proc1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_start),
    .ap_done(do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_done),
    .ap_continue(do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_continue),
    .ap_idle(do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_idle),
    .ap_ready(do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_ready),
    .l(do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_l),
    .i_stream_TDATA(i_stream_TDATA),
    .i_stream_TVALID(i_stream_TVALID),
    .i_stream_TREADY(do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_i_stream_TREADY),
    .s_stream_TDATA(s_stream_TDATA),
    .s_stream_TVALID(s_stream_TVALID),
    .s_stream_TREADY(do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_s_stream_TREADY),
    .o_stream_TDATA(do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_o_stream_TDATA),
    .o_stream_TVALID(do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_o_stream_TVALID),
    .o_stream_TREADY(o_stream_TREADY)
);

assign ap_done = do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_done;

assign ap_idle = do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_idle;

assign ap_ready = do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_ready;

assign do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_continue = ap_continue;

assign do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_ap_start = ap_start;

assign do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_l = {{l[(6 - 32'd1):0]}};

assign i_stream_TREADY = do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_i_stream_TREADY;

assign o_stream_TDATA = do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_o_stream_TDATA;

assign o_stream_TVALID = do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_o_stream_TVALID;

assign s_stream_TREADY = do_uD_Loop_VITIS_LOOP_58_1_proc1_U0_s_stream_TREADY;

endmodule //UD_do_uD
// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module UD_do_uD_Loop_VITIS_LOOP_58_1_proc1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        l,
        i_stream_TDATA,
        i_stream_TVALID,
        i_stream_TREADY,
        s_stream_TDATA,
        s_stream_TVALID,
        s_stream_TREADY,
        o_stream_TDATA,
        o_stream_TVALID,
        o_stream_TREADY
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [5:0] l;
input  [63:0] i_stream_TDATA;
input   i_stream_TVALID;
output   i_stream_TREADY;
input  [7:0] s_stream_TDATA;
input   s_stream_TVALID;
output   s_stream_TREADY;
output  [255:0] o_stream_TDATA;
output   o_stream_TVALID;
input   o_stream_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [12:0] empty_fu_100_p2;
reg   [12:0] empty_reg_144;
wire    ap_CS_fsm_state2;
wire   [9:0] empty_24_fu_129_p2;
reg   [9:0] empty_24_reg_149;
wire    grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_start;
wire    grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_done;
wire    grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_idle;
wire    grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_ready;
wire    grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_o_stream_TREADY;
wire    grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_i_stream_TREADY;
wire    grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_s_stream_TREADY;
wire   [255:0] grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_o_stream_TDATA;
wire    grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_o_stream_TVALID;
reg    grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    ap_block_state1;
wire   [11:0] tmp_i_fu_78_p3;
wire   [9:0] tmp_1_i_fu_89_p3;
wire   [12:0] tmp_i_cast_fu_85_p1;
wire   [12:0] tmp_1_i_cast_fu_96_p1;
wire   [8:0] tmp_2_i_fu_107_p3;
wire   [6:0] tmp_3_i_fu_118_p3;
wire   [9:0] tmp_2_i_cast_fu_114_p1;
wire   [9:0] tmp_3_i_cast_fu_125_p1;
wire    ap_CS_fsm_state4;
wire    regslice_both_o_stream_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    regslice_both_i_stream_U_apdone_blk;
wire   [63:0] i_stream_TDATA_int_regslice;
wire    i_stream_TVALID_int_regslice;
reg    i_stream_TREADY_int_regslice;
wire    regslice_both_i_stream_U_ack_in;
wire    regslice_both_s_stream_U_apdone_blk;
wire   [7:0] s_stream_TDATA_int_regslice;
wire    s_stream_TVALID_int_regslice;
reg    s_stream_TREADY_int_regslice;
wire    regslice_both_s_stream_U_ack_in;
wire    o_stream_TREADY_int_regslice;
wire    regslice_both_o_stream_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_done_reg = 1'b0;
//#0 ap_CS_fsm = 4'd1;
//#0 grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_start_reg = 1'b0;
end

UD_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_start),
    .ap_done(grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_done),
    .ap_idle(grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_idle),
    .ap_ready(grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_ready),
    .i_stream_TVALID(i_stream_TVALID_int_regslice),
    .s_stream_TVALID(s_stream_TVALID_int_regslice),
    .o_stream_TREADY(grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_o_stream_TREADY),
    .empty_21(empty_24_reg_149),
    .empty(empty_reg_144),
    .i_stream_TDATA(i_stream_TDATA_int_regslice),
    .i_stream_TREADY(grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_i_stream_TREADY),
    .s_stream_TDATA(s_stream_TDATA_int_regslice),
    .s_stream_TREADY(grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_s_stream_TREADY),
    .o_stream_TDATA(grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_o_stream_TDATA),
    .o_stream_TVALID(grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_o_stream_TVALID)
);

UD_regslice_both #(
    .DataWidth( 64 ))
regslice_both_i_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(i_stream_TDATA),
    .vld_in(i_stream_TVALID),
    .ack_in(regslice_both_i_stream_U_ack_in),
    .data_out(i_stream_TDATA_int_regslice),
    .vld_out(i_stream_TVALID_int_regslice),
    .ack_out(i_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_i_stream_U_apdone_blk)
);

UD_regslice_both #(
    .DataWidth( 8 ))
regslice_both_s_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_stream_TDATA),
    .vld_in(s_stream_TVALID),
    .ack_in(regslice_both_s_stream_U_ack_in),
    .data_out(s_stream_TDATA_int_regslice),
    .vld_out(s_stream_TVALID_int_regslice),
    .ack_out(s_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_stream_U_apdone_blk)
);

UD_regslice_both #(
    .DataWidth( 256 ))
regslice_both_o_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_o_stream_TDATA),
    .vld_in(grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_o_stream_TVALID),
    .ack_in(o_stream_TREADY_int_regslice),
    .data_out(o_stream_TDATA),
    .vld_out(regslice_both_o_stream_U_vld_out),
    .ack_out(o_stream_TREADY),
    .apdone_blk(regslice_both_o_stream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_o_stream_U_apdone_blk == 1'b0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_start_reg <= 1'b1;
        end else if ((grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_ready == 1'b1)) begin
            grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        empty_24_reg_149[9 : 1] <= empty_24_fu_129_p2[9 : 1];
        empty_reg_144[12 : 4] <= empty_fu_100_p2[12 : 4];
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_o_stream_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_o_stream_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_o_stream_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_stream_TREADY_int_regslice = grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_i_stream_TREADY;
    end else begin
        i_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        s_stream_TREADY_int_regslice = grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_s_stream_TREADY;
    end else begin
        s_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_o_stream_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign empty_24_fu_129_p2 = (tmp_2_i_cast_fu_114_p1 + tmp_3_i_cast_fu_125_p1);

assign empty_fu_100_p2 = (tmp_i_cast_fu_85_p1 + tmp_1_i_cast_fu_96_p1);

assign grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_start = grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_ap_start_reg;

assign grp_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s_fu_62_o_stream_TREADY = (o_stream_TREADY_int_regslice & ap_CS_fsm_state3);

assign i_stream_TREADY = regslice_both_i_stream_U_ack_in;

assign o_stream_TVALID = regslice_both_o_stream_U_vld_out;

assign s_stream_TREADY = regslice_both_s_stream_U_ack_in;

assign tmp_1_i_cast_fu_96_p1 = tmp_1_i_fu_89_p3;

assign tmp_1_i_fu_89_p3 = {{l}, {4'd0}};

assign tmp_2_i_cast_fu_114_p1 = tmp_2_i_fu_107_p3;

assign tmp_2_i_fu_107_p3 = {{l}, {3'd0}};

assign tmp_3_i_cast_fu_125_p1 = tmp_3_i_fu_118_p3;

assign tmp_3_i_fu_118_p3 = {{l}, {1'd0}};

assign tmp_i_cast_fu_85_p1 = tmp_i_fu_78_p3;

assign tmp_i_fu_78_p3 = {{l}, {6'd0}};

always @ (posedge ap_clk) begin
    empty_reg_144[3:0] <= 4'b0000;
    empty_24_reg_149[0] <= 1'b0;
end

endmodule //UD_do_uD_Loop_VITIS_LOOP_58_1_proc1
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module UD_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITbkb (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 3;
parameter AddressWidth = 10;
parameter AddressRange = 640;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
(* rom_style = "hls_ultra" *)reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("D:/file/project/git/light-mamba/SPINAL/src/main/verilog/UD/UD_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITbkb.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module UD_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITcud (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 8;
parameter AddressWidth = 13;
parameter AddressRange = 5120;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
(* rom_style = "hls_ultra" *)reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("D:/file/project/git/light-mamba/SPINAL/src/main/verilog/UD/UD_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITcud.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module UD_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        i_stream_TVALID,
        s_stream_TVALID,
        o_stream_TREADY,
        empty_21,
        empty,
        i_stream_TDATA,
        i_stream_TREADY,
        s_stream_TDATA,
        s_stream_TREADY,
        o_stream_TDATA,
        o_stream_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   i_stream_TVALID;
input   s_stream_TVALID;
input   o_stream_TREADY;
input  [9:0] empty_21;
input  [12:0] empty;
input  [63:0] i_stream_TDATA;
output   i_stream_TREADY;
input  [7:0] s_stream_TDATA;
output   s_stream_TREADY;
output  [255:0] o_stream_TDATA;
output   o_stream_TVALID;

reg ap_idle;
reg i_stream_TREADY;
reg s_stream_TREADY;
reg o_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln58_fu_265_p2;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] uD_inst_D_weight_s_V_address0;
reg    uD_inst_D_weight_s_V_ce0;
wire   [2:0] uD_inst_D_weight_s_V_q0;
wire   [12:0] uD_inst_D_weight_V_address0;
reg    uD_inst_D_weight_V_ce0;
wire   [7:0] uD_inst_D_weight_V_q0;
wire    i_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
wire    s_stream_TDATA_blk_n;
wire    o_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln58_reg_980;
wire   [0:0] icmp_ln59_fu_274_p2;
reg   [0:0] icmp_ln59_reg_984;
reg   [0:0] icmp_ln59_reg_984_pp0_iter1_reg;
wire   [7:0] trunc_ln62_fu_280_p1;
reg   [7:0] trunc_ln62_reg_994;
reg   [7:0] trunc_ln62_reg_994_pp0_iter1_reg;
reg   [7:0] trunc_ln62_reg_994_pp0_iter2_reg;
reg  signed [7:0] trunc_ln62_reg_994_pp0_iter3_reg;
reg   [7:0] trunc_ln62_6_i_reg_999;
reg   [7:0] trunc_ln62_6_i_reg_999_pp0_iter1_reg;
reg   [7:0] trunc_ln62_6_i_reg_999_pp0_iter2_reg;
reg  signed [7:0] trunc_ln62_6_i_reg_999_pp0_iter3_reg;
reg   [7:0] trunc_ln62_7_i_reg_1004;
reg   [7:0] trunc_ln62_7_i_reg_1004_pp0_iter1_reg;
reg   [7:0] trunc_ln62_7_i_reg_1004_pp0_iter2_reg;
reg  signed [7:0] trunc_ln62_7_i_reg_1004_pp0_iter3_reg;
reg   [7:0] tmp_i_i_reg_1009;
reg   [7:0] tmp_i_i_reg_1009_pp0_iter1_reg;
reg   [7:0] tmp_i_i_reg_1009_pp0_iter2_reg;
reg  signed [7:0] tmp_i_i_reg_1009_pp0_iter3_reg;
reg   [7:0] tmp_1_i_i_reg_1014;
reg   [7:0] tmp_1_i_i_reg_1014_pp0_iter1_reg;
reg   [7:0] tmp_1_i_i_reg_1014_pp0_iter2_reg;
reg  signed [7:0] tmp_1_i_i_reg_1014_pp0_iter3_reg;
reg   [7:0] tmp_2_i_i_reg_1019;
reg   [7:0] tmp_2_i_i_reg_1019_pp0_iter1_reg;
reg   [7:0] tmp_2_i_i_reg_1019_pp0_iter2_reg;
reg  signed [7:0] tmp_2_i_i_reg_1019_pp0_iter3_reg;
reg   [7:0] tmp_3_i_i_reg_1024;
reg   [7:0] tmp_3_i_i_reg_1024_pp0_iter1_reg;
reg   [7:0] tmp_3_i_i_reg_1024_pp0_iter2_reg;
reg  signed [7:0] tmp_3_i_i_reg_1024_pp0_iter3_reg;
reg   [7:0] tmp_4_i_i_reg_1029;
reg   [7:0] tmp_4_i_i_reg_1029_pp0_iter1_reg;
reg   [7:0] tmp_4_i_i_reg_1029_pp0_iter2_reg;
reg  signed [7:0] tmp_4_i_i_reg_1029_pp0_iter3_reg;
wire   [3:0] lhs_V_fu_354_p1;
reg   [3:0] lhs_V_reg_1034;
reg   [3:0] lhs_V_reg_1034_pp0_iter1_reg;
reg   [3:0] lhs_V_reg_1034_pp0_iter2_reg;
reg   [3:0] lhs_V_reg_1034_pp0_iter3_reg;
reg   [3:0] lhs_V_reg_1034_pp0_iter4_reg;
wire   [6:0] empty_22_fu_400_p2;
reg   [6:0] empty_22_reg_1039;
wire   [6:0] p_mid_i_fu_422_p3;
reg   [6:0] p_mid_i_reg_1044;
wire   [3:0] select_ln58_2_fu_437_p3;
reg   [3:0] select_ln58_2_reg_1049;
reg   [3:0] select_ln58_2_reg_1049_pp0_iter2_reg;
reg   [3:0] select_ln58_2_reg_1049_pp0_iter3_reg;
wire   [0:0] and_ln58_fu_455_p2;
reg   [0:0] and_ln58_reg_1054;
wire   [6:0] p_mid1_i_fu_471_p2;
reg   [6:0] p_mid1_i_reg_1059;
reg   [7:0] uD_inst_D_weight_V_load_reg_1069;
wire  signed [15:0] sext_ln59_fu_557_p1;
wire   [4:0] ret_V_fu_639_p2;
reg   [4:0] ret_V_reg_1131;
wire   [14:0] ret_V_1_fu_645_p1;
reg   [14:0] ret_V_1_reg_1136;
wire   [14:0] ret_V_2_fu_649_p1;
reg   [14:0] ret_V_2_reg_1141;
wire   [14:0] ret_V_3_fu_653_p1;
reg   [14:0] ret_V_3_reg_1146;
wire   [14:0] ret_V_4_fu_657_p1;
reg   [14:0] ret_V_4_reg_1151;
wire   [14:0] ret_V_5_fu_661_p1;
reg   [14:0] ret_V_5_reg_1156;
wire   [14:0] ret_V_6_fu_665_p1;
reg   [14:0] ret_V_6_reg_1161;
wire   [14:0] ret_V_7_fu_669_p1;
reg   [14:0] ret_V_7_reg_1166;
wire   [14:0] ret_V_8_fu_673_p1;
reg   [14:0] ret_V_8_reg_1171;
wire   [63:0] add_ln59_1_i_cast_fu_539_p1;
wire   [63:0] add_ln58_1_i_cast_fu_552_p1;
reg   [3:0] pt_fu_154;
wire   [3:0] pt_1_fu_496_p3;
wire    ap_loop_init;
reg   [3:0] cp_fu_158;
wire   [3:0] select_ln59_1_fu_477_p3;
reg   [7:0] indvar_flatten_i_fu_162;
wire   [7:0] select_ln59_2_fu_364_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_i_load;
reg   [3:0] ct_fu_166;
reg   [9:0] indvar_flatten28_i_fu_170;
wire   [9:0] add_ln58_fu_259_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten28_i_load;
wire    ap_block_pp0_stage0_01001;
wire   [7:0] add_ln59_2_fu_358_p2;
wire   [6:0] tmp_4_i_fu_388_p3;
wire   [6:0] zext_ln59_fu_396_p1;
wire   [3:0] add_ln58_1_fu_409_p2;
wire   [0:0] icmp_ln60_fu_449_p2;
wire   [0:0] xor_ln58_fu_444_p2;
wire   [3:0] select_ln58_fu_415_p3;
wire   [3:0] add_ln59_fu_461_p2;
wire   [6:0] select_ln58_1_fu_430_p3;
wire   [6:0] zext_ln59_1_fu_467_p1;
wire   [0:0] or_ln60_fu_491_p2;
wire   [3:0] add_ln60_fu_485_p2;
wire   [6:0] select_ln58_3_fu_519_p3;
wire   [6:0] select_ln59_fu_524_p3;
wire   [12:0] zext_ln59_2_fu_530_p1;
wire   [12:0] add_ln59_1_fu_534_p2;
wire   [9:0] zext_ln58_fu_544_p1;
wire   [9:0] add_ln58_2_fu_547_p2;
wire  signed [7:0] grp_fu_584_p1;
wire  signed [7:0] grp_fu_590_p1;
wire  signed [7:0] grp_fu_596_p1;
wire  signed [7:0] grp_fu_602_p1;
wire  signed [7:0] grp_fu_608_p1;
wire  signed [7:0] grp_fu_614_p1;
wire  signed [7:0] grp_fu_620_p1;
wire  signed [7:0] grp_fu_626_p1;
wire   [4:0] zext_ln186_fu_636_p1;
wire   [4:0] zext_ln58_1_fu_632_p1;
wire   [15:0] grp_fu_584_p2;
wire   [15:0] grp_fu_590_p2;
wire   [15:0] grp_fu_596_p2;
wire   [15:0] grp_fu_602_p2;
wire   [15:0] grp_fu_608_p2;
wire   [15:0] grp_fu_614_p2;
wire   [15:0] grp_fu_620_p2;
wire   [15:0] grp_fu_626_p2;
wire  signed [33:0] sext_ln71_fu_680_p1;
wire   [33:0] sh_prom_i_i_i_i_fu_677_p1;
wire   [33:0] r_V_fu_683_p2;
wire   [25:0] trunc_ln1_i_fu_689_p4;
wire  signed [33:0] sext_ln71_2_fu_703_p1;
wire  signed [33:0] sext_ln71_3_fu_712_p1;
wire  signed [33:0] sext_ln71_4_fu_721_p1;
wire  signed [33:0] sext_ln71_5_fu_730_p1;
wire  signed [33:0] sext_ln71_6_fu_739_p1;
wire  signed [33:0] sext_ln71_7_fu_748_p1;
wire   [33:0] r_V_6_fu_751_p2;
wire   [25:0] trunc_ln1669_6_i_fu_757_p4;
wire  signed [33:0] sext_ln71_9_fu_771_p1;
wire   [33:0] r_V_7_fu_774_p2;
wire   [33:0] r_V_1_fu_706_p2;
wire   [33:0] r_V_2_fu_715_p2;
wire   [33:0] r_V_3_fu_724_p2;
wire   [33:0] r_V_4_fu_733_p2;
wire   [33:0] r_V_5_fu_742_p2;
wire   [24:0] tmp_i_fu_830_p4;
wire   [24:0] tmp_10_i_fu_844_p4;
wire   [24:0] tmp_11_i_fu_858_p4;
wire   [24:0] tmp_12_i_fu_872_p4;
wire   [24:0] tmp_13_i_fu_886_p4;
wire   [25:0] trunc_ln1669_7_i_fu_780_p4;
wire  signed [31:0] sext_ln71_8_fu_767_p1;
wire  signed [30:0] sext_ln73_4_fu_896_p1;
wire   [0:0] tmp_6_fu_822_p3;
wire  signed [30:0] sext_ln73_3_fu_882_p1;
wire   [0:0] tmp_5_fu_814_p3;
wire  signed [30:0] sext_ln73_2_fu_868_p1;
wire   [0:0] tmp_4_fu_806_p3;
wire  signed [30:0] sext_ln73_1_fu_854_p1;
wire   [0:0] tmp_3_fu_798_p3;
wire  signed [30:0] sext_ln73_fu_840_p1;
wire   [0:0] tmp_2_fu_790_p3;
wire  signed [31:0] sext_ln71_1_fu_699_p1;
wire   [249:0] tmp_14_i_fu_900_p14;
wire    ap_continue_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_done_int_frp;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [6:0] frp_pipeline_valid_U_valid_out;
wire   [3:0] frp_pipeline_valid_U_num_valid_datasets;
wire   [255:0] pf_o_stream_U_data_out;
wire    pf_o_stream_U_data_out_vld;
wire    pf_o_stream_U_pf_ready;
wire    pf_o_stream_U_pf_done;
reg    ap_condition_frp_pvb_no_fwd_prs;
reg    ap_condition_frp_pvb_no_bkwd_prs;
reg    ap_condition_frp_pvb_pf_start;
reg    ap_frp_vld_in;
reg    frp_pipeline_valid_U_exitcond;
reg    pf_o_stream_U_data_in_vld;
wire   [255:0] pf_o_stream_U_frpsig_data_in;
reg    pf_all_done;
wire    ap_ce_reg;

// power-on initialization
initial begin
//#0 ap_CS_fsm = 1'd1;
//#0 pf_all_done = 1'b0;
end

UD_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITbkb #(
    .DataWidth( 3 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
uD_inst_D_weight_s_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(uD_inst_D_weight_s_V_address0),
    .ce0(uD_inst_D_weight_s_V_ce0),
    .q0(uD_inst_D_weight_s_V_q0)
);

UD_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITcud #(
    .DataWidth( 8 ),
    .AddressRange( 5120 ),
    .AddressWidth( 13 ))
uD_inst_D_weight_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(uD_inst_D_weight_V_address0),
    .ce0(uD_inst_D_weight_V_ce0),
    .q0(uD_inst_D_weight_V_q0)
);

UD_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln62_reg_994_pp0_iter3_reg),
    .din1(grp_fu_584_p1),
    .ce(1'b1),
    .dout(grp_fu_584_p2)
);

UD_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_i_i_reg_1009_pp0_iter3_reg),
    .din1(grp_fu_590_p1),
    .ce(1'b1),
    .dout(grp_fu_590_p2)
);

UD_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_1_i_i_reg_1014_pp0_iter3_reg),
    .din1(grp_fu_596_p1),
    .ce(1'b1),
    .dout(grp_fu_596_p2)
);

UD_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_2_i_i_reg_1019_pp0_iter3_reg),
    .din1(grp_fu_602_p1),
    .ce(1'b1),
    .dout(grp_fu_602_p2)
);

UD_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_3_i_i_reg_1024_pp0_iter3_reg),
    .din1(grp_fu_608_p1),
    .ce(1'b1),
    .dout(grp_fu_608_p2)
);

UD_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_4_i_i_reg_1029_pp0_iter3_reg),
    .din1(grp_fu_614_p1),
    .ce(1'b1),
    .dout(grp_fu_614_p2)
);

UD_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln62_6_i_reg_999_pp0_iter3_reg),
    .din1(grp_fu_620_p1),
    .ce(1'b1),
    .dout(grp_fu_620_p2)
);

UD_mul_8s_8s_16_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8s_8s_16_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln62_7_i_reg_1004_pp0_iter3_reg),
    .din1(grp_fu_626_p1),
    .ce(1'b1),
    .dout(grp_fu_626_p2)
);

UD_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(pf_all_done),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(pf_all_done)
);

UD_frp_pipeline_valid #(
    .PipelineLatency( 7 ),
    .PipelineII( 1 ),
    .CeilLog2Stages( 3 ),
    .ExitLatency( 1 ))
frp_pipeline_valid_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .valid_in(ap_frp_vld_in),
    .exitcond(frp_pipeline_valid_U_exitcond),
    .valid_out(frp_pipeline_valid_U_valid_out),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

UD_frp_fifoout #(
    .BlockingType( 1 ),
    .PipeLatency( 7 ),
    .PipelineII( 1 ),
    .DataWidth( 256 ),
    .NumWrites( 1 ),
    .CeilLog2Stages( 3 ),
    .CeilLog2FDepth( 3 ),
    .PfAllDoneEnable( 2 ))
pf_o_stream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(pf_o_stream_U_frpsig_data_in),
    .data_out(pf_o_stream_U_data_out),
    .valid(frp_pipeline_valid_U_valid_out),
    .data_in_vld(pf_o_stream_U_data_in_vld),
    .data_out_vld(pf_o_stream_U_data_out_vld),
    .data_in_last(ap_done_int_frp),
    .pf_continue(1'b1),
    .pf_all_done(pf_all_done),
    .pf_ready(pf_o_stream_U_pf_ready),
    .pf_done(pf_o_stream_U_pf_done),
    .data_out_read(o_stream_TREADY),
    .ap_start(1'b0),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        pf_all_done <= 1'b0;
    end else begin
        pf_all_done <= pf_o_stream_U_pf_done;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cp_fu_158 <= 4'd0;
    end else if (((frp_pipeline_valid_U_valid_out[3'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln58_reg_980 == 1'd0)))) begin
        cp_fu_158 <= select_ln59_1_fu_477_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ct_fu_166 <= 4'd0;
    end else if (((frp_pipeline_valid_U_valid_out[3'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln58_reg_980 == 1'd0)))) begin
        ct_fu_166 <= select_ln58_2_fu_437_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[3'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln58_fu_265_p2 == 1'd0)))) begin
        indvar_flatten28_i_fu_170 <= add_ln58_fu_259_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten28_i_fu_170 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[3'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln58_fu_265_p2 == 1'd0)))) begin
        indvar_flatten_i_fu_162 <= select_ln59_2_fu_364_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_i_fu_162 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pt_fu_154 <= 4'd0;
    end else if (((frp_pipeline_valid_U_valid_out[3'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln58_reg_980 == 1'd0)))) begin
        pt_fu_154 <= pt_1_fu_496_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln58_reg_980 == 1'd0))) begin
        and_ln58_reg_1054 <= and_ln58_fu_455_p2;
        p_mid1_i_reg_1059 <= p_mid1_i_fu_471_p2;
        p_mid_i_reg_1044[6 : 3] <= p_mid_i_fu_422_p3[6 : 3];
        select_ln58_2_reg_1049 <= select_ln58_2_fu_437_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln58_reg_980 <= icmp_ln58_fu_265_p2;
        icmp_ln59_reg_984_pp0_iter1_reg <= icmp_ln59_reg_984;
        lhs_V_reg_1034_pp0_iter1_reg <= lhs_V_reg_1034;
        tmp_1_i_i_reg_1014_pp0_iter1_reg <= tmp_1_i_i_reg_1014;
        tmp_2_i_i_reg_1019_pp0_iter1_reg <= tmp_2_i_i_reg_1019;
        tmp_3_i_i_reg_1024_pp0_iter1_reg <= tmp_3_i_i_reg_1024;
        tmp_4_i_i_reg_1029_pp0_iter1_reg <= tmp_4_i_i_reg_1029;
        tmp_i_i_reg_1009_pp0_iter1_reg <= tmp_i_i_reg_1009;
        trunc_ln62_6_i_reg_999_pp0_iter1_reg <= trunc_ln62_6_i_reg_999;
        trunc_ln62_7_i_reg_1004_pp0_iter1_reg <= trunc_ln62_7_i_reg_1004;
        trunc_ln62_reg_994_pp0_iter1_reg <= trunc_ln62_reg_994;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        lhs_V_reg_1034_pp0_iter2_reg <= lhs_V_reg_1034_pp0_iter1_reg;
        lhs_V_reg_1034_pp0_iter3_reg <= lhs_V_reg_1034_pp0_iter2_reg;
        lhs_V_reg_1034_pp0_iter4_reg <= lhs_V_reg_1034_pp0_iter3_reg;
        ret_V_1_reg_1136 <= ret_V_1_fu_645_p1;
        ret_V_2_reg_1141 <= ret_V_2_fu_649_p1;
        ret_V_3_reg_1146 <= ret_V_3_fu_653_p1;
        ret_V_4_reg_1151 <= ret_V_4_fu_657_p1;
        ret_V_5_reg_1156 <= ret_V_5_fu_661_p1;
        ret_V_6_reg_1161 <= ret_V_6_fu_665_p1;
        ret_V_7_reg_1166 <= ret_V_7_fu_669_p1;
        ret_V_8_reg_1171 <= ret_V_8_fu_673_p1;
        ret_V_reg_1131 <= ret_V_fu_639_p2;
        select_ln58_2_reg_1049_pp0_iter2_reg <= select_ln58_2_reg_1049;
        select_ln58_2_reg_1049_pp0_iter3_reg <= select_ln58_2_reg_1049_pp0_iter2_reg;
        tmp_1_i_i_reg_1014_pp0_iter2_reg <= tmp_1_i_i_reg_1014_pp0_iter1_reg;
        tmp_1_i_i_reg_1014_pp0_iter3_reg <= tmp_1_i_i_reg_1014_pp0_iter2_reg;
        tmp_2_i_i_reg_1019_pp0_iter2_reg <= tmp_2_i_i_reg_1019_pp0_iter1_reg;
        tmp_2_i_i_reg_1019_pp0_iter3_reg <= tmp_2_i_i_reg_1019_pp0_iter2_reg;
        tmp_3_i_i_reg_1024_pp0_iter2_reg <= tmp_3_i_i_reg_1024_pp0_iter1_reg;
        tmp_3_i_i_reg_1024_pp0_iter3_reg <= tmp_3_i_i_reg_1024_pp0_iter2_reg;
        tmp_4_i_i_reg_1029_pp0_iter2_reg <= tmp_4_i_i_reg_1029_pp0_iter1_reg;
        tmp_4_i_i_reg_1029_pp0_iter3_reg <= tmp_4_i_i_reg_1029_pp0_iter2_reg;
        tmp_i_i_reg_1009_pp0_iter2_reg <= tmp_i_i_reg_1009_pp0_iter1_reg;
        tmp_i_i_reg_1009_pp0_iter3_reg <= tmp_i_i_reg_1009_pp0_iter2_reg;
        trunc_ln62_6_i_reg_999_pp0_iter2_reg <= trunc_ln62_6_i_reg_999_pp0_iter1_reg;
        trunc_ln62_6_i_reg_999_pp0_iter3_reg <= trunc_ln62_6_i_reg_999_pp0_iter2_reg;
        trunc_ln62_7_i_reg_1004_pp0_iter2_reg <= trunc_ln62_7_i_reg_1004_pp0_iter1_reg;
        trunc_ln62_7_i_reg_1004_pp0_iter3_reg <= trunc_ln62_7_i_reg_1004_pp0_iter2_reg;
        trunc_ln62_reg_994_pp0_iter2_reg <= trunc_ln62_reg_994_pp0_iter1_reg;
        trunc_ln62_reg_994_pp0_iter3_reg <= trunc_ln62_reg_994_pp0_iter2_reg;
        uD_inst_D_weight_V_load_reg_1069 <= uD_inst_D_weight_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln59_reg_984 == 1'd0))) begin
        empty_22_reg_1039 <= empty_22_fu_400_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln58_fu_265_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln59_reg_984 <= icmp_ln59_fu_274_p2;
        lhs_V_reg_1034 <= lhs_V_fu_354_p1;
        tmp_1_i_i_reg_1014 <= {{i_stream_TDATA[23:16]}};
        tmp_2_i_i_reg_1019 <= {{i_stream_TDATA[31:24]}};
        tmp_3_i_i_reg_1024 <= {{i_stream_TDATA[39:32]}};
        tmp_4_i_i_reg_1029 <= {{i_stream_TDATA[47:40]}};
        tmp_i_i_reg_1009 <= {{i_stream_TDATA[15:8]}};
        trunc_ln62_6_i_reg_999 <= {{i_stream_TDATA[55:48]}};
        trunc_ln62_7_i_reg_1004 <= {{i_stream_TDATA[63:56]}};
        trunc_ln62_reg_994 <= trunc_ln62_fu_280_p1;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[3'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln58_fu_265_p2 == 1'd1)))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int_frp = 1'b1;
    end else begin
        ap_done_int_frp = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[3'd1] == 1'b1)) begin
        ap_enable_reg_pp0_iter1 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter1 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[3'd2] == 1'b1)) begin
        ap_enable_reg_pp0_iter2 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter2 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[3'd3] == 1'b1)) begin
        ap_enable_reg_pp0_iter3 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter3 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[3'd4] == 1'b1)) begin
        ap_enable_reg_pp0_iter4 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter4 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[3'd5] == 1'b1)) begin
        ap_enable_reg_pp0_iter5 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter5 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[3'd6] == 1'b1)) begin
        ap_enable_reg_pp0_iter6 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_condition_frp_pvb_pf_start) & (1'b1 == ap_condition_frp_pvb_no_bkwd_prs) & (1'b1 == ap_condition_frp_pvb_no_fwd_prs))) begin
        ap_frp_vld_in = 1'b1;
    end else begin
        ap_frp_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[3'd0] == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten28_i_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten28_i_load = indvar_flatten28_i_fu_170;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_i_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_i_load = indvar_flatten_i_fu_162;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln58_reg_980 == 1'd1))) begin
        frp_pipeline_valid_U_exitcond = 1'b1;
    end else begin
        frp_pipeline_valid_U_exitcond = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[3'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln58_fu_265_p2 == 1'd0)))) begin
        i_stream_TREADY = 1'b1;
    end else begin
        i_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((pf_o_stream_U_data_out_vld == 1'b1)) begin
        o_stream_TVALID = 1'b1;
    end else begin
        o_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        pf_o_stream_U_data_in_vld = 1'b1;
    end else begin
        pf_o_stream_U_data_in_vld = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[3'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln58_fu_265_p2 == 1'd0)))) begin
        s_stream_TREADY = 1'b1;
    end else begin
        s_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        uD_inst_D_weight_V_ce0 = 1'b1;
    end else begin
        uD_inst_D_weight_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        uD_inst_D_weight_s_V_ce0 = 1'b1;
    end else begin
        uD_inst_D_weight_s_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_1_fu_409_p2 = (ct_fu_166 + 4'd1);

assign add_ln58_1_i_cast_fu_552_p1 = add_ln58_2_fu_547_p2;

assign add_ln58_2_fu_547_p2 = (empty_21 + zext_ln58_fu_544_p1);

assign add_ln58_fu_259_p2 = (ap_sig_allocacmp_indvar_flatten28_i_load + 10'd1);

assign add_ln59_1_fu_534_p2 = (empty + zext_ln59_2_fu_530_p1);

assign add_ln59_1_i_cast_fu_539_p1 = add_ln59_1_fu_534_p2;

assign add_ln59_2_fu_358_p2 = (ap_sig_allocacmp_indvar_flatten_i_load + 8'd1);

assign add_ln59_fu_461_p2 = (select_ln58_fu_415_p3 + 4'd1);

assign add_ln60_fu_485_p2 = (pt_fu_154 + 4'd1);

assign and_ln58_fu_455_p2 = (xor_ln58_fu_444_p2 & icmp_ln60_fu_449_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = 1'b0;

assign ap_block_pp0_stage0_01001 = 1'b0;

assign ap_block_pp0_stage0_11001 = 1'b0;

assign ap_block_pp0_stage0_subdone = 1'b0;

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln58_fu_265_p2 == 1'd0) & (1'b1 == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = (1'b1 == 1'b0);

always @ (*) begin
    ap_condition_frp_pvb_no_bkwd_prs = (pf_o_stream_U_pf_ready == 1'b1);
end

always @ (*) begin
    ap_condition_frp_pvb_no_fwd_prs = ~(((s_stream_TVALID == 1'b0) & (icmp_ln58_fu_265_p2 == 1'd0)) | ((icmp_ln58_fu_265_p2 == 1'd0) & (i_stream_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_frp_pvb_pf_start = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_22_fu_400_p2 = (tmp_4_i_fu_388_p3 + zext_ln59_fu_396_p1);

assign grp_fu_584_p1 = sext_ln59_fu_557_p1;

assign grp_fu_590_p1 = sext_ln59_fu_557_p1;

assign grp_fu_596_p1 = sext_ln59_fu_557_p1;

assign grp_fu_602_p1 = sext_ln59_fu_557_p1;

assign grp_fu_608_p1 = sext_ln59_fu_557_p1;

assign grp_fu_614_p1 = sext_ln59_fu_557_p1;

assign grp_fu_620_p1 = sext_ln59_fu_557_p1;

assign grp_fu_626_p1 = sext_ln59_fu_557_p1;

assign i_stream_TDATA_blk_n = 1'b1;

assign icmp_ln58_fu_265_p2 = ((ap_sig_allocacmp_indvar_flatten28_i_load == 10'd640) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_274_p2 = ((ap_sig_allocacmp_indvar_flatten_i_load == 8'd64) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_449_p2 = ((pt_fu_154 == 4'd8) ? 1'b1 : 1'b0);

assign lhs_V_fu_354_p1 = s_stream_TDATA[3:0];

assign o_stream_TDATA = pf_o_stream_U_data_out;

assign o_stream_TDATA_blk_n = 1'b1;

assign or_ln60_fu_491_p2 = (icmp_ln59_reg_984 | and_ln58_fu_455_p2);

assign p_mid1_i_fu_471_p2 = (select_ln58_1_fu_430_p3 + zext_ln59_1_fu_467_p1);

assign p_mid_i_fu_422_p3 = {{add_ln58_1_fu_409_p2}, {3'd0}};

assign pf_o_stream_U_frpsig_data_in = $signed(tmp_14_i_fu_900_p14);

assign pt_1_fu_496_p3 = ((or_ln60_fu_491_p2[0:0] == 1'b1) ? 4'd1 : add_ln60_fu_485_p2);

assign r_V_1_fu_706_p2 = sext_ln71_2_fu_703_p1 << sh_prom_i_i_i_i_fu_677_p1;

assign r_V_2_fu_715_p2 = sext_ln71_3_fu_712_p1 << sh_prom_i_i_i_i_fu_677_p1;

assign r_V_3_fu_724_p2 = sext_ln71_4_fu_721_p1 << sh_prom_i_i_i_i_fu_677_p1;

assign r_V_4_fu_733_p2 = sext_ln71_5_fu_730_p1 << sh_prom_i_i_i_i_fu_677_p1;

assign r_V_5_fu_742_p2 = sext_ln71_6_fu_739_p1 << sh_prom_i_i_i_i_fu_677_p1;

assign r_V_6_fu_751_p2 = sext_ln71_7_fu_748_p1 << sh_prom_i_i_i_i_fu_677_p1;

assign r_V_7_fu_774_p2 = sext_ln71_9_fu_771_p1 << sh_prom_i_i_i_i_fu_677_p1;

assign r_V_fu_683_p2 = sext_ln71_fu_680_p1 << sh_prom_i_i_i_i_fu_677_p1;

assign ret_V_1_fu_645_p1 = grp_fu_584_p2[14:0];

assign ret_V_2_fu_649_p1 = grp_fu_590_p2[14:0];

assign ret_V_3_fu_653_p1 = grp_fu_596_p2[14:0];

assign ret_V_4_fu_657_p1 = grp_fu_602_p2[14:0];

assign ret_V_5_fu_661_p1 = grp_fu_608_p2[14:0];

assign ret_V_6_fu_665_p1 = grp_fu_614_p2[14:0];

assign ret_V_7_fu_669_p1 = grp_fu_620_p2[14:0];

assign ret_V_8_fu_673_p1 = grp_fu_626_p2[14:0];

assign ret_V_fu_639_p2 = (zext_ln186_fu_636_p1 + zext_ln58_1_fu_632_p1);

assign s_stream_TDATA_blk_n = 1'b1;

assign select_ln58_1_fu_430_p3 = ((icmp_ln59_reg_984[0:0] == 1'b1) ? p_mid_i_fu_422_p3 : tmp_4_i_fu_388_p3);

assign select_ln58_2_fu_437_p3 = ((icmp_ln59_reg_984[0:0] == 1'b1) ? add_ln58_1_fu_409_p2 : ct_fu_166);

assign select_ln58_3_fu_519_p3 = ((icmp_ln59_reg_984_pp0_iter1_reg[0:0] == 1'b1) ? p_mid_i_reg_1044 : empty_22_reg_1039);

assign select_ln58_fu_415_p3 = ((icmp_ln59_reg_984[0:0] == 1'b1) ? 4'd0 : cp_fu_158);

assign select_ln59_1_fu_477_p3 = ((and_ln58_fu_455_p2[0:0] == 1'b1) ? add_ln59_fu_461_p2 : select_ln58_fu_415_p3);

assign select_ln59_2_fu_364_p3 = ((icmp_ln59_fu_274_p2[0:0] == 1'b1) ? 8'd1 : add_ln59_2_fu_358_p2);

assign select_ln59_fu_524_p3 = ((and_ln58_reg_1054[0:0] == 1'b1) ? p_mid1_i_reg_1059 : select_ln58_3_fu_519_p3);

assign sext_ln59_fu_557_p1 = $signed(uD_inst_D_weight_V_load_reg_1069);

assign sext_ln71_1_fu_699_p1 = $signed(trunc_ln1_i_fu_689_p4);

assign sext_ln71_2_fu_703_p1 = $signed(ret_V_2_reg_1141);

assign sext_ln71_3_fu_712_p1 = $signed(ret_V_3_reg_1146);

assign sext_ln71_4_fu_721_p1 = $signed(ret_V_4_reg_1151);

assign sext_ln71_5_fu_730_p1 = $signed(ret_V_5_reg_1156);

assign sext_ln71_6_fu_739_p1 = $signed(ret_V_6_reg_1161);

assign sext_ln71_7_fu_748_p1 = $signed(ret_V_7_reg_1166);

assign sext_ln71_8_fu_767_p1 = $signed(trunc_ln1669_6_i_fu_757_p4);

assign sext_ln71_9_fu_771_p1 = $signed(ret_V_8_reg_1171);

assign sext_ln71_fu_680_p1 = $signed(ret_V_1_reg_1136);

assign sext_ln73_1_fu_854_p1 = $signed(tmp_10_i_fu_844_p4);

assign sext_ln73_2_fu_868_p1 = $signed(tmp_11_i_fu_858_p4);

assign sext_ln73_3_fu_882_p1 = $signed(tmp_12_i_fu_872_p4);

assign sext_ln73_4_fu_896_p1 = $signed(tmp_13_i_fu_886_p4);

assign sext_ln73_fu_840_p1 = $signed(tmp_i_fu_830_p4);

assign sh_prom_i_i_i_i_fu_677_p1 = ret_V_reg_1131;

assign tmp_10_i_fu_844_p4 = {{r_V_2_fu_715_p2[33:9]}};

assign tmp_11_i_fu_858_p4 = {{r_V_3_fu_724_p2[33:9]}};

assign tmp_12_i_fu_872_p4 = {{r_V_4_fu_733_p2[33:9]}};

assign tmp_13_i_fu_886_p4 = {{r_V_5_fu_742_p2[33:9]}};

assign tmp_14_i_fu_900_p14 = {{{{{{{{{{{{{trunc_ln1669_7_i_fu_780_p4}, {sext_ln71_8_fu_767_p1}}, {sext_ln73_4_fu_896_p1}}, {tmp_6_fu_822_p3}}, {sext_ln73_3_fu_882_p1}}, {tmp_5_fu_814_p3}}, {sext_ln73_2_fu_868_p1}}, {tmp_4_fu_806_p3}}, {sext_ln73_1_fu_854_p1}}, {tmp_3_fu_798_p3}}, {sext_ln73_fu_840_p1}}, {tmp_2_fu_790_p3}}, {sext_ln71_1_fu_699_p1}};

assign tmp_2_fu_790_p3 = r_V_1_fu_706_p2[32'd8];

assign tmp_3_fu_798_p3 = r_V_2_fu_715_p2[32'd8];

assign tmp_4_fu_806_p3 = r_V_3_fu_724_p2[32'd8];

assign tmp_4_i_fu_388_p3 = {{ct_fu_166}, {3'd0}};

assign tmp_5_fu_814_p3 = r_V_4_fu_733_p2[32'd8];

assign tmp_6_fu_822_p3 = r_V_5_fu_742_p2[32'd8];

assign tmp_i_fu_830_p4 = {{r_V_1_fu_706_p2[33:9]}};

assign trunc_ln1669_6_i_fu_757_p4 = {{r_V_6_fu_751_p2[33:8]}};

assign trunc_ln1669_7_i_fu_780_p4 = {{r_V_7_fu_774_p2[33:8]}};

assign trunc_ln1_i_fu_689_p4 = {{r_V_fu_683_p2[33:8]}};

assign trunc_ln62_fu_280_p1 = i_stream_TDATA[7:0];

assign uD_inst_D_weight_V_address0 = add_ln59_1_i_cast_fu_539_p1;

assign uD_inst_D_weight_s_V_address0 = add_ln58_1_i_cast_fu_552_p1;

assign xor_ln58_fu_444_p2 = (icmp_ln59_reg_984 ^ 1'd1);

assign zext_ln186_fu_636_p1 = lhs_V_reg_1034_pp0_iter4_reg;

assign zext_ln58_1_fu_632_p1 = uD_inst_D_weight_s_V_q0;

assign zext_ln58_fu_544_p1 = select_ln58_2_reg_1049_pp0_iter3_reg;

assign zext_ln59_1_fu_467_p1 = add_ln59_fu_461_p2;

assign zext_ln59_2_fu_530_p1 = select_ln59_fu_524_p3;

assign zext_ln59_fu_396_p1 = cp_fu_158;

always @ (posedge ap_clk) begin
    p_mid_i_reg_1044[2:0] <= 3'b000;
end

endmodule //UD_do_uD_Loop_VITIS_LOOP_58_1_proc1_Pipeline_VITIS_LOOP_58_1_VITIS_LOOP_59_2_VITIS_s
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

module UD_flow_control_loop_pipe_sequential_init(
        ap_clk,
        ap_rst,
        ap_start,
        ap_ready,
        ap_done,
        ap_start_int,
        ap_ready_int,
        ap_done_int,
        ap_continue_int,
        ap_loop_init,
        ap_loop_exit_ready,
        ap_loop_exit_done
);

input   ap_clk;
input   ap_rst;

//Block level handshake with outside loop
input   ap_start;
output  ap_ready;
output  ap_done;

//Block level handshake with loop body
output  ap_start_int;
input   ap_ready_int;
input   ap_done_int;
output  ap_continue_int;

//Init live in variables
output   ap_loop_init;
wire     ap_loop_init;
reg ap_loop_init_int;
reg ap_done;
reg ap_done_cache;

//Exit signal from loop body
input   ap_loop_exit_ready;
input   ap_loop_exit_done;

// power-on initialization
initial begin
//#0 ap_loop_init_int = 1'b1;
//#0 ap_done_cache = 1'b0;
end

assign ap_start_int = ap_start;

assign ap_continue_int = 1'b1;

assign ap_ready = ap_loop_exit_ready;

//ap_loop_init is valid for the first II
//of the first loop run so as to enable
//the init block ops which are pushed into
//the first state of the pipeline region
always @ (posedge ap_clk)
begin
    if (ap_rst == 1'b1) begin
        ap_loop_init_int <= 1'b1;
    end else if(ap_loop_exit_done == 1'b1) begin
        ap_loop_init_int <= 1'b1;
    end else if(ap_ready_int == 1'b1) begin
        ap_loop_init_int <= 1'b0;
    end
end

assign ap_loop_init = ap_loop_init_int & ap_start;

// if no ap_continue port and current module is not UD module, 
// ap_done handshakes with ap_start. Internally, flow control sends out 
// ap_conintue_int = 1'b1 so the ap_done_int is asserted high for 1 clock cycle.
// ap_done_cache is used to record ap_done_int, and de-assert if ap_start_int
// is asserted, so DUT can start the next run
always @(posedge ap_clk)
begin
    if (ap_rst == 1'b1) begin
        ap_done_cache <= 1'b0;
    end else if (ap_done_int == 1'b1) begin
        ap_done_cache <= 1'b1;
    end else if (ap_start_int == 1'b1) begin
        ap_done_cache <= 1'b0;
    end
end

// if no ap_continue port and current module is not UD module, ap_done handshakes with ap_start
always @(*)
begin
    if ((ap_done_int == 1'b1) || ((ap_done_cache == 1'b1) && (ap_start_int == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

endmodule
        
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

(* keep_hierarchy = "yes" *)
module UD_frp_fifoout
  (
   ap_clk,
   ap_rst,
   data_in,
   data_in_vld,
   data_in_last,

   data_out,
   data_out_vld,

   ap_start,
   data_out_read,

   valid,
   num_valid_datasets,
   pf_ready,
   pf_done,
   empty,
   pf_all_done,
   pf_continue
);
   parameter BlockingType = 1;  // 'frp_fifoout' type parameter: '1' for blocking port(AXIS/FIFO/AP_HS)
                                //                               '0' for non-blocking port(Memory/AP_VLD...)
   parameter PipeLatency = 4;
   parameter PipelineII  = 1;
   parameter DataWidth   = 32;
   parameter NumWrites   = 1;
   parameter CeilLog2Stages  = 2;
   parameter CeilLog2FDepth  = 2;
   parameter PfAllDoneEnable = 2;
   
   localparam NUM_STAGES = (PipeLatency+PipelineII-1) / PipelineII; // Ceil(Latency/II)
   
   function isDefined;
      input val;
      begin
         isDefined = (val === 1'b0 || val === 1'b1);
      end
   endfunction

   input ap_clk;
   input ap_rst;
   input [DataWidth-1:0] data_in;
   input ap_start;
   input [PipeLatency-1:0] valid;
   input               data_in_vld, data_in_last;
   input [CeilLog2Stages:0] num_valid_datasets;
   input data_out_read;
   input pf_all_done;
   input pf_continue;

   output reg [DataWidth-1:0] data_out;
   output reg data_out_vld;
   output reg pf_ready;
   output reg pf_done;
   output  empty;

   assign empty=1'b0; // output port empty is not used


   ///////// custom fifo implementation /////////
   localparam FDEPTH = NUM_STAGES * NumWrites + 1;
   reg [DataWidth-1+2:0] fifo [0:FDEPTH-1]; // the "+2" is for extrabits for {data_in_last,data_in_vld}
   reg write_enable, read_enable;
   reg fifo_empty, fifo_full, sel_pipe;
   reg signed [CeilLog2FDepth:0] fifo_rdPtr; // range is -1 to FDEPTH-1
   reg [CeilLog2FDepth:0] fifo_avail;
   reg signed [CeilLog2FDepth+1:0] ready_chk; // max -ve value is (0 - fifo_avail)
   reg                  fail;
   reg     data_out_vld_fifo;

   integer WarningSuppressThreshold;
   initial begin // for co-sim assertion
       fifo_rdPtr = -1;
       fifo_empty = 1'b1;
       fifo_full = 1'b0;
       fail = 0;
//       if(!$value$plusargs("warning_suppress_threshold=%0d", WarningSuppressThreshold)) 
$display("This is UD.\n");
           WarningSuppressThreshold = 5;
   end

   integer i;
   always @ (posedge ap_clk) begin : fifo_gen
      if (write_enable) begin
         for (i = 0; i < FDEPTH-1; i = i+1)
           fifo[i+1] <= fifo[i];
         fifo[0] <= {data_in_last, data_in_vld, data_in};
      end
   end
   // read ptr should have a positive address (MSB can be ignored)
   wire [DataWidth-1+2:0] fifo_out; // the "+2" is for extrabits for {data_in_last,data_in_vld}
   assign fifo_out = fifo[ fifo_rdPtr[CeilLog2FDepth-1:0] ];

   integer j;
   integer cnt_write_ovfl = 0;
   integer cnt_read_ovfl = 0;
   always @ (posedge ap_clk) begin : fifo_ptr
      if (ap_rst) begin
        fifo_rdPtr <= -1;
        fifo_empty <= 1'b1;
        fifo_full <= 1'b0;
      end
      else begin
          //// // synthesis translate_off
          //// if ($time > 0) begin
          ////    if ( write_enable && fifo_full && cnt_write_ovfl < WarningSuppressThreshold ) begin
          ////        $display("WARNING : fifo write overflow at time %0t", $time); fail=1;
          ////        cnt_write_ovfl = cnt_write_ovfl + 1;
          ////    end
          //// end
          //// // synthesis translate_on
         if (write_enable && !read_enable && !fifo_full) begin
           fifo_rdPtr <= fifo_rdPtr + 1;
           fifo_empty <= 1'b0;
           fifo_full <= (fifo_rdPtr == FDEPTH-2);
         end
         else if (read_enable && !write_enable && !fifo_empty) begin
           fifo_rdPtr <= fifo_rdPtr - 1;
           fifo_empty <= (fifo_rdPtr == 'd0);
           fifo_full <= 1'b0;
         end
      end
   end
   
   ///////// control logic /////////

   reg stalled, must_stall, data_cannot_vld, data_done, data_out_last_reg;
   reg data_out_last, internal_done;
   
    generate
        if(PfAllDoneEnable==2)
            always @(*) begin
                stalled = must_stall;
            end
        else
            always @ (posedge ap_clk) begin : stall_reg
                if (ap_rst) stalled <= 1'b0;
                else stalled <= must_stall;
            end
    endgenerate
   
    generate
        if (BlockingType == 1)
            always @ (*) begin : readen_control_for_blocking
                casex ({data_out_read, data_out_vld_fifo, data_out_last, fifo_empty, stalled})
                  5'b 1_X_X_0_0 : // when consumer reads and fifo is not empty.
                    read_enable = 1'b1;
                  5'b X_0_1_0_0 : // when no data in last and fifo is not empty.
                    read_enable = 1'b1;
                  default:
                    read_enable = 1'b0;
                endcase
            end
        else
            always @ (*) begin : readen_control_for_non_blocking
                casex ({fifo_empty, must_stall})
                  2'b 0_0: 
                    read_enable = 1'b1;
                  default:
                    read_enable = 1'b0;
                endcase
            end
    endgenerate

    generate
        if (BlockingType == 1)
            always @ (*) begin : writen_control_for_blocking
                casex ({ data_out_read, data_in_vld, fifo_empty, data_in_last, stalled })
                    5'b X_X_X_1_1 :
                        write_enable = 1'b1;
                    5'b X_1_X_X_1 :
                        write_enable = 1'b1;

                    5'b X_X_0_1_0 : // last valid, fifo has data
                        write_enable = 1'b1;
                    5'b 0_1_1_1_0 : // last valid, but consumer stalls (data_out_read==0), data_in_valid available
                        write_enable = 1'b1;
                    
                    5'b 0_1_X_X_0 : // data valid, but consumer stalls (data_out_read==0)
                        write_enable = 1'b1;
                    5'b 1_1_1_X_0 : // data valid, consumer ready, fifo is fifo_empty
                        write_enable = 1'b0;
                    5'b 1_1_0_X_0 : // data valid, consumer ready, fifo has data
                        write_enable = 1'b1;
                    default     :
                      write_enable = 1'b0;
                endcase
            end
        else if(BlockingType==0 && PfAllDoneEnable == 2)
            always @ (*) begin : writen_control_for_non_blocking
                casex ({ data_in_vld, fifo_empty, data_in_last, must_stall })
                  4'b 1_0_X_X :
                      write_enable = 1'b1;
                  4'b X_0_1_X :
                      write_enable = 1'b1;
                  4'b X_1_1_1 :
                      write_enable = 1'b1;
                  4'b 1_1_X_1 :
                      write_enable = 1'b1;
                  default     :
                      write_enable = 1'b0;
                endcase
            end
        else
            always @ (*) begin : writen_control_for_non_blocking
                casex ({ data_in_vld, fifo_empty, data_in_last, must_stall })
                  4'b 1_0_X_X :
                      write_enable = 1'b1;
                  4'b X_0_1_X :
                      write_enable = 1'b1;
                  4'b X_1_1_1 :
                      write_enable = 1'b1;
                  default     :
                      write_enable = 1'b0;
                endcase
            end
    endgenerate

    generate
        if (PfAllDoneEnable == 2)
            always @(posedge ap_clk) begin
                if(ap_rst) begin
                    data_cannot_vld<=1'b0;
                    data_out_last_reg<=1'b0;
                end else if(pf_all_done&&pf_continue) begin 
                    if(data_out_vld_fifo&&data_out_read&&data_out_last) data_cannot_vld<=1'b1 & (BlockingType==1);
                    else if(!data_out_vld_fifo&&data_out_last) data_cannot_vld<=1'b1;
                    else data_cannot_vld<=1'b0;

                    if(data_out_vld_fifo&&data_out_read&&data_out_last) data_out_last_reg<=data_out_last&(BlockingType==1);
                    else if(!data_out_vld_fifo&&data_out_last) data_out_last_reg<=data_out_last;
                    else data_out_last_reg<=1'b0;
                end else if(pf_all_done&&!pf_continue) begin 
                    data_cannot_vld<=1'b1;
                    data_out_last_reg<=data_out_last_reg;
                end else if(!pf_all_done) begin
                    if(data_out_last_reg) begin
                        data_cannot_vld<=1'b1;
                        data_out_last_reg<=data_out_last_reg;
                    end else if(data_out_vld_fifo&&!data_out_read) begin
                        data_cannot_vld<=1'b0;
                        data_out_last_reg<=1'b0;
                    end else if(data_out_vld_fifo&&data_out_read||!data_out_vld_fifo)begin
                        if(!data_out_last) data_cannot_vld<=1'b0;
                        else data_cannot_vld<=1'b1;
                        if(data_out_last) data_out_last_reg<=data_out_last;
                        else data_out_last_reg<=1'b0;
                    end
                end

                if(ap_rst) data_done<=1'b0;
                else if(must_stall) data_done <= data_done;
                else if ( (data_out_vld&&data_out_read||!data_out_vld_fifo&&data_out_last)||
                          (!pf_all_done||pf_all_done&&pf_continue) ) data_done <= 1'b1 & (BlockingType==1);
                else data_done <= 1'b0;
            end
    endgenerate

    generate
        if (PfAllDoneEnable == 2)
            always @ (*) begin : control
                ///////// internal signals /////////
                // data_out_vld is AMBA compliant (independent of data_out_read)
                sel_pipe    = fifo_empty;
                {data_out_last, data_out_vld_fifo, data_out} = sel_pipe ? {data_in_last, data_in_vld, data_in} : fifo_out;
                //for blocking mode, next transaction first data is already in UD fifo. They can do handshake when
                //last transaction ap_done/ap_continue does handshake
                //for non_blocking mode, next transaction first data is not in UD fifo
                data_out_vld = data_out_vld_fifo & (!data_cannot_vld || pf_continue&&pf_all_done&&data_done);

                if(pf_continue&&pf_all_done) begin
                    if(data_out_vld_fifo&&!data_out_read) must_stall=1'b1;
                    else if(data_out_vld_fifo&&data_out_read) must_stall=1'b1 & (BlockingType==0);
                    else must_stall=1'b0;

                    if(data_out_vld_fifo&&data_out_read) pf_done=data_out_last & (BlockingType==1);
                    else if(!data_out_vld_fifo&&data_out_last) pf_done=data_out_last;
                    else pf_done=1'b0;
                end else if(pf_all_done && !pf_continue) begin 
                    must_stall=1;
                    pf_done=data_out_last_reg;
                end else if(!pf_all_done) begin
                    if(data_out_last_reg) begin
                         must_stall=1'b1;
                         pf_done=data_out_last_reg;
                    end else if(data_out_vld_fifo&&!data_out_read) begin
                        must_stall=1'b1;
                        pf_done=1'b0;
                    end else if(data_out_vld_fifo&&data_out_read||!data_out_vld_fifo)begin
                        must_stall = 1'b0;
                        if(data_out_last) pf_done=data_out_last;
                        else pf_done=1'b0;
                    end else begin
                        must_stall = 1'b0;
                        pf_done = 1'b0;
                    end
                end else begin
                    must_stall = 1'b0;
                    pf_done = 1'b0;
                end

                ///////// outputs /////////
                fifo_avail = (FDEPTH - fifo_rdPtr - 1);
                // available has to be atleast one (or NumWrites) more than
                // valid transactions being processed in the pipeline. Then this
                // fifo buffer can accept the "valid" data in the following cycle.
                // pf_ready = (fifo_avail - (num_valid_datasets * NumWrites) >=
                // NumWrites);
                // above expr simplified for hardware
                                ready_chk = (NumWrites - fifo_avail + (num_valid_datasets * NumWrites));
                  pf_ready = ready_chk < 0;
            end // block: control
        else if (PfAllDoneEnable == 1)
            always @ (*) begin : control
               ///////// internal signals /////////
               // data_out_vld is AMBA compliant (independent of data_out_read)
               sel_pipe    = fifo_empty;
               {data_out_last, data_out_vld_fifo, data_out} = sel_pipe ? {data_in_last, data_in_vld, data_in} : fifo_out;
               data_out_vld = data_out_vld_fifo & !stalled;

               casex ({data_out_vld_fifo, data_out_last, pf_continue&pf_all_done, stalled, data_out_read})
                 5'b 0_0_X_0_X : {internal_done, must_stall} = 2'b 0_0;
                 5'b X_X_0_1_X : {internal_done, must_stall} = 2'b 1_1;  // when 'stalled', should wait until 'pf_continue'.
                 5'b X_X_1_1_X : {internal_done, must_stall} = 2'b 1_0;  // when 'pf_continue' arrived, 'stalled' register is de-asserted first.
                                                                         // This is to avoid the combinational loop on 'pf_done'.
                                                                         // loop: pf_done->ap_done->done_sync->ap_continue->pf_continue->pf_done.
                 5'b 0_1_0_0_X : {internal_done, must_stall} = 2'b 1_1;  // When there is only 'data_out_last', no need to wait 'data_out_read'.
                 5'b 0_1_1_0_X : {internal_done, must_stall} = 2'b 1_0;

                 5'b 1_1_X_X_0 : {internal_done, must_stall} = 2'b 0_0;  // when there are 'data_out_vld' and 'data_out_last' in the same cycle, 'internal_done' has to handshake with 'data_out_read'.
                 5'b 1_1_1_0_1 : {internal_done, must_stall} = 2'b 1_0;
                 5'b 1_1_0_0_1 : {internal_done, must_stall} = 2'b 1_1;
                 default       : {internal_done, must_stall} = 2'b 0_0;
               endcase
               pf_done = internal_done&!(pf_continue&pf_all_done);

               ///////// outputs /////////
               fifo_avail = (FDEPTH - fifo_rdPtr - 1);
               // available has to be atleast one (or NumWrites) more than
               // valid transactions being processed in the pipeline. Then this
               // fifo buffer can accept the "valid" data in the following cycle.
               // pf_ready = (fifo_avail - (num_valid_datasets * NumWrites) >=
               // NumWrites);
               // above expr simplified for hardware

                               ready_chk = (NumWrites - fifo_avail + (num_valid_datasets * NumWrites));
                 pf_ready = ready_chk < 0;
            end // block: control
        else
            always @ (*) begin : control
     
                 ///////// internal signals /////////
     
                 // data_out_vld is AMBA compliant (independent of data_out_read)
                 sel_pipe    = fifo_empty;
                 {data_out_last, data_out_vld_fifo, data_out} = sel_pipe ? {data_in_last, data_in_vld, data_in} : fifo_out;
                 data_out_vld = data_out_vld_fifo & !stalled;
     
                 casex ({data_out_vld_fifo, data_out_last, pf_continue, stalled, data_out_read})
                   5'b 0_0_X_0_X : {internal_done, must_stall} = 2'b 0_0;
                   5'b X_X_0_1_X : {internal_done, must_stall} = 2'b 1_1;  // when 'stalled', should wait until 'pf_continue'.
                   5'b X_X_1_1_X : {internal_done, must_stall} = 2'b 1_0;  // when 'pf_continue' arrived, 'stalled' register is de-asserted first.
                                                                           // This is to avoid the combinational loop on 'pf_done'.
                                                                           // loop: pf_done->ap_done->done_sync->ap_continue->pf_continue->pf_done.
                   5'b 0_1_0_0_X : {internal_done, must_stall} = 2'b 1_1;  // When there is only 'data_out_last', no need to wait 'data_out_read'.
                   5'b 0_1_1_0_X : {internal_done, must_stall} = 2'b 1_0;

                   5'b 1_1_X_X_0 : {internal_done, must_stall} = 2'b 0_0;  // when there are 'data_out_vld' and 'data_out_last' in the same cycle, 'internal_done' has to handshake with 'data_out_read'.
                   5'b 1_1_1_0_1 : {internal_done, must_stall} = 2'b 1_0;
                   5'b 1_1_0_0_1 : {internal_done, must_stall} = 2'b 1_1;
                   default       : {internal_done, must_stall} = 2'b 0_0;
                 endcase
                 pf_done = internal_done;

                 ///////// outputs /////////
                 fifo_avail = (FDEPTH - fifo_rdPtr - 1);
                 // available has to be atleast one (or NumWrites) more than
                 // valid transactions being processed in the pipeline. Then this
                 // fifo buffer can accept the "valid" data in the following cycle.
                 // pf_ready = (fifo_avail - (num_valid_datasets * NumWrites) >=
                 // NumWrites);
                 // above expr simplified for hardware

                             ready_chk = (NumWrites - fifo_avail + (num_valid_datasets * NumWrites));
                     pf_ready = ready_chk < 0;
            end // block: control
       endgenerate
endmodule // pipeline_fifo
    
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

(* keep_hierarchy = "yes" *)
module UD_frp_pipeline_valid
  (ap_clk,
   ap_rst,
   valid_in,
   exitcond,

   valid_out,
   num_valid_datasets);

   parameter PipelineLatency =  4;
   parameter PipelineII      =  1;
   parameter ExitLatency = -1;
   parameter CeilLog2Stages   = 2;
   
   localparam NUM_STAGES = (PipelineLatency+PipelineII-1) / PipelineII; // Ceil(Latency/II)
   
   function isDefined;
      input val;
      begin
         isDefined = (val === 1'b0 || val === 1'b1);
      end
   endfunction

   input ap_clk;
   input ap_rst;
   input valid_in;
   input exitcond;
   
   
   output [PipelineLatency-1:0] valid_out;
   output [CeilLog2Stages:0] num_valid_datasets;
   reg signed [CeilLog2Stages+1:0] nvd_reg;
   assign num_valid_datasets=nvd_reg;

   reg fail;
   reg [PipelineLatency-2:0] v2;

   integer WarningSuppressThreshold;
   initial begin // for co-sim assertion
       v2 = 0;
       fail = 0;
       nvd_reg = 0;
//       if(!$value$plusargs("warning_suppress_threshold=%0d", WarningSuppressThreshold)) 
$display("This is UD.\n");
           WarningSuppressThreshold = 5;
   end

   reg [PipelineLatency-1:0] valid_out_tmp;

   assign valid_out=valid_out_tmp;
   ///////// pipeline data valid (flushable impl) /////////
   reg [PipelineLatency-2:0] v1;
   genvar i;
   generate for (i = 0; i < PipelineLatency-1; i = i+1)
     always @ (posedge ap_clk) begin
        if (ap_rst)
          v2[i] <= 0;
        else begin
           v1[i] = (i == 0) ? valid_in : v2[i-1];
           v2[i] <= (ExitLatency==i) ? (!exitcond & v1[i]) : v1[i];
        end
     end
   endgenerate

   integer j;
   ///// // synthesis translate_off
   ///// integer cnt_nvd_ovfl_warning[PipelineLatency-1:0];
   ///// // synthesis translate_on
   always @(*) begin

       valid_out_tmp = {v2, valid_in};

       //// // synthesis translate_off
       //// if ($time > 0) begin
       ////    for (j = 1; j < PipelineLatency; j = j+1) begin : loop_block
       ////       if ( !(!valid_out_tmp[j] || nvd_reg <= NUM_STAGES) && 
       ////            cnt_nvd_ovfl_warning[j] < WarningSuppressThreshold ) begin
       ////          $display("WARNING : nvd_reg overflow. valid_out_tmp[%0d]=%b nvd=%0d nstg=%0d (at time %0t)",
       ////                 j, valid_out_tmp[j], nvd_reg, NUM_STAGES, $time);
       ////          fail=1; 
       ////          cnt_nvd_ovfl_warning[j] = cnt_nvd_ovfl_warning[j] + 1;
       ////          disable loop_block;
       ////       end
       ////    end // for (j = 1; j < PipelineLatency; j = j+1)
       //// end // if ($time > 0)
       //// // synthesis translate_on
   end

   wire   valid_disable;
   assign valid_disable = (ExitLatency == -1) ? 1'b0 : (valid_out_tmp[ExitLatency] & exitcond);
   
   // Count the num valid_out_tmp datasets in the pipe stages other than the
   // first. We do NOT count valid_out_tmp[0], otherwise it will be a
   // combination loop: nvd -> pfifo.ap_ready -> valid_in -> valid_out_tmp[0] -> nvd
   reg signed [2:0] incr;
   integer cnt_nvd_out_range = 0;
   always @ (posedge ap_clk) begin
      if (ap_rst)
         nvd_reg <= 0;
      else begin
         casex ({valid_out_tmp[0], valid_out_tmp[PipelineLatency-1], valid_disable})
           3'b100:  incr =  1;
           3'b111:  incr = -1;
           3'b001:  incr = -1;
           3'b010:  incr = -1;
           3'b011:  incr = -2;
           default: incr =  0;
         endcase
         /// // synthesis translate_off
         /// if (!(0 <=($signed(nvd_reg)+incr)<=NUM_STAGES) && cnt_nvd_out_range<WarningSuppressThreshold) begin
         ///       $display("WARNING: nvd_reg out of range. incr=%d nvd=%0d nstg=%0d (at time %0t)",
         ///              incr, nvd_reg, NUM_STAGES, $time);
         ///    fail=1;
         ///    cnt_nvd_out_range = cnt_nvd_out_range+1;
         /// end
         /// // synthesis translate_on
         nvd_reg <= nvd_reg + incr;
      end
   end

   //// // synthesis translate_off
   //// integer cnt_valid_out_tmp[PipelineLatency-1:0];
   //// integer stg, stgc;
   //// always @ (posedge ap_clk) begin
   ////    stg = 0;
   ////    stgc = 0;
   ////    for (j = 0; j < PipelineLatency; j = j+1) begin : block_stgc
   ////       stgc = stgc + valid_out_tmp[j];
   ////       if (stg == PipelineII-1) begin
   ////          if ( !(stgc <= 1) && cnt_valid_out_tmp[j]<WarningSuppressThreshold) begin
   ////             $display("WARNING: valid_out_tmp=%b. %0d bits set in one pipe-stage ending at bit-%0d (at time %0t)",
   ////                    valid_out_tmp, stgc, j, $time);
   ////             fail=1; 
   ////             cnt_valid_out_tmp[j] = cnt_valid_out_tmp[j] + 1;
   ////             disable block_stgc;
   ////          end
   ////          stgc = 0;
   ////          stg  = 0;
   ////       end else begin
   ////          stg = stg + 1;
   ////       end
   ////    end // for (j = 0; j < PipelineLatency; j = j+1)
   //// end // always @ (posedge ap_clk)
   //// // synthesis translate_on

endmodule // pipeline_valid
    
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps

(* use_dsp = "yes" *) module UD_mul_8s_8s_16_2_1(clk, ce, reset, din0, din1, dout);
parameter ID = 1;
parameter NUM_STAGE = 1;
parameter din0_WIDTH = 14;
parameter din1_WIDTH = 12;
parameter dout_WIDTH = 26;
input clk;
input ce;
input reset;
input signed [din0_WIDTH - 1 : 0] din0;
input signed [din1_WIDTH - 1 : 0] din1;
output[dout_WIDTH - 1 : 0] dout;
reg signed [dout_WIDTH - 1 : 0] dout;
wire signed [dout_WIDTH - 1 : 0] tmp_product;

assign tmp_product = $signed(din0) * $signed(din1);
always @ (posedge clk) begin
    if (ce) begin
        dout <= tmp_product;
    end
end
endmodule
// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Tool Version Limit: 2019.12
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// ==============================================================

`timescale 1ns/1ps

module UD_regslice_both
#(parameter 
    DataWidth=32
)(
    input ap_clk ,
    input ap_rst,

    input [DataWidth-1:0] data_in , 
    input vld_in , 
    output ack_in ,
    output [DataWidth-1:0] data_out, 
    output vld_out,
    input ack_out,
    output apdone_blk
);
 

reg   [1:0] B_V_data_1_state;
wire   [DataWidth-1:0] B_V_data_1_data_in;
reg   [DataWidth-1:0] B_V_data_1_data_out;
wire    B_V_data_1_vld_reg;
wire    B_V_data_1_vld_in;
wire    B_V_data_1_vld_out;
reg   [DataWidth-1:0] B_V_data_1_payload_A;
reg   [DataWidth-1:0] B_V_data_1_payload_B;
reg    B_V_data_1_sel_rd;
reg    B_V_data_1_sel_wr;
wire    B_V_data_1_sel;
wire    B_V_data_1_load_A;
wire    B_V_data_1_load_B;
wire    B_V_data_1_state_cmp_full;
wire    B_V_data_1_ack_in;
wire    B_V_data_1_ack_out;

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_out) & (1'b1 == B_V_data_1_ack_out))) begin
            B_V_data_1_sel_rd <= ~B_V_data_1_sel_rd;
        end else begin
            B_V_data_1_sel_rd <= B_V_data_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_in))) begin
            B_V_data_1_sel_wr <= ~B_V_data_1_sel_wr;
        end else begin
            B_V_data_1_sel_wr <= B_V_data_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_state <= 2'd0;
    end else begin
        if ((((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) | ((2'd2 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd2;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out)) | ((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd1;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b1 == B_V_data_1_ack_out)) | (~((1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)) & ~((1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) & (2'd3 == B_V_data_1_state)) | ((2'd2 == B_V_data_1_state) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd3;
        end else begin
            B_V_data_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_A)) begin
        B_V_data_1_payload_A <= B_V_data_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_B)) begin
        B_V_data_1_payload_B <= B_V_data_1_data_in;
    end
end

always @ (*) begin
    if ((1'b1 == B_V_data_1_sel)) begin
        B_V_data_1_data_out = B_V_data_1_payload_B;
    end else begin
        B_V_data_1_data_out = B_V_data_1_payload_A;
    end
end

assign B_V_data_1_ack_in = B_V_data_1_state[1'd1];
assign B_V_data_1_load_A = (~B_V_data_1_sel_wr & B_V_data_1_state_cmp_full);
assign B_V_data_1_load_B = (B_V_data_1_state_cmp_full & B_V_data_1_sel_wr);
assign B_V_data_1_sel = B_V_data_1_sel_rd;
assign B_V_data_1_state_cmp_full = ((B_V_data_1_state != 2'd1) ? 1'b1 : 1'b0);
assign B_V_data_1_vld_out = B_V_data_1_state[1'd0];

assign ack_in = B_V_data_1_ack_in;
assign B_V_data_1_data_in = data_in;
assign B_V_data_1_vld_in = vld_in;

assign vld_out = B_V_data_1_vld_out;
assign data_out = B_V_data_1_data_out;
assign B_V_data_1_ack_out = ack_out;

assign apdone_blk = ((B_V_data_1_state == 2'd3 && ack_out == 1'b0) | (B_V_data_1_state == 2'd1));

endmodule // both

module UD_regslice_both_w1
#(parameter 
    DataWidth=1
)(
    input ap_clk ,
    input ap_rst,

    input data_in , 
    input vld_in , 
    output ack_in ,
    output data_out, 
    output vld_out,
    input ack_out,
    output apdone_blk
);

reg     [1:0] B_V_data_1_state;
wire    B_V_data_1_data_in;
reg     B_V_data_1_data_out;
wire    B_V_data_1_vld_reg;
wire    B_V_data_1_vld_in;
wire    B_V_data_1_vld_out;
reg     B_V_data_1_payload_A;
reg     B_V_data_1_payload_B;
reg     B_V_data_1_sel_rd;
reg     B_V_data_1_sel_wr;
wire    B_V_data_1_sel;
wire    B_V_data_1_load_A;
wire    B_V_data_1_load_B;
wire    B_V_data_1_state_cmp_full;
wire    B_V_data_1_ack_in;
wire    B_V_data_1_ack_out;

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_out) & (1'b1 == B_V_data_1_ack_out))) begin
            B_V_data_1_sel_rd <= ~B_V_data_1_sel_rd;
        end else begin
            B_V_data_1_sel_rd <= B_V_data_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_in))) begin
            B_V_data_1_sel_wr <= ~B_V_data_1_sel_wr;
        end else begin
            B_V_data_1_sel_wr <= B_V_data_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        B_V_data_1_state <= 2'd0;
    end else begin
        if ((((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) | ((2'd2 == B_V_data_1_state) & (1'b0 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd2;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out)) | ((2'd3 == B_V_data_1_state) & (1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd1;
        end else if ((((2'd1 == B_V_data_1_state) & (1'b1 == B_V_data_1_ack_out)) | (~((1'b0 == B_V_data_1_ack_out) & (1'b1 == B_V_data_1_vld_in)) & ~((1'b0 == B_V_data_1_vld_in) & (1'b1 == B_V_data_1_ack_out)) & (2'd3 == B_V_data_1_state)) | ((2'd2 == B_V_data_1_state) & (1'b1 == B_V_data_1_vld_in)))) begin
            B_V_data_1_state <= 2'd3;
        end else begin
            B_V_data_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_A)) begin
        B_V_data_1_payload_A <= B_V_data_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == B_V_data_1_load_B)) begin
        B_V_data_1_payload_B <= B_V_data_1_data_in;
    end
end

always @ (*) begin
    if ((1'b1 == B_V_data_1_sel)) begin
        B_V_data_1_data_out = B_V_data_1_payload_B;
    end else begin
        B_V_data_1_data_out = B_V_data_1_payload_A;
    end
end

assign B_V_data_1_ack_in = B_V_data_1_state[1'd1];
assign B_V_data_1_load_A = (~B_V_data_1_sel_wr & B_V_data_1_state_cmp_full);
assign B_V_data_1_load_B = (B_V_data_1_state_cmp_full & B_V_data_1_sel_wr);
assign B_V_data_1_sel = B_V_data_1_sel_rd;
assign B_V_data_1_state_cmp_full = ((B_V_data_1_state != 2'd1) ? 1'b1 : 1'b0);
assign B_V_data_1_vld_out = B_V_data_1_state[1'd0];

assign ack_in = B_V_data_1_ack_in;
assign B_V_data_1_data_in = data_in;
assign B_V_data_1_vld_in = vld_in;

assign vld_out = B_V_data_1_vld_out;
assign data_out = B_V_data_1_data_out;
assign B_V_data_1_ack_out = ack_out;

assign apdone_blk = ((B_V_data_1_state == 2'd3 && ack_out == 1'b0) | (B_V_data_1_state == 2'd1));

endmodule // both


